### ISSUE TITLE
Problem with proxy location

### ISSUE THREAD

**Issue by lordnynex** [leafo/lapis#100]
Trying to setup the /proxy location according to the docs. 

```
nginx: [emerg] unknown "_url" variable
```

I've tried  `set $_url '';` which results in:

```
2014/05/28 22:05:49 [error] 17664#0: *1 invalid URL prefix in "", client: 127.0.0.1, server: , request: "POST /testroute HTTP/1.1", subrequest: "/proxy", host: "localhost:8080"
```

Does ngx.location.capture accept vars? Shouldn't this be args?

Also, is it just the log line that is displaying POST because the original request is a POST? The intention was an outbound GET request.

**Comment by Guard13007** [comment]
@leafo Just ran into this issue myself, and ran `lapis new` using v1.5.1 in another directory to test, the `set $_URL '';` line is **not** generated in a new project.
