### ISSUE TITLE
Lapis 1.0.1 cant access sample

### ISSUE THREAD

**Issue by sparvu** [leafo/lapis#122]
Hi,

Sorry if this has been asked again for FreeBSD users: I am using FreeBSD 10.0 amd64. 
I have compiled and installed OpenResty latest 1.7.2.1 and luarocks. I have a single Lua installation on this system, on a prefix which is my application outside from my OS, using luajit which comes with OpenResty.

Update: This is also valid for Linux users, CentOS 5.10 amd64 for example.

Build Luarocks
---------
 Luarocks was a bit difficult to install since I had to use the latest 2.2.0 and do it as. 
  env CC=cc ./configure --prefix=${iprefix} --with-lua=/opt/sdr/analytics/kernel/luajit \
           --with-lua-include=/opt/sdr/analytics/kernel/luajit/include/luajit-2.1 --with-lua-lib=/opt/sdr/analytics/kernel/luajit/lib

Note: FreeBSD 10.0 does not use gcc, but clang. So I have tried to export CC for it.

Build Lapis
----------------
I was able then to use louarocks as:

luarocks CC=cc CFLAGS="-O3 -fPIC -I/opt/sdr/analytics/kernel/luajit/include/luajit-2.1" LD=ld LIBFLAG=-shared  install lapis

Worked fine ...

The other rocks:
----------------
My system has the following rocks installed:

ansicolors
   1.0.2-3 (installed) - /opt/sdr/analytics/kernel/lib/luarocks/rocks

lapis
   1.0.1-1 (installed) - /opt/sdr/analytics/kernel/lib/luarocks/rocks

lpeg
   0.12-1 (installed) - /opt/sdr/analytics/kernel/lib/luarocks/rocks

lua-cjson
   2.1.0-1 (installed) - /opt/sdr/analytics/kernel/lib/luarocks/rocks

luasocket
   3.0rc1-1 (installed) - /opt/sdr/analytics/kernel/lib/luarocks/rocks

Now Im trying to start a sample page and play around with Lapis. I cant do that. Somehow Im able to start the server but when trying to access Im getting these errors:

nginx: [alert] lua_code_cache is off; this will hurt performance in /home/sdr/lapislua/nginx.conf.compiled:15
2014/07/13 22:21:55 [notice] 82245#0: using the "kqueue" event method
2014/07/13 22:21:55 [notice] 82245#0: openresty/1.7.2.1
2014/07/13 22:21:55 [notice] 82245#0: built by clang 3.3 (tags/RELEASE_33/final 183502) 20130610
2014/07/13 22:21:55 [notice] 82245#0: OS: FreeBSD 10.0-RELEASE-p4
2014/07/13 22:21:55 [notice] 82245#0: kern.osreldate: 1000510, built on 1000510
2014/07/13 22:21:55 [notice] 82245#0: hw.ncpu: 2
2014/07/13 22:21:55 [notice] 82245#0: net.inet.tcp.sendspace: 32768
2014/07/13 22:21:55 [notice] 82245#0: kern.ipc.somaxconn: 128
2014/07/13 22:21:55 [notice] 82245#0: getrlimit(RLIMIT_NOFILE): 58032:58032
2014/07/13 22:21:55 [notice] 82245#0: start worker processes
2014/07/13 22:21:55 [notice] 82245#0: start worker process 82246
2014/07/13 22:22:03 [error] 82246#0: *1 lua entry thread aborted: runtime error: /home/sdr/lapislua/web.lua:1: module 'lapis' not found:
	no field package.preload['lapis']
	no file '/opt/sdr/analytics/kernel/lualib/lapis.lua'
	no file '/opt/sdr/analytics/kernel/lualib/lapis/init.lua'
	no file './lapis.lua'
	no file '/opt/sdr/analytics/kernel/luajit/share/luajit-2.1.0-alpha/lapis.lua'
	no file '/usr/local/share/lua/5.1/lapis.lua'
	no file '/usr/local/share/lua/5.1/lapis/init.lua'
	no file '/opt/sdr/analytics/kernel/luajit/share/lua/5.1/lapis.lua'
	no file '/opt/sdr/analytics/kernel/luajit/share/lua/5.1/lapis/init.lua'
	no file '/opt/sdr/analytics/kernel/lualib/lapis.so'
	no file './lapis.so'
	no file '/usr/local/lib/lua/5.1/lapis.so'
	no file '/opt/sdr/analytics/kernel/luajit/lib/lua/5.1/lapis.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	/home/sdr/lapislua/web.lua:1: in function </home/sdr/lapislua/web.lua:1>, client: 192.168.1.171, server: , request: "GET / HTTP/1.1", host: "192.168.1.41:8080"

Any ideas ? Seems related with building Lapis ? 

Thanks a lot

**Comment by leafo** [comment]
will be addressed in #367
