### ISSUE TITLE
Memory Leak?

### ISSUE THREAD

**Issue by smallsco** [leafo/lapis#123]
Hello,

I am experiencing severe memory leaks (1 MB/sec) when using applications written with Lapis, and I am not sure if this is due to a problem with Lapis itself or with something specific to my environment. This does not occur when using native Lua / OpenResty.

The symptoms appear primarily when load testing using a tool such as [Siege](http://www.joedog.org/siege-home/) to send many requests to nginx. I can reproduce this behaviour even by using the default application that is generated with "lapis new".

Steps to reproduce - create a new Lapis app, start it up in the background, and start up a load test:
```
root@littlegravitas:~/openresty# mkdir foo
root@littlegravitas:~/openresty# cd foo
root@littlegravitas:~/openresty/foo# lapis new --lua
wrote   nginx.conf
wrote   mime.types
wrote   web.lua

root@littlegravitas:~/openresty/foo# nohup lapis server 2>/dev/null 1>/dev/null &

root@littlegravitas:~/openresty/foo# siege -q -i -c 100 -t 15m http://127.0.0.1:8080
```

Next, get the PID of the nginx worker and watch as its' memory usage go up:
```
root@littlegravitas:~# ps aux | grep nginx | grep worker
root     24889  0.0  0.0 101844  2204 pts/0    S    08:59   0:00 nginx: worker process

root@littlegravitas:~# top -p 24889
```

If this is done for a non-Lapis app, memory usage remains constant after the first request. If this is done for a Lapis app, memory usage increases at roughly 1MB/sec.

Things I have tried include:
- Different versions of Linux (Ubuntu 13.10 and Ubuntu 14.04)
- Different versions of Lapis (1.00, 1.01)
- Different versions of OpenResty ( 1.7.2.1 and 1.7.0.1 )
- Different Lapis applications (the default, and the benchmarks from here: https://github.com/killercup/lapis-benchmarks )
- Turning the lua code cache on/off
- Increasing/decreasing the number of nginx worker processes

Thanks in advance for any assistance you can provide.

**Comment by qaisjp** [comment]
fixed in that commit, needs closing
