### ISSUE TITLE
newbie question - Error: attempt to call global 'getfenv' with config.moon compiled

### ISSUE THREAD

**Issue by newgeekorder** [leafo/lapis#124]
lapis looks awesome. The default example works on 8080 great

As a newbie I'm trying to do a simple port change by creating and compiling a default config.moon 

Starting the server 

```
lapis server development
```

 with a config.lua in the directory I always get 

```
Error: attempt to call global 'getfenv'
```

The config.moon is 

```
-- config.moon
import config from require "lapis.config"

config "development", ->
    port 5454

config "production", ->
  port 80
  num_workers 4
  lua_code_cache "off"
```

**Comment by checkraiser** [comment]
I've faced this issue with Lua 5.2.4. 
THe error throws when trying to read compiled config.lua file.
Do you know how to resolve this ?

**Comment by leafo** [comment]
As I mentioned in the other issue, Lapis is only compatible with 5.1
