### ISSUE TITLE
DB errors in the 9th TechEmpower benchmark

### ISSUE THREAD

**Issue by pygy** [leafo/lapis#140]
http://www.techempower.com/benchmarks/#section=data-r9&hw=peak&test=update

On the EC2 and "dedicated i7" hardware Lapis does quite well, especially when compared to other Postgres-based systems, but on the beefy "Peak" hardware, it is at the bottom of the pile with 22k db errors.

Any idea why? Should this be resolved with the switch to `pgmoon`?

While typing this message, I got curious and reviewed the Lapis code, it should have capped db updates to 500 per requests and wasn't doing it: https://github.com/TechEmpower/FrameworkBenchmarks/pull/949. Maybe this was related?

**Comment by leafo** [comment]
Closing this as there don't appear to be any errors anymore. (I am curious what changed)
