### ISSUE TITLE
before_filter function

### ISSUE THREAD

**Issue by hackers365** [leafo/lapis#154]
when i invoke before_filter function, get error like this

2014/08/28 22:50:53 [error] 4987#0: *4 lua entry thread aborted: runtime error: /data/www/image_history/app.lua:10: attempt to call method 'before_filter' (a nil value)
stack traceback:
coroutine 0:
	[C]: in function 'require'
	/usr/local/share/lua/5.1/lapis/init.lua:15: in function 'serve'
	content_by_lua:2: in function <content_by_lua:1>, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:8080"

**Comment by qaisjp** [comment]
is this a Lua-only bug?

**Comment by leafo** [comment]
fixed long ago
