### ISSUE TITLE
config.moon error: no resolver defined to resolve "postgres"

### ISSUE THREAD

**Issue by knubie** [leafo/lapis#171]
On my Lapis server I have an entry in the `/etc/hosts` files that points to the postgres database:

``` yaml
# /etc/hosts
172.17.0.41        acd2c0346aa4
fe00::0    ip6-localnet
ff00::0    ip6-mcastprefix
ff02::1    ip6-allnodes
ff02::2    ip6-allrouters
127.0.0.1  localhost
::1        localhost ip6-localhost ip6-loopback
172.17.0.39        postgres
```

And in my `config.moon` file I'm pointing to the postgres entry in the hosts file:

``` moonscript
-- config.moon
config = require "lapis.config"

config {"development", "production"}, ->
  postgres ->
    backend "pgmoon"
    host "postgres"
    database "postgres"
```

But when Lapis tries to access the database it throws the following error:

```
/usr/local/share/lua/5.1/lapis/application.lua:626:
/usr/local/share/lua/5.1/lapis/nginx/postgres.lua:85:
no resolver defined to resolve "postgres"
```

Replacing `host "postgres"` with `host "172.17.0.39"` works, however.

**Comment by mathieujobin** [comment]
dnsmasq worked great for me

http://stackoverflow.com/questions/8305015/when-using-proxy-pass-can-etc-hosts-be-used-to-resolve-domain-names-instead-of/8559797#8559797

**Comment by MiYogurt** [comment]
I  use `cat /etc/resolv.conf` find the docker nameserver is 127.0.0.11

```
    lua_code_cache ${{CODE_CACHE}};
    resolver 127.0.0.11;
    location / {
```

It's work for me 。
