### ISSUE TITLE
Handling large request bodies

### ISSUE THREAD

**Issue by seemk** [leafo/lapis#179]
Currently when making a POST request and the body's size exceeds nginx's `client_body_buffer_size` the data read will be nil. Only workaround I see at the moment is just to increase the buffer size (e.g. larger buffer for a large JSON upload route).

Is there a way to handle this without increasing the buffer size? The body gets stored inside a file if it exceeds the buffer size, so I guess the only option would be to read it from there (I couldn't find it so I assume it is not handled at the moment).

**Comment by thefosk** [comment]
+1
