### ISSUE TITLE
Lapis Flow breaks logging

### ISSUE THREAD

**Issue by lordnynex** [leafo/lapis#217]
Passing @ to a flow object ```FlowObj(@, @req)``` makes logging somewhat meaningless. 

It appears req.cmd_url is always nil (a7d0b9acabb178a9e5626a38c49199456fb52c5f/lapis/logging.moon#L59)

cmd_mth and flatten_params function as expected. 

Example:
```
2014/12/07 14:47:09 [notice] 8846#0: *991 [lua] [C]:-1: [200] PUT nil - { blah: "bar" }, client: 127.0.0.1, server: , request: "PUT /foo/bar HTTP/1.1", host: "localhost:8080"
```

Instantiating the flow object by just passing @req (without @) does not break logging.

**Comment by lordnynex** [comment]
Sorry for the long delay. I am not manually initiating logging. This is the normal in-built lapis logging that breaks.

**Comment by lordnynex** [comment]
I can not reproduce this. Seems like an anomaly. Closing to keep your issue list clean.

**Comment by lordnynex** [comment]
I lied this bug is still present. It may be something I'm doing wrong but here is an example

```moon
-- app.moon
lapis = require "lapis"

FlowControllerTest = require("FlowControllerTest")

class extends lapis.Application
    "/": =>
        "Welcome to Lapis #{require "lapis.version"}!"

    "/test": =>
        status: 200, json: { foo: "Bar" }

    "/testflow": =>
        return FlowControllerTest(@, @req)\testLogging!, layout: false
```

```moon
-- FlowControllerTest.moon
import Flow from require("lapis.flow")
config = require("lapis.config").get!

class FLowControllerTest extends Flow
    new: (obj, req)=>
        super(obj, req)
    testLogging: =>
        status: 200, json: { foo: "Bar" }
```

GET /test
```
2015/02/09 13:40:06 [notice] 4608#0: *3 [lua] [C]:-1: [200] GET /test - {  }, client: 127.0.0.1, server: , request: "GET /test HTTP/1.1", host: "localhost:8080"
```

GET /test/flow
```
2015/02/09 13:40:45 [notice] 4608#0: *3 [lua] [C]:-1: [200] nil nil - {  }, client: 127.0.0.1, server: , request: "GET /testflow HTTP/1.1", host: "localhost:8080"
```

With Flow
```moon
-- logging.moon
  cmd = "#{req.cmd_mth} #{req.cmd_url}"
  print colors(t)\format status, cmd, flatten_params r.url_params
```

req.cmd_mth and req.cmd_url seem to be always nil.

**Comment by leafo** [comment]
What's the purpose of the second argument you're passing to the flow constructor? Just pass `@` as only argument.

**Comment by lordnynex** [comment]
@leafo no idea! :) I think I made some assumptions about how flow works from #216. Removing @req solves the issue. Thank you!
