### ISSUE TITLE
new to lapis

### ISSUE THREAD

**Issue by hwongcom** [leafo/lapis#229]
I'm exploring converting php to lapis... exploring... because i've read that there are a lot of modules not available...

where can i find the module for payment gateway connection such as paypal? would like to test if payment is viable.

great work on lapis by the way. i see huge potential but as mentioned, only certain parts of the modules that is keeping me from going all in.

**Comment by VaiN474** [comment]
I too have made the jump from php to lapis (greatly prefer coding in Lua). However I'm not doing any e-commerce or payment stuff so I haven't looked into that much.

It seems you aren't the only one interested in such a feature though, as a quick search revealed this which may be helpful:
https://github.com/Chewbye/lua-resty-paypal

I hope that can get you started in the right direction. Lapis is an amazing framework, stick with it and I'm sure you'll be glad you did.

**Comment by leafo** [comment]
I also extracted some code, but it's undocumented at the moment: https://github.com/leafo/lua-payments
