### ISSUE TITLE
Spelling mistakes on http://leafo.net/

### ISSUE THREAD

**Issue by kireevco** [leafo/lapis#235]
Is it possible to fix spelling mistakes on the main site and in documentation?
Mistakes like 'reutrn' are very misleading when trying out a piece of a sample code.

**Comment by kireevco** [comment]
```lua
Also, what was very confusing:
app:match("/", function()
  return { render: "hello" }
end)
```

vs 

```lua
app:match("/", function()
  return { render =  "hello" }
end)
```

It never works with the colon. Should it work at all?

Thank you!

**Comment by starius** [comment]
Colon is used in MoonScript. It should be replaced with "=" in Lua version. Please, reopen this issue.

**Comment by leafo** [comment]
Could you provide me to links to the pages you notice with typos so I can fix them. Thanks.

**Comment by kireevco** [comment]
Check http://leafo.net/lapis/reference/etlua_templates.html for reutrn please as well.
Thank you.

**Comment by kireevco** [comment]
http://prntscr.com/64wlv0

**Comment by leafo** [comment]
Haven't deployed the documentation yet. Will do so shortly.
