### ISSUE TITLE
Error: module 'bit' not found:No LuaRocks module found for bit

### ISSUE THREAD

**Issue by CriztianiX** [leafo/lapis#239]
When i tried to use lapis migrate
This seems be solved installing: 
luarocks install luabitop

So, should be a dependency "luabitop"?

**Comment by lordnynex** [comment]
Hello @CriztianiX ,

This is technically a bug (missing dependency in the rockspec) in pgmoon. This migration error would not happen for other pg backend configurations. I know @leafo prefers pgmoon for the lapis db driver. This is only an issue in situations where pgmoon is used outside of nginx as LuaJIT ships with it's own bitop module.

**Comment by leafo** [comment]
thanks, added the dependency
