### ISSUE TITLE
Add HTML capture function to documentation

### ISSUE THREAD

**Issue by lordnynex** [leafo/lapis#241]
Angular use case

```moon
class Widget
  content: =>
    div class: "foo", ["data-content"]: @getFragment!

  getFragment: =>
    render_html ->
      div class: "row", ->
        text "Bar"
```

**Comment by leafo** [comment]
use the capture function: 

```moonscript
div class: "foo", ["data-content"]: capture @\getFragment
```

or

```moonscript
div class: "foo", ["data-content"]: capture -> @getFragment!
```

**Comment by leafo** [comment]
Just noticed this isn't documented, need to add it to docs.

**Comment by lordnynex** [comment]
Oh I'll give this a try. Thanks

**Comment by lordnynex** [comment]
@leafo The output of capture is correct but the end result is escaped. I've tried to wrap the output in raw() but this appears to remove the attribute from the rendered output entirely.

**Comment by leafo** [comment]
`raw` writes to the output buffer. It doesn't return a wrapped string, but instead `nil`.

The escaping takes place when you use the text as the attribute value. All attribute values are escaped. You do want it to be escaped though, eg. if your capture string has a quote in it you don't want to generate the following:

```html
<div hello="<div color="blue"></div>" />
```

I'm not sure why you want the unescaped version to be put in the attribute value. If you read the attribute value from javascript it will automatically unescape what was written in the HTML, so you should get what you expect.

**Comment by lordnynex** [comment]
You're right. Sorry about that.
