### ISSUE TITLE
Lapis on Windows?

### ISSUE THREAD

**Issue by nelson2005** [leafo/lapis#244]
I saws an old-ish openresty-on-windows project, but a cursory glance looked like it might not be super easy.

**Comment by leafo** [comment]
openresty would be the only difficult dependency, everything else can be installed through luarocks. 

I see this but it's very out of date: https://github.com/moonbingbing/openresty_windows

**Comment by nelson2005** [comment]
yeah, I saw that one... it looked like it might not be viable.  Thanks!
