### ISSUE TITLE
typo in docs: belongs_to is not one-to-one

### ISSUE THREAD

**Issue by starius** [leafo/lapis#251]
Methods [belongs_to][belongs_to] and `has_one` have almost equal descriptions:

> A one-to-one relation where the foreign key is located on the current model.

and

> A one-to-one relation where the foreign key is located on the associated model.

I think, "one-to-one" should be replaced with "many-to-one" for `belongs_to`.

Another problem is text "Creates `get_` method for each relation" for `belongs_to`. I think it should be replaced with "Creates `get_` method for current model".

[belongs_to]: http://leafo.net/lapis/reference/models.html#describing-relationships-belongs_to

**Comment by leafo** [comment]
They both accomplish the same thing, just the location of the foreign key column is different. I think it would be confusing to say `one-to-one` on one and `many-to-one` on the other when both can be used in either scenario. I reworded and added more text clarifying.
