### ISSUE TITLE
lapis console example doesn't work (Lua)

### ISSUE THREAD

**Issue by starius** [leafo/lapis#252]
The following code is provided as an example of using Lapis console for Lua:

```lua
local lapis = require("lapis")
local console = require("lapis.console")

local app = lapis.Application()

app:match("/console", console.make())

return app
```

This code doesn't work, because [console.make()][make] returns result of `respond_to`, which [provides][respond_to] two values: a function and a table. So `app:match` is called with 3 arguments, which are interpreted by Lapis as route name, route path and a function.

Workaround:
```lua
local lapis = require("lapis")
local console = require("lapis.console")

local app = lapis.Application()

app:match("console", "/console", console.make())

return app
```

By the way, MoonScript Lapis console example works well, because it assigns result of `console.make()` to a table key (class member), so second result is dropped:

```moonscript
lapis = require "lapis"
console = require "lapis.console"

class extends lapis.Application
  "/console": console.make!
```

[make]: https://github.com/leafo/lapis-console/blob/32991214c3808564c5dd11fbc5a6a18714daf0/lapis/console/init.moon#L84
[respond_to]: https://github.com/leafo/lapis/blob/20820977a07cf210d5986ec809e49712caea6165/lapis/application.moon#L459

**Comment by leafo** [comment]
hmm, not sure why I made respond_to return two values. In any case a better workaround might be to truncate the return values of `console.make`:

```lua
app:match("/console", (console.make()))
```
