### ISSUE TITLE
Aborting: can not find suitable server installation

### ISSUE THREAD

**Issue by nelson2005** [leafo/lapis#253]
I installed openresty, luarocks, and lapis okay, and made a new app with 'lapis new --lua', but when I run 'lapis server' I get the 'can not find suitable server installation'.  Any help troubleshooting would be helpful.  My actual command line is

/modlusr/web_interface1/application>/modlusr/web_interface1/openresty/luajit/bin/lapis server
Aborting: can not find suitable server installation
/modlusr/web_interface1/application>

openresty is installed in /modlusr/web_interface1/openresty (not as root), and I'm using the luajit that comes with openresty (luarocks was configured as shown on the openresty site at http://openresty.org/#UsingLuaRocks)

**Comment by starius** [comment]
Hi,

use following commands:
```bash
$ export LAPIS_OPENRESTY=/modlusr/web_interface1/openresty
$ /modlusr/web_interface1/openresty/luajit/bin/lapis server
```

See http://leafo.net/lapis/reference/command_line.html

**Comment by nelson2005** [comment]
Thanks, that's one of the things I tried

$export LAPIS_OPENRESTY=/modlusr/web_interface1/openresty
$/modlusr/web_interface1/openresty/luajit/bin/lapis server
Aborting: can not find suitable server installation

It seems to me that lapis ought to find nginx based on the path lookup in the command line reference you linked to.  The nginx binary is as I would expect in

/modlusr/web_interface1/openresty/nginx/sbin/nginx

**Comment by lordnynex** [comment]
```which nginx```

You're better off making sure the nginx binary executable is in $PATH. 

A side note about openresty, I've gone to great lengths in the past to make complex directory structures at compile time. It almost always has minor side operational side effects. Things like pid's body buffer directories, their permissions etc become a pain. IMHO, this complex directory structure is not worth it.

**Comment by nelson2005** [comment]
I'd prefer not to modify the $PATH, that often results in broken things when scripting.  Like someone else logging in with a different $PATH and things not working.

Also, what do you mean by a complex directory?  I just installed openresty in a directory... what else could I do?  I don't have root.

After poking about in openresty/luajit/share/lua/5.1/lapis/cmd/nginx.lua, it looks like the LAPIS_OPENRESTY environment variable is directly used as the name of the nginx binary.

setting the export to point to the nginx binary as in
export LAPIS_OPENRESTY=/modlusr/web_interface1/openresty/nginx/sbin/nginx

seems to fix the problem.  If someone has a moment to update the documentation at

http://leafo.net/lapis/reference/command_line.html

that might help someone else in the future.

**Comment by leafo** [comment]
Was the text above it not clear?

> If you need to manually specify the location of the OpenResty binary you can do so with the LAPIS_OPENRESTY environment variable:

Was it confusing because the example called the binary openresty instead of nginx?

**Comment by starius** [comment]
> Was it confusing because the example called the binary openresty instead of nginx?

I think, [my first comment](https://github.com/leafo/lapis/issues/253#issuecomment-90133300) is confusing, because I used LAPIS_OPENRESTY as a directory, where OpenResty is installed. I misunderstood the example provided in [the documentation](http://leafo.net/lapis/reference/command_line.html):

```
$ LAPIS_OPENRESTY=/home/leafo/bin/openresty lapis server
```

I think, the documentation could be a bit more clear, if it said "the location of the OpenResty **or nginx** binary" and provided two examples:

```
$ LAPIS_OPENRESTY=/home/leafo/bin/openresty lapis server
$ LAPIS_OPENRESTY=/home/leafo/openresty/nginx/sbin/nginx lapis server
```

**Comment by nelson2005** [comment]
Yes, I misread the documentation as well- since the main (normal) way that lapis looks for the binary is by searching in a few common openresty install *directories*, it seemed to me that the logical extension would be to specify the openresty install directory, then the same logic would be applied.  So I incorrectly believed that the env variable should point to a directory, not a binary.

A couple of thing compounded this- on my openresty v1.7.7.2, the openresty binary is named 'resty', (not 'openresty' as in the example) and the only thing named 'openresty' is the openresty install directory.   Even when I read the lua code that does the search, it took me a moment to understand that the env variable search was done differently than default path search.  Additionally, since the error is complaining about a missing server, I read that to mean nginx, since I understood nginx to be the server for openresty.  This was reinforced by the example as well, since the first path searched is for the nginx binary.

Anyway, all those factors worked together and I reached the wrong conclusion, even though the documentation is technically correct.  Thanks for everyone's help sorting it out!

**Comment by limadm** [comment]
Hello!
Today I stepped on the same issue, my package manager installs openresty to `/opt/openresty/bin/resty` and `lapis server` was not finding it. Also, exporting `LAPIS_OPENRESTY=/opt/openresty/bin/resty` did not work, only `LAPIS_OPENRESTY=/opt/openresty/nginx/sbin/nginx` did.
Couldn't you add this information to [the getting started page](http://leafo.net/lapis/reference/getting_started.html) or even better, fix the paths lapis is searching?

**Comment by leafo** [comment]
`resty` is the command line code runner that comes with openresty, not the web server. Lapis needs to point to the nginx binary

**Comment by concatime** [comment]
Hi. I have the same issue, but I don't know exactly why!
I made a script to install OpenResty with latest components.

<code>LAPIS_OPENRESTY=/opt/openresty/nginx/sbin/nginx /opt/openresty/luajit/bin/lapis server</code>

Error!

But the installation works just perfectly: 
![help](https://cloud.githubusercontent.com/assets/26262387/26598688/1545e246-4544-11e7-959c-40bb4d4641f6.png)
