### ISSUE TITLE
travis doesn't test

### ISSUE THREAD

**Issue by starius** [leafo/lapis#254]
All builds strting from [272][272] are ended with the following text:

```
$ busted -l ./luajit

/usr/local/bin/busted_bootstrap:49: attempt to call a nil value

The command "busted -l ./luajit" exited with 0.

Done. Your build exited with 0.
```

See [difference][diff] from [previous build][prev], which runs OK.

This may a bug of lapis, of busted or of travis.

[272]: https://travis-ci.org/leafo/lapis/builds/52391046
[diff]: https://github.com/leafo/lapis/compare/ff95b661dba2...689609aabc00
[prev]: https://travis-ci.org/leafo/lapis/builds/52101163

**Comment by leafo** [comment]
Thanks, just upgraded to the latest busted. I had held back before because it doesn't support luajit without being patched, but I just put in a quick fix.
