### ISSUE TITLE
Recursive html generation with etlua files?

### ISSUE THREAD

**Issue by nelson2005** [leafo/lapis#258]
In the 'getting started with lua' documentation (http://leafo.net/lapis/reference/lua_getting_started.html)

there's a nice example of generating html by looping over the values in a list in views/list.etlua

how would one make an arbitrarily recursive list?

and so on? essentially, I'd like to 're-include' the ordered-list section of the list.etlua template.  Is there some way to do that, besides just using lua to print the html?

For example, generating the html for this tree structure

http://www.thecssninja.com/demo/css_tree/

Note:  I tried to put in some html to explain what I meant, but was foiled.  I can clarify if necessary.

**Comment by starius** [comment]
> how would one make an arbitrarily recursive list?

```etlua
<% function recursiveList(list) %>
<ol>
  <% for i, thing in ipairs(list) do %>
    <% if type(thing) == 'table' then %>
      <% recursiveList(thing) %>
		<% else %>
      <li><%= thing %></li>
    <% end %>    
  <% end %>
</ol>
<% end %>

<% recursiveList(things) %>
```

```lua
things = {
	{1, 2, 3, {4, 5}},
	6, 7
}
etlua = require 'etlua'
etlua_compiled = etlua.compile(etlua_string)
etlua_compiled()
```

> Is there some way to do that, besides just using lua to print the html?

http://leafo.net/lapis/reference/html_generation.html

> Note: I tried to put in some html to explain what I meant, but was foiled.

You can include it using "```". See [examples][1].

[1]: https://guides.github.com/features/mastering-markdown/#examples

**Comment by nelson2005** [comment]
That's helpful.  As a side note, nearly all of the html generation examples are in MoonScript- is it possible to do the html generation in pure Lua?

**Comment by starius** [comment]
> is it possible to do the html generation in pure Lua?

I think, no. See #201

**Comment by nelson2005** [comment]
thanks
