### ISSUE TITLE
Documentation bug. `HTML Generation` page does not have lua version for examples

### ISSUE THREAD

**Issue by akaRem** [leafo/lapis#259]
seen at http://leafo.net/lapis/reference/html_generation.html

**Comment by leafo** [comment]
Not sure if you're the person to answer this but I created the html generator syntax with moonscript in mind. Would people want to write that syntax in lua? It becomes pretty verbose. I made etlua specifically for lua users but never really polled any lua users to see what they prefer.

**Comment by nelson2005** [comment]
I feel like the clarification you just presented is helpful- I feel like the docs generally give the impression that the moonscript and lua approaches generally have equivalent functionality.  Making it clear that the html options are moonscript and etlua is helpful to me.

**Comment by kraftman** [comment]
Came here with the same problem, would be good to maybe just have your comment above or words to the same effect at the top of the documentation page for html generation.

**Comment by leafo** [comment]
Is it worth also providing lua translations of the html builders? Would anyone use it?

**Comment by nelson2005** [comment]
It's hard to say without seeing one.  At the very least a note that etlua plays thank role.  It's just that the documentation naturally indicates that there is a lua version, so it just struck me as odd when I found it for some things but not others.
Erik
On Aug 22, 2015 12:38 PM, leaf <notifications@github.com> wrote:Is it worth also providing lua translations of the html builders? Would anyone use it?

**Comment by soccermitchy** [comment]
I'd definitely use a Lua version of it if it's made.

**Comment by borikinternet** [comment]
I`d too.

**Comment by akaRem** [comment]
I'd too.
I don't like moonscript.. :(

**Comment by Guard13007** [comment]
If it's still wanted (which it looks like it is), I wouldn't mind going through and converting the MoonScript version of the examples to Lua, and submitting a pull for it.

I think a note should definitely be added to the top to say that this isn't recommended however. @leafo How would I add a note to the top that only shows up on the Lua version? I figured out how with the code examples, but not with anything else.

**Comment by borikinternet** [comment]
Yes, it's still wanted.

**Comment by Guard13007** [comment]
Just submitted a pull for it..but it's not very complete, as a lot of the HTML generation stuff is based on MoonScript classes. I honestly do not think this is a good idea in its current state. If anyone else wants to work on it, please do.

**Comment by turbo** [comment]
Yes, some general info on how to invoke the builder would be nice. Not just for Lua. For example, the same call structure can be created in Fennel:

```clojure
(html #(
  div { :class "main container" } #(
    (h1 #(
      (text "SuperApp ")
      (sup (. Config app_version))))
    (p #(
      (text "This is the debug interface. Use the ")
      (a { :href "#" } "API")
      (text " to build stuff. Don't rely on this interface. If you're not a developer, you shouldn't be here."))))))
```

produces this Lua code:

```lua
_1_(...)
local function _2_()
  local function _3_()
    local function _4_()
      return text("SuperApp ")(sup(Config[app_version]))
    end
    local function _5_()
      return text("This is the debug interface. Use the ")(a({href = "#"}, "API"), text(" to build stuff. Don't rely on this interface. If you're not a developer, you shouldn't be here."))
    end
    return h1(_4_)(p(_5_))
  end
  return div({class = "main container"}, _3_)
end
return html(_2_)
```

(I know there's a Fennel HTML generator, but it's not as sophisticated as Lapis')

Even if it's literally just the HTML builder. Then it can be applied to other frameworks which rely less on MoonScript (e.g. Turbo.lua (no affiliation with me)).

**Comment by turbo** [comment]
Nevermind, with @TangentFoxy's example, this works:

```clojure
(local render_html (. (require "lapis.html") render_html))

(print (render_html #(
  (html #(
    div { :class "main container" } #(
      (h1 #(
        (text "SuperApp ")
        (sup (. Config app_version))))
      (p #(
        (text "This is the debug interface. Use the ")
        (a { :href "#" } "API")
        (text " to build stuff. Don't rely on this interface. If you're not a developer, you shouldn't be here.")))))))))
```

well, up until the point where the Fennel compiler complains about all the unknown globals (the HTML tag names). But I think I can find a way around that. :smile:

**Comment by TangentFoxy** [comment]
@turbo Oh I'm glad to know that worked out for you! :D
