### ISSUE TITLE
logging system is broken

### ISSUE THREAD

**Issue by akaRem** [leafo/lapis#261]
I run helloworld app and see such things in error log. 

~~~
2015/04/11 18:37:41 [notice] 1976#0: *1 [lua] [C]:-1: [0m[[32m200[0m] [1m[36mGET /[0m - {  }[0m, client: 192.168.33.1, server: , request: "GET / HTTP/1.1", host: "test.example.com"
~~~

there are lots of missing closing brackets, empty placeholders, etc:
- `[0m[[32m200[0m] [1m[36mGET /[0m - {  }[` —8 x `[` and only 1 `]` — ??
- somethig should be in `{}`
- there is duplicated GET
- there is blank value for 'server'
- there are a lot of meaningless digits with 'm' letters

**Comment by leafo** [comment]
1. & 5. Do you not have color escape sequences available on your terminal?
2. Why should something be in `{}`, did you pass any params?
3. & 4. All notice logs from nginx automatically include that appended information that I can't control

These logs are just for development purposes, I don't recommend leaving them on in production.

**Comment by akaRem** [comment]
1 & 5 ah, ok. this is color seq. Why do they go into logfile?
2 no. this structure `{ }` is common for template engines and looks like its not filled.
3 & ok, my mistake

Well, ok.

Then I should rephrase the issue.
Color escape sequences are written in logfile so it's hard to read.

**Comment by leafo** [comment]
It depends on how you view the logs. If you open them with `tail` or `less -R` the colors will show. In any case, these logs are intended for development mode when you're running the sever in the foreground. I suggest you disable them on production server and rely on the access log for a list of requests to the server.

The `{ }` represents empty params sent to the request. It is unrelated to any template compiler.

**Comment by akaRem** [comment]
@leafo thanks for clearifying.
I dont have any lapis-powered production servers yet.

About viewing the logs.

I run some bunch of scenarios, then if they fail, I open logs.
After success, I clear them.

If lapis logger is about development only, then may be it would be better to use your own logging system and not nginx?

**Comment by leafo** [comment]
I think putting stuff like this in the notice log isn't an abuse of it. I don't think it's necessary to build something else.

In case you're curious, my workflow is to keep the sever running in a terminal while I'm developing and if something goes wrong I can scroll up.
