### ISSUE TITLE
lapis does not respect nginx config and creates its own /logs dir 

### ISSUE THREAD

**Issue by akaRem** [leafo/lapis#262]
for some reasons lapis does not respect nginx config

in config its said:
~~~
...

http {

    include mime.types;

    root            /vagrant/data/;

    error_log      /vagrant/logs/nginx-error.log debug;
    access_log     /vagrant/logs/nginx-access.log;
    log_format      '$remote_addr - $remote_user [$time_local] '
                    '"$request" $status $body_bytes_sent '
                    '"$http_referer" "$http_user_agent"';

    ...

~~~

but still `/logs` is created with forever-empty files 
~~~
access.log
error.log
~~~

__WHY__ ?

**Comment by leafo** [comment]
This is nginx's doing.

**Comment by leafo** [comment]
Those are the default logging locations. If I recall correctly the server will not start unless the log files exist. Since lapis does not parse the nginx conf file you've provided, it touches the default files to ensure the server is start-able in the minimal configuration.

**Comment by akaRem** [comment]
@leafo why you set cwd as nginx working dir? 
Is there any reason not to use default?

**Comment by akaRem** [comment]
@leafo The main idea in my recently reported issues is that using of provided cli pollutes my project dir with lots of folders and files which I then must clean by hands (or script). Its not good.

**Comment by leafo** [comment]
The working directory also controls where lua modules are loaded from by default. If the global was used it would make running multiple lapis applications on the same machine complicated or confusing. This is especially important if you have a development machine with multiple projects. I felt this was a good default.

**Comment by leafo** [comment]
If you're worried about the additional files I suggest you add them to .gitignore. If you clean them they're just going to come back.

**Comment by akaRem** [comment]
@leafo since you launch lapis with modified conf, I suggest to put something like this into 'http' section.

~~~
    lua_package_path    '/vagrant/data/?.lua;/vagrant/data/?/main.lua;/vagrant/data/lib/?.lua;/vagrant/data/lib/?/main.lua;;';
    lua_package_cpath   '/vagrant/data/?.so;/vagrant/data/?/main.so;/vagrant/data/lib/?.so;/vagrant/data/lib/?/main.so;;';
~~~

Its better because one may start server from any dir just providing correct config path

**Comment by leafo** [comment]
Feel free to add those lines to your own configurations, but I'll probably keep the default how it is. The `lapis server` command expects you to be in the correct directory anyway so it can correctly read the config and compile the nginx config file. (This is done before nginx starts, so `lua_package_path` nginx directive would not be used)

**Comment by akaRem** [comment]
@leafo ok
