### ISSUE TITLE
documentation bug at http://leafo.net/lapis/reference/etlua_templates.html ?

### ISSUE THREAD

**Issue by nelson2005** [leafo/lapis#270]
It may seem obvious, but every little bit counts when learning a framework/language

```return { render: "hello" }``` should be ```return { render = "hello" }```

```return { render: true }```  should be ```return { render = true }```

minor: 'return' is spelled incorrectly a couple of places

**Comment by leafo** [comment]
These were already fixed in docs, just haven't deployed yet. Sorry about that, will do so shortly
