### ISSUE TITLE
url_for() question

### ISSUE THREAD

**Issue by nelson2005** [leafo/lapis#271]
If my app has something like

````
app:get('projects', '/', function(self)
  print(self:url_for('choose_project'))
  return { render = true }
end)

app:match('/choose_project/*', function(self)
  return { render = 'project' }
end)
````
I get an error page in my browser along the lines of 
```...terface1/openresty/luajit/share/lua/5.1/lapis/router.lua:100: Missing route named choose_project```

so I guess I need to add a name to the 'choose_project' routing, like

```app:match('choose_project', '/choose_project/*', function(self)
  return { render = 'project' }
end)```

but that prints the string ```/choose_project/*``` in my log, not simply '/choose_project' like I expected.

What am I missing?

**Comment by VaiN474** [comment]
a named route is a reference for the full route, so this is the correct behavior.
```lua
app:get("foo","/foo/bar/bang", function(self)
    ...
end)
```
a call to `url_for("foo")` would return _/foo/bar/bang_

**Comment by nelson2005** [comment]
Thanks- so if I want to accept query parameters like /foo/bar/bang?arg1=xyz&arg2=abc how would I write the app:get and the url_for?

**Comment by VaiN474** [comment]
query parameters are passed to the route that matches what comes before them, you would write it the same way, as they don't have to be specified in the route. you would use `self.params` table to get the query keys and values passed in the URL.

**Comment by VaiN474** [comment]
I've made a helper function for printing out tables which comes in handy for testing things:

_helpers/table.lua_
```lua
function table.echo(tbl)
    local out = ""
    local indent = 1

    local function pr(s) out = out .. s end
    local function exportstring(s) return string.format("%q",s) end
    local function serialize(o)
        if type(o) == "number" then
            pr(o)
        elseif type(o) == "boolean" then
            if o then pr("true") else pr("false") end
        elseif type(o) == "string" then
            pr(exportstring(o))
        elseif type(o) == "table" then
            pr("{<br>")
            indent = indent + 1
            local tab = ""
            for i=1,indent do tab = tab .. "&nbsp;&nbsp;&nbsp;&nbsp;" end
            for k,v in pairs(o) do
                pr(tab .. "[")
                serialize(k)
                pr("] = ")
                serialize(v)
                pr(",<br>")
            end
            indent = indent - 1
            tab = ""
            for i=1,indent do tab = tab .. "&nbsp;&nbsp;&nbsp;&nbsp;" end
            pr(tab .. "}")
        else
            pr(tostring(o))
        end
    end

    pr(tostring(tbl)..":&nbsp;{<br>")
    for k,v in pairs(tbl) do
        pr("&nbsp;&nbsp;[")
        serialize(k)
        pr("] = ")
        serialize(v)
        pr(",<br>")
    end
    pr("}<br>")
    return out
end
```
you can add it to your app with `table = require("helpers.table")` and just call `table.echo(self.params)` to see them printed out nice and neat

**Comment by leafo** [comment]
@nelson2005 the second argument to `url_for` is a table of parameters that go into the route, the third argument is a table of parameters that get converted into the get parameters. urls using splats currently don't support overriding the `*` using `url_for`, it's a bug.

**Comment by nelson2005** [comment]
Okay, then it sounds like I shouldn't use url_for in the case of splatted routes?

Thanks to all who replied

**Comment by nelson2005** [comment]
I'm fine with closing this, I had an incorrect understanding of splatted routes.
