### ISSUE TITLE
Large file upload

### ISSUE THREAD

**Issue by nelson2005** [leafo/lapis#272]
There's an example of uploading a file in the utilities documentation at

http://leafo.net/lapis/reference/utilities.html

But it notes that the entire file will be cached in memory.  Is there some way to do this with non blocking streaming to disk?  I've seen some openresty examples, but haven't found anything for lapis.

**Comment by leafo** [comment]
There currently isn't a way for lapis to do this. In the past I've just used a plain nginx lua handler. Here's some code I wrote that reads/writes a model and streams an upload to disk:

https://github.com/leafo/streak.club/blob/master/handle_upload.moon

And the nginx location for it: https://github.com/leafo/streak.club/blob/master/nginx.conf#L48

**Comment by nelson2005** [comment]
That's helpful, gives me a good start.  Out of curiosity, would you happen to know of a lua example?
On Apr 15, 2015 7:50 PM, leaf <notifications@github.com> wrote:There currently isn't a way for lapis to do this. In the past I've just used a plain nginx lua handler. Here's some code I wrote that reads/writes a model and streams an upload to disk:

https://github.com/leafo/streak.club/blob/master/handle_upload.moon

And the nginx location for it: https://github.com/leafo/streak.club/blob/master/nginx.conf#L48

**Comment by nelson2005** [comment]
I'll poke around, see if I can find something.
