### ISSUE TITLE
Trailing slash redirect optional

### ISSUE THREAD

**Issue by Nijikokun** [leafo/lapis#276]
In some cases a redirect is not optimal as a solution, it would be much better to treat them as the same (see Express) optionally with a flag on the app to turn redirection on.

Basically when the `redirectTrailingSlashFlag` (psuedocode, just an example) is `false`:

`/about` and `/about/` execute the same code (they are treated as the same).

When it is `true`:

`/about/` redirects to `/about`

---

Is there a way I can do this via regexp, or can you add this feature?

**Comment by leafo** [comment]
Are you using Lua or MoonScript?

In moonscript just override the `default_route` method in your application: https://github.com/leafo/lapis/blob/master/lapis/application.moon

It's a *callback* so it receives the request object instead of the application as self

**Comment by Nijikokun** [comment]
Lua

**Comment by Nijikokun** [comment]
@leafo Making two routes for the same thing is out of scope for what I am doing, it will not be possible to do that, how would I handle this in Lua with the `default_route`?

**Comment by leafo** [comment]
this should work: 

```lua
local lapis = require "lapis"

local app = lapis.Application()

app.default_route = function(self)
  local path = self.req.parsed_url.path:match("^(.*)/$")

  if path and self.app.router:resolve(path, self) then
    return
  end

  return self.app.handle_404(self)
end

app:get("/hello", function()
  print "it worked"
end)


local spec = require "lapis.spec.request"
print(spec.mock_request(app, "/hello/"))
print(spec.mock_request(app, "/hello"))
```

**Comment by Nijikokun** [comment]
That works perfectly :+1:  thanks :)
