### ISSUE TITLE
Lapis app on multiple ports?

### ISSUE THREAD

**Issue by nelson2005** [leafo/lapis#278]
I know it's possible for nginx to serve assets on more than one port.  Is there some way to do this with lapis?

**Comment by leafo** [comment]
Yeah, just create multiple `server` blocks, or set multiple `listen` directives in nginx config. Do you want the same lapis app to serve all the ports? Multiple `listen` would work best for that. Otherwise do multiple `server`.

**Comment by nelson2005** [comment]
okay,thanks, I wondered about that... in that case, only one of the ports could be set in config.lua, and the others would need to be directly entered in the nginx config?  That is, confirming ```listen ${{PORT}};``` doesn't have some extended syntax like ```listen ${{PORT1}};``` that the nginx config compiler knows about.

**Comment by leafo** [comment]
You can just make new variables in `config.lua`/`config.moon` and use them in the nginx config. Keep in mind the built in helpers for doing tests default to assuming a single port, so if you have multiple applications you might need some additional code to test each of them.

**Comment by nelson2005** [comment]
so referencing my previous example, if I set config.lua to have  ```port1 = 9091,`` then I can reference PORT1 in the nginx config and the nginx config compiler will do the substitution?

**Comment by leafo** [comment]
Yup

**Comment by nelson2005** [comment]
thanks much!
