### ISSUE TITLE
UDP server app?

### ISSUE THREAD

**Issue by nelson2005** [leafo/lapis#279]
Is it possible to make an UDP server with lapis?  It looked to me like it might be a future feature, but wondered if anyone has done this.

**Comment by leafo** [comment]
Openresty doesn't support UDP as far as I know, so until then I won't be considering it.

Currently Lapis is coded specifically with HTTP in mind. What would you like Lapis to provide for UDP servers? You could still use the database code and the helpers with no issues as there are no strict dependencies on HTTP. But things like routing, sessions, headers, cookies, get/post params don't make sense .

**Comment by nelson2005** [comment]
Fair enough.  I guess it's more of an Openresty question, I posted it over there.  I suppose the main thing I'd want from Lapis is the config.lua values.

Would
```lua
require("lapis.config").get()
```
still work in nginx.conf?

**Comment by starius** [comment]
> Would
> `require("lapis.config").get()`
> still work in nginx.conf?

It should work. Generally all code working in app.lua works in nginx.conf.

**Comment by nelson2005** [comment]
okay, thanks
