### ISSUE TITLE
render options

### ISSUE THREAD

**Issue by nelson2005** [leafo/lapis#281]
Is there any way to set the status code *without* using a view?

from the render options page,

```lua
app:match("/", function(self)
  return { render = "error", status = 404}
end)
```
renders the view named 'error'.  Is there some way to just return the status code and result text?  for example

```lua
app:match("/", function(self)
  return { render_text = "you made a mistake", status = 404}
end)
```

The docs say the options are copied to self.options, so I (unsuccessfully) tried

```lua
app:match("/", function(self)
  self.options.status = 404
  return "you made a mistake"
end)
```

**Comment by nelson2005** [comment]
my mistake, what I tried *did* work.

**Comment by nelson2005** [comment]
If I wanted to do it in one line, without separately setting self.options.status, is there some way to do that?

Like in my example
```lua
return { render_text = "you made a mistake", status = 404, layout = false}
```
can be written as
```lua
ngx.say("you made a mistake")
self.options.status = 404
return { layout = false}
```

but that gets pretty verbose, especially if it's used frequently.

**Comment by leafo** [comment]
you can put a string in the table as positional argument or return two values:

```moon
"/route": => "hello", status: 404
"/route2": => { "hello", status: 404 }
```

**Comment by nelson2005** [comment]
okay, got it that's MoonScript?  In Lua, it might be something like this?
```lua
app:match("/route", function(self)
   return { "hello", status = 404, layout = false}
end)
```

**Comment by leafo** [comment]
In lua, either work: 

```lua
return { "hello", status = 404, layout = false }
return "hello", { status = 404, layout = false }
`````

**Comment by nelson2005** [comment]
thanks!
