### ISSUE TITLE
strict mode in lapis?

### ISSUE THREAD

**Issue by nelson2005** [leafo/lapis#282]
I've tried a couple of different strict.lua implementations but I haven't managed to get any of them to work.  Does anyone know of a strict implementation that's known to work with lapis?  I'm hoping to disallow global variable creation, at least in my own code.

**Comment by starius** [comment]
I use the following bash script to find all nonstandard global variables (getting and setting):

```bash
#!/bin/bash

(for f in $@; do luac -l -p $f; done) | egrep ETGLOBAL | \
    awk '{print $7}' | \
    ( ! egrep -wv \
    "string|xpcall|package|tostring|print|os|unpack|require|getfenv|setmetatable|next|assert|tonumber|io|rawequal|collectgarbage|getmetatable|module|rawset|math|debug|pcall|table|newproxy|type|coroutine|_G|select|gcinfo|pairs|rawget|loadstring|ipairs|_VERSION|dofile|setfenv|load|error|loadfile" )
```

How to use it:
```bash
$ lua-globals.sh foo.lua bar.lua
var1
var2
$ lua-globals.sh `find src -name '*.lua'`
```
Exit status of the script is 0, if no global variables are used, and 1, if global variables are used. It can be used in CI.

**Comment by nelson2005** [comment]
that's helpful, other alternatives are also welcome!

**Comment by leafo** [comment]
Are you using MoonScript? The [MoonScript linter](http://moonscript.org/reference/command_line.html#linter) works well for this, here's the lint config I use: https://github.com/leafo/streak.club/blob/master/lint_config.moon

**Comment by nelson2005** [comment]
no, not using MoonScript- I was hoping for something like one of the many 'strict.lua' implementations

https://www.google.com/search?q=lua+strict&ie=utf-8&oe=utf-8

I'll close this issue, I'm still interested if knowing if anyone has more input.
