### ISSUE TITLE
Suppressing HTML generation

### ISSUE THREAD

**Issue by nelson2005** [leafo/lapis#288]
If I specify an empty return string for a route, like 

```lua
app:get("/", function()
  return ''
end)
```
the server returns something like
```
<!DOCTYPE HTML><html lang="en"><head><title>Lapis Page</title></head><body></body></html>
```
I'd like to suppress that HTML and only return the HTTP response line, like
```
HTTP/1.1 200 OK
```
Is there any way to do that?

**Comment by leafo** [comment]
You have to disable the layout, you should do 

```lua
app:get("/", function()
  return { layout = false }
end)
```

**Comment by nelson2005** [comment]
That's perfect, thanks
