### ISSUE TITLE
respond_to broken

### ISSUE THREAD

**Issue by ghost** [leafo/lapis#302]
When following the lua version of the documentation, use of respond_to results in the error "attempt to call global 'respond_to', a nil value".

**Comment by digipanda** [comment]
It turns out that in the documentation for lua, the line "local respond_to = require("lapis.application").respond_to" is left out. Using this should fix the problem.

**Comment by toastal** [comment]
Thank you for this! I just ran into this issue.

**Comment by sinalpha** [comment]
same problem. Adding `respond_to = require("lapis.application").respond_to` works on me.

**Comment by Onuonga** [comment]
I can see that the code base here:https://github.com/leafo/lapis/blob/master/docs/actions.md takes care of all this but it has not been updated to the actual docs that are available here: http://leafo.net/lapis/reference/actions.html . Do we need to hit a freeze and update the docs ?

**Comment by leafo** [comment]
Docs should be updated now, tell me if you're not seeing something you expect and where.
