### ISSUE TITLE
What's the search engine that powers itch.io?

### ISSUE THREAD

**Issue by hwongcom** [leafo/lapis#303]
What's the search engine that powers itch.io?
Can you provide the source to the paypal payment etc?
Anyway, I'm new to lapis and lua so just exploring... Will be great if you can make something open source... "cms"/software kind of solution maybe? like wordpress etc, so can have wider adoption and easier to narrow down on practical use case scenario situation... Sorry for asking so much, I apologize. It's a roadmap / direction afterall. Just imho.

Irrespective, I just want to say extremely impressed with your work on lapis, moonscript etc. You are incredible. And thank you for making all these possible. I really hope it can be more mainstream like node.js. After looking at lapis. I regretted writing a few things on node.js when I can write in lua/moonscript.

Will definitely adopt moonscript, as I'm going to convert all my node.js into moonscript/lapis.

**Comment by leafo** [comment]
search on itch.io currently uses postgres fulltext search. I'm not really too satisfied with the results though. The dictionary I'm using is english based and has trouble with game names.

I've experimented with the pg_tgrm module, and it appears to give better results in the general case: http://www.postgresql.org/docs/9.1/static/pgtrgm.html

**Comment by leafo** [comment]
Closing, feel free to ask more questions though :)
