### ISSUE TITLE
normalization of URLs

### ISSUE THREAD

**Issue by nelson2005** [leafo/lapis#304]
if I have a route like
```lua
app:get('/get_log', require('actions.get_log'))
```
and I put something like  http://server//crde_get_log in my browse(note the double slash after 'server'), I get a lapis error like

...resty-1.7.7.2/luajit/share/lua/5.1/lapis/application.lua:393: Failed to find route: //get_log

I'm not sure if that's a feature or a bug- I've tried adding duplicate slashes in various URLs around the net- many sites accept them, a few don't.

**Comment by leafo** [comment]
The only normalization that takes place is if there is a trailing slash in the path and no match, a redirect will take place to the non-trailing slash version of the URL.

**Comment by nelson2005** [comment]
Okay, thanks.  And thanks for lapis, it's great!
