### ISSUE TITLE
Attempt to index field 'http_host' (a nil value)

### ISSUE THREAD

**Issue by thefosk** [leafo/lapis#305]
I am seeing the following exception in my logs:

```
handle_error(): /usr/local/share/lua/5.1/lapis/nginx.lua:104: attempt to index field 'http_host' (a nil value)
stack traceback:
	/usr/local/share/lua/5.1/lapis/nginx.lua:104: in function 'fn'
	/usr/local/share/lua/5.1/lapis/nginx.lua:133: in function '__index'
	/usr/local/share/lua/5.1/lapis/application.lua:402: in function </usr/local/share/lua/5.1/lapis/application.lua:400>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/lapis/application.lua:400: in function 'dispatch'
	/usr/local/share/lua/5.1/lapis/nginx.lua:181: in function 'serve'
	content_by_lua(nginx.conf:114):1: in function <content_by_lua(nginx.conf:114):1>, client: 61.240.144.66, server: , request: "GET / HTTP/1.0"
```

**Comment by lordnynex** [comment]
Hello, this is a really odd error. The code in question has been present for 2 years. Can you provide any more information? Lapis version, openresty version, an nginx conf that can reproduce this.

**Comment by thefosk** [comment]
* Lapis 1.1.0-1
* OpenResty 1.7.10.2rc0
* Nginx bit:

```nginx
location / {
  default_type application/json;
  content_by_lua 'require("lapis").serve("kong.api.app")';
}
```

Where `kong.api.app` is the Lapis app.

**Comment by leafo** [comment]
Is the http request sent to lapis without a host header?

**Comment by thefosk** [comment]
The error is being logged remotely by another user, and it seems to be replicable by making the following request:

```
GET / HTTP/1.0\r\n\r\n
```

Adding the `Host` header seems to make it work:

```
GET / HTTP/1.0\r\nHost: 127.0.0.1:8001\r\n\r\n
```

The same request using `HTTP/1.1` **without** the `Host` header also works:

```
GET / HTTP/1.1\r\n\r\n
```

So the problem seems to happen under `HTTP/1.0` when the `Host` header is being omitted.
