### ISSUE TITLE
Lapis is awesome

### ISSUE THREAD

**Issue by vadimyer** [leafo/lapis#306]
Hey there.

This is totally what I was looking for last month (in fact, I was thinking of nginx with web framework capabilities cause no other back-end except PHP could show interesting enough results in terms of performance and ease of use and deployment for me, and here Lapis comes), something that's, now, *really at least 2x* faster for simple apps than PHP and doesn't look to be in that "hipster-style". The true power of nginx alongside a great language with beautiful syntax! I wasn't much into Lua before, but setup process was still pretty simple (though I'm still not sure why versions of Lua 5.2+ don't wanna work with that kind of thing). This project is really great.

I certainly need and will dive into world of Lua itself, but have a few beginner questions concerning Lapis:
1) How do you handle includes of other .lua files into the app so it's not "a big boss" in just one file?
2) How do you handle mailing in Lapis? Or is it something that can be in someway incorporated with Lua as a language (and some add-on library)?
3) Is there a way to run latest nginx (like 1.9.0+) with Lapis?

Thanks!

**Comment by leafo** [comment]
1. just use the `require` function from lua
2. MoonScript and mailing are completely separate things, but for mailing I've used mailgun and their http api
3. lapis needs to run in openresty, openresty isn't on 1.9 yet as far as I know

**Comment by vadimyer** [comment]
@leafo thanks! A small mistake. I was observing sources for streak.club to find out how do you include parts of application, but found only MoonScript code there. That was actually regarding first question.

**Comment by leafo** [comment]
the `include` method works the same on applications created from the lua interface as well. I'll have to update the documentation for that

**Comment by vadimyer** [comment]
Yeah, also would be nice for docs to have an example of splitting into sub-apps via standard code. There are not so many tutorials on Lapis, but existing ones are all on MoonScript. I'm feeling like not quite ready to use MoonScript without basic knowledge of standard Lua, though it's totally my problem.

**Comment by nelson2005** [comment]
Lapis is awesome, and I had a similar question about routing.  I only use Lua as well- thought Moonscript looks pretty awesome, I was new to Lua so learning two things seemed harder.  In my app.lua, I have something like
```lua
local lapis = require("lapis")
local app = lapis.Application()
app:get('/initialize', require('actions.initialize'))
app:put('/log', require('actions.log'))
```
and then in directory 'actions', I have a file named 'log.lua' that contains something like
```
return function(self)
   local crude = require('utilities.crude') --require 'utilities/crude.lua'
   crude.log(ngx, ngx.var.request_body or 'no body in log request')
   return { layout=false }  -- in this case, don't want a layout on the response
end
```
using my app.lua, you'd also need a actions/initialize.lua file as well, of course.

Anyway, kudos to @leafo for a sweet system (built on top of the amazing openresty by @agentzh)

**Comment by vadimyer** [comment]
Thanks @nelson2005 !
This is definitely a way. Though isn't it possible to not define routes in main file? Like in MoonScript, I've just included additional "controller" through require("controller") and then there's this piece of code, that doesn't work (still looking for a solution):
```
local lapis = require "lapis"

local app = lapis.Application()

app:get("/about", function(self)
        return "Welcome to Lapis"
end)

return app
```
P.S. Guess Lapis needs a forum/community board! :)

**Comment by vadimyer** [comment]
I've removed "local" from app declaration in both .lua files and it worked. But not yet sure if it's right, since according to Lua docs, local should be visible in some kind of "chunk" - I think this is the whole body of app.lua since it's not in some other "chunk" like a loop? I though I'm just including the code, and that's it, but that's not like that :)

**Comment by agentzh** [comment]
@vadimyer Just a side note: use of Lua globals is a bad idea, especially in the context of OpenResty. See

https://github.com/openresty/lua-nginx-module#lua-variable-scope

**Comment by vadimyer** [comment]
@agentzh thanks, I see. I've finally found a proper solution to split the app into sub-applications via Lua, it was actually a solution in #255 by @VaiN474 !

**Comment by nonchip** [comment]
why not just:

    local lapis = require("lapis")
    local app = lapis.Application()
    require('actions.initialize')(app)

and let the "submodules" add their own actions using the app argument?

**Comment by leafo** [comment]
Closing old issue
