### ISSUE TITLE
lapis with lua 5.3.1 doesn't "do anything"

### ISSUE THREAD

**Issue by qaisjp** [leafo/lapis#308]
I'm having issues..  the command simply doesn't work

![screenshot](http://qs.lc/vpgft)

**Comment by tst2005** [comment]
See [this](https://github.com/simoncozens/sile/commit/ec73cbbff2b19af574db0974a0febcef4b37747c#commitcomment-11583886) and my workaround :

```lua
local unpack = unpack         -- Lua <= 5.2
   or require("table").unpack -- Lua >= 5.3
assert(unpack, "unpack function is missing")
```

**Comment by qaisjp** [comment]
Yes, [editing the file in question with your change fixes it](http://qs.lc/kh6eo).

**Comment by leafo** [comment]
I can patch this but I don't recommend using lapis with 5.3. Openresty runs in luajit, aka 5.1. If you're installing binary modules and they get compiled against 5.3 they won't be loadable in openresty. The only scenario where running 5.3 on the commandline having 5.1 running in openresty would mean you installed all of lapis's dependencies twice, and you have two functional lua versions installed with paths correctly configured. I would say that's highly unlikely but maybe you can tell me more about your setup.

**Comment by qaisjp** [comment]
Indeed. I ran into several other issues with other lua related things, so I've just downgraded to 5.2. I pretty much followed the entire tutorial, except with 5.3 being built.

Closing this because a separate issue can be created dedicated to 5.3 support, if needed.

**Comment by ounos** [comment]
Can you please add this piece of info somewhere on the website ? 
IMHO, it should be clearly stated that only lua 5.1 is supported for now.

**Comment by qaisjp** [comment]
I agree

**Comment by jasoncapriati** [comment]
+1

**Comment by leafo** [comment]
Alright, added a little not below the install instructions
