### ISSUE TITLE
Error loading module 'socket.core' ...

### ISSUE THREAD

**Issue by checkraiser** [leafo/lapis#311]
Hi.
I'm using lua 5.1 with openresty latest version, luarocks 2.2.1.
I've installed lapis but when running
```
require 'lapis'
```

it throws error:

```
error loading module 'socket.core' from file '/usr/local/lib/lua/5.1/socket/core.so'
```

Do you know how to resolve this issue ?

**Comment by leafo** [comment]
Sounds like a problem with your luasocket implementation. Was it compiled against 5.1?

**Comment by checkraiser** [comment]
Yes. I use Lua 5.1.
Do you know how to resolve this ?

**Comment by leafo** [comment]
I'll need to know more information about your environment to help you. Do you have a full error message? Are you running multiple versions of Lua on your system? Can you load luasocket from the Lua REPL?

**Comment by checkraiser** [comment]
Hi, i've used Lua 5.2.4 and everything is fine now. Thank you very much.
