### ISSUE TITLE
Mount lapis app under Nginx sublocation

### ISSUE THREAD

**Issue by checkraiser** [leafo/lapis#312]
Hi.
In my nginx.conf, i use the following:
```
location /test  {
      default_type text/html;
      content_by_lua_file "web.lua";
    }
```

That is, i want to run the Lapis app under subpath /test , but the result is always 404.

Do you know how to resolve this ?

**Comment by leafo** [comment]
If you define all your routes in lapis prefixed with /test and they should match

**Comment by checkraiser** [comment]
Thanks @leafo
