### ISSUE TITLE
mysql migrations dont create a connection before checking if migrations table exists

### ISSUE THREAD

**Issue by kraftman** [leafo/lapis#314]
Tried to run 'lapis migrate' for a mysql db and got an error saying it need either a luasql or ngx connection.
Had a look through and it seems it tries to check if lapis_migrations exists before creating a connection.
Solved it by adding init_db() to mysql.moon line 138, after 'escape_literal = (val) ->'
Haven't submitted it as a pull request as i dont know enough about the code to know if its a hacky fix or OK.

Cheers,
Chris

### config.lua:
local config = require("lapis.config")

config("development", {
  mysql = {
    host = "127.0.0.1",
    user = "root",
    password = "meep",
    database = "meep"
  }
})

### migrations.lua:
local schema = require("lapis.db.schema")
local types = schema.types

return {
  [1] = function()
    schema.create_table("user", {
      { "id", types.uuid },
      { "username", types.text },
      { "email", types.text },
      { "passwordHash", types.text },
      { "active", types.boolean},
    })
  end
}

### stacktrace: 

lapis migrate development --trace
Error: /usr/local/share/lua/5.1/lapis/db/mysql.lua:170: LuaSQL connection or ngx is required to escape a string literal
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/lapis/db/mysql.lua:170: in function 'escape_literal'
	/usr/local/share/lua/5.1/lapis/db/mysql/schema.lua:48: in function 'entity_exists'
	/usr/local/share/lua/5.1/lapis/db/migrations.lua:69: in function 'run_migrations'
	/usr/local/share/lua/5.1/lapis/cmd/actions.lua:243: in function </usr/local/share/lua/5.1/lapis/cmd/actions.lua:234>
	(tail call): ?
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/lapis/cmd/actions.lua:344: in function 'execute'
	/usr/local/lib/luarocks/rocks/lapis/dev-1/bin/lapis:4: in main chunk
	[C]: ?

**Comment by wyixin** [comment]
happen this issue again, how to fix this?

**Comment by wyixin** [comment]
in /usr/local/share/lua/5.1/lapis/db/mysql.lua
add
```
backends.luasql()
```
before 
```
escape_literal = function(val)
```
can fix this bug
