### ISSUE TITLE
Seen this error on older lapis version, unsure how to solve on current

### ISSUE THREAD

**Issue by OpenToClose** [leafo/lapis#315]
/usr/local/share/lua/5.1/lapis/db/postgres.lua:31: found RDS format version 1129268257, but we can only handle version 3: INSERT INTO "registerKeys" ("key", "pid") VALUES ('P6A4C', 'a') RETURNING "id"

app.lua

	local Model = require("lapis.db.model").Model
	local registerKeys = Model:extend("registerKeys")

	local function register(self)
		if not self.params.pid then return end
		local genkey = generateKey(5) -- random 5 len string

		registerKeys:create({ pid = self.params.pid, key = genkey })

		return genkey
	end

	app:match("/register/:pid",register)

config.lua

	local config = require("lapis.config")

	config("production",
		{
			session_name = "main",
			secret = "mysecretisverysecret",
			postgres =
				{
					 database = "main",
					 password = "snip"
			}
	})

It also appears I get this error with example code in the documentation, so I'm assuming a config error

**Comment by leafo** [comment]
Hmm, this is from a really old version of lapis. Any reason why you can't upgrade? RDS and ngx_postgres isn't used anymore in favor of pgmoon.

**Comment by OpenToClose** [comment]
Build I was using was from 4 months ago, simply used luarocks install lapis and it fixed everything

Many thanks!
Sorry for the unnecessary ticket

**Comment by leafo** [comment]
No problem, glad you could upgrade
