### ISSUE TITLE
disable response when using ngx.print directly

### ISSUE THREAD

**Issue by rrichardson** [leafo/lapis#318]
I have a situation where I want to directly write out some mmap'd data in response to a route handler. 

The current result is that the data gets written out of the socket correctly, it is then followed by: 
```
<!DOCTYPE HTML><html lang="en"><head><title>Lapis Page</title></head><body></body></html>
```

How can I tell lapis not to send down any response? 

I've tried to set the content and content type in my handler as follows: 
```
    self.res.headers["Content-Type"] = "text/plain"
    self.res.content = nil
```

Thanks for making such a great framework!

**Comment by nelson2005** [comment]
Is that similar to this question?

https://github.com/leafo/lapis/issues/288

**Comment by rrichardson** [comment]
Why yes. Yes it is :)
