### ISSUE TITLE
respond_to broken (in Lua)?

### ISSUE THREAD

**Issue by punchmonster** [leafo/lapis#319]
Using 'respond_to' seems to result in this error:
```
[error] 19276#0: *90 lua entry thread aborted: runtime error: ./app.lua:18: attempt to call global 'respond_to' (a nil value)
```

My test code:
```lua
app:match('index', '/', respond_to({

	--handle the GET request on index
	GET = function(self)
		self.submit_url = self:url_for('index')
		return { render = 'index'}
	end,

	--handle the POST request on index
	POST = function(self)
		return 'hello'
	end
}))
```

**Comment by leafo** [comment]
There are no global variables in lapis, you need to bring the function into scope:

```lua
local respond_to  = require("lapis.application").respond_to
```

**Comment by punchmonster** [comment]
Thanks. Maybe add it to the documentation at http://leafo.net/lapis/reference/actions.html?

It's there in the Moonscript documentation examples, but not the Lua ones.

**Comment by leafo** [comment]
Outdated issue 

(ps. all references in the docs have been updated to show the require)
