### ISSUE TITLE
Is it possible to run multiple servers and assign them to different domains?

### ISSUE THREAD

**Issue by qaisjp** [leafo/lapis#321]
Like vhosts?

**Comment by starius** [comment]
Yes, it is. Create multiple `server` sections in `nginx.conf`, each of them forwarding requests to a Lapis.

[Read more](http://nginx.org/en/docs/http/server_names.html) about nginx configuration and server names.

**Comment by idevz** [comment]
sounds good, and it's better to use include directive like 
``` include  "vhost/*.conf";
```
to contain multiple servers, each app uese a single conf file.

**Comment by qaisjp** [comment]
Thanks @starius and @idevz!
