### ISSUE TITLE
Different cookies secrets and postgresql databases for different sites one the same server.

### ISSUE THREAD

**Issue by yurevich1** [leafo/lapis#323]
I have two different sites on the same server. How to setup config.lua depending on the site? I want different secrets and databases/users/etc.
This part
-- config.lua
`config("development", {
  postgres = {
    host = "127.0.0.1",
    user = "pg_user",
    password = "the_password",
    database = "my_database"
  }
})`
and this part:
`default_config = {
  port = "8080",
  secret = "please-change-me",
  session_name = "lapis_session",
  code_cache = "off",
  num_workers = "1",
  logging = {
    queries = true,
    requests = true
  }
}`

is `/usr/local/share/lua/5.1/lapis/config.lua` the only place to setup the config? Or I can do it inside my `app.lua` code file?

**Comment by leafo** [comment]
It's not trivial to do without some major hacking. The config is essentially a collection of global variables. Additionally lapis is currently built with only having one database connection configuration active at one time.

I'd like to address these things in the future, but for the time being you'll probably have to work around it in a different way.

In the past, when I run multiple lapis applications on the same physical machine I'll run each in their own independent openresty process each with their own port, then a primary openresty/nginx that reverse-proxies to the correct openresty instance based on the hostname.

**Comment by nonchip** [comment]
I'm doing this by deploying several instances (better anyway, because so you can't kill siteA by a critical error(500) in siteB) of https://github.com/nonchip/lazuli (my lapis based framework that creates portable installations per site) and then having a single system wide nginx on port 80 as a proxy, which handles the virtual host names

**Comment by leafo** [comment]
Going to close this. 

The current recommended method is to run one lapis app per openresty.
