### ISSUE TITLE
"Modularized" framework

### ISSUE THREAD

**Issue by CriztianiX** [leafo/lapis#325]
Hello guys! i am thinking in to have the framework in modules.
Somthing like "ORM", "Core" etc...
The most common framework in this days, seems to work in this way, (django, cakephp3, symphony, etc?
will be posible?
What do  you think?

**Comment by leafo** [comment]
Would you like different packages to install? The components are already pretty independent. I've successfully used parts of lapis in command line tools with no modifications or hacks.

**Comment by CriztianiX** [comment]
@leafo Yes... something like "lapis-orm", "lapis", etc...
In this way, if i dont use the "orm"  then i  not need pgmoon dependency...etc.

**Comment by bdjnk** [comment]
I disagree. If someone wants individual components, they can figure it out themselves. For the standard use case, modularization would seem to be of nominal benefit, and would likely make general usage more abstruse.

**Comment by nelson2005** [comment]
On Aug 25, 2015 9:19 AM, Michael Plotke <notifications@github.com> wrote:
>
> I disagree. If someone wants individual components, they can figure it out themselves. For the standard use case, modularization would seem to be of nominal benefit, and would likely make general usage more abstruse.
>
+1

**Comment by CriztianiX** [comment]
Ok guys.. Thanks for the comments.
i will close this suggest!
