### ISSUE TITLE
doc: Lapis' dependency on Moonrocks not clear in Beginner Sections

### ISSUE THREAD

**Issue by yooden** [leafo/lapis#326]
(This feels like more fitting to a forum, but I couldn't find one.)

I'm new into both Lua and thus Lapis, and I'm running into a problem quite early in the process.

I filled up my box with all the Lua goodness, installed Lapis and Openresty, run into some problems I could solve, but I'm stumped now: While "lapis server" seems to work at first sight, accessing it returns an Internal Server Error. The command line has the following: 

    2015/09/02 20:32:05 [error] 29862#0: *1 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/lapis/init.lua:15: module 'app' not found:
    	no field package.preload['app']
    	no file '/usr/local/openresty/lualib/app.lua'
    	no file '/usr/local/openresty/lualib/app/init.lua'
    	no file '/usr/local/share/lua/5.1/app.lua'
    	no file '/usr/local/share/lua/5.1/app/init.lua'
    	no file '/root/.luarocks/share/lua/5.1/app.lua'
    	no file '/root/.luarocks/share/lua/5.1/app/init.lua'
    	no file '/usr/share/lua/5.1//app.lua'
    	no file '/usr/share/lua/5.1//app/init.lua'
    	no file './app.lua'
    	no file '/usr/local/share/lua/5.1/app.lua'
    	no file '/usr/local/share/lua/5.1/app/init.lua'
    	no file '/usr/local/lib/lua/5.1/app.lua'
    	no file '/usr/local/lib/lua/5.1/app/init.lua'
    	no file '/usr/share/lua/5.1/app.lua'
    	no file '/usr/share/lua/5.1/app/init.lua'
    	no file '/usr/local/openresty/lualib/app.so'
    	no file '/usr/local/lib/lua/5.1/app.so'
    	no file '/root/.luarocks/lib/lua/5.1/app.so'
    	no file './app.so'
    	no file '/usr/local/lib/lua/5.1/app.so'
    	no file '/usr/lib/i386-linux-gnu/lua/5.1/app.so'
    	no file '/usr/lib/lua/5.1/app.so'
    	no file '/usr/local/lib/lua/5.1/loadall.so'
    stack traceback:
    coroutine 0:
    	[C]: in function 'require'
    	/usr/local/share/lua/5.1/lapis/init.lua:15: in function 'serve'
    	content_by_lua(nginx.conf.compiled:22):2: in function <content_by_lua(nginx.conf.compiled:22):1>, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:8080"

I can find app.lua in /usr/local/share/lua/5.1/lapis/cmd/templates, init.lua in /usr/local/share/lua/5.1/lapis/ and .../pgmoon/ and not relevant app.so.

So I have two questions:
- How can I fix this?
- What went wrong during the installation? I would very much like to understand how the parts connect. Lua was installed by Apt, Lapis by luarocks, Openresty was configure/make/make installed.

$ lua -v
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
$ lapis
Lapis 1.3.0
$ /usr/sbin/nginx -v
nginx version: nginx/1.2.1
$ cat /etc/debian_version
7.8

Thanks in advance!

**Comment by soccermitchy** [comment]
Hey, did you run 'lapis new' to create a new Lapis project? If not, that's
what you may want to do.

**Comment by yooden** [comment]
Nope, I run "lapis new".

In fact, I get the same error with "lapis new && lapis server".

**Comment by yooden** [comment]
So I copied the app.lua from Lapis' template dir into Lapis' search path (at least I assume that's what I see in the lapis "binary"). As hoped, the error changed! (The new error is a missing method "build_router", quite likely just a result of my hack.)

Now I have a request at the general public: Could you please look for "app.lua" in your lapis dir? Maybe my installation is misding something...

**Comment by bdjnk** [comment]
I had the same issue. Here is [my solution](https://bbs.archlinux.org/viewtopic.php?id=188650)

**Comment by bdjnk** [comment]
Sorry, that was me being confused. Have you compiled app.moon?

Try running `moonc app.moon` to get `app.lua`

To automate this process, use a build system, like [tup](http://gittup.org/tup/)

Or, for a detailed walk-through, follow along with leafo in [this helpful video](https://www.youtube.com/watch?v=Eo67iTY1Yf8)

**Comment by yooden** [comment]
I did not compile app.moon. Is that a thing you have to do regularly every time you use Lapis, or something special to my problems?

In any case, I don't have moonc on my systems, nor is it available for my OS (Debian, either Wheezy, Jessie or Stretch). Neither is Moonscript or Tup.

Thanks for your help!

**Comment by yooden** [comment]
Ok, I clearly picked the wrong order to read the documentation. I now luarocked Moonscript, and get a nice friendly welcome message from Lapis:

Welcome to Lapis 1.3.0!

Now the question arises: Shouldn't Moonscript be part of Lapis' dependencies withing Luarocks?

**Comment by VaiN474** [comment]
Moonscript is not a dependency because Lapis does not require it. You can run a Lapis server with just plain Lua as well.

```
lapis new --lua
```
This may be preferred while learning Lua as Moonscript may be quite confusing if you aren't familiar with how Lua works first. To learn more about Moonscript be sure to check out [moonscript.org](http://moonscript.org).

Regarding [Tup](http://gittup.org/tup/), it is completely optional but can come in quite handy. I'd recommend to compile it from source following the steps on the site. If it gives you an error about `No package 'fuse' found` you will need to install the `libfuse-dev` package.

Hope that helps.

**Comment by yooden** [comment]
Ok, thanks. In that case, I wish the documentation at leafo.net would have been clearer. In the "Getting Started" section it just says that I should use `--lua` if I "want a Lua starter application", not why I would like to want one and what consequences that might have.

I had a look at Tup, but was frightened away by the fact that it uses a modified Lua parser, apparently because a trivial operator was missing. That does not fill me with confidence. There are more than enough alternatives.

**Comment by nonchip** [comment]
there's no such thing as Moonrocks anymore. also, lapis does not depend on moonscript and/or tup, it'll work just fine using plain Lua, if you want to ignore all the syntax sugar moon would give you

**Comment by Guard13007** [comment]
@leafo I believe this issue should be closed. Is there any reason it's still open?
