### ISSUE TITLE
module 'alt_getopt' not found ~ using moonc

### ISSUE THREAD

**Issue by DigitalVeer** [leafo/lapis#327]
Hello, I am trying to convert a .moon file to a .lua file using the moonc command.

I am running on OS X 10.10.5

These are the commands/errors acquired:

Veers-MBP:sample DigitalVeer$ lapis new
wrote	nginx.conf
wrote	mime.types
wrote	web.moon
Veers-MBP:sample DigitalVeer$ moonc web.moon
/usr/local/bin/lua: ...ocal/lib/luarocks/rocks-5.2/moonscript/0.3.2-1/bin/moonc:3: module 'alt_getopt' not found:Failed loading module alt_getopt in LuaRocks rock alt-getopt 0.7.0-1
	no field package.preload['alt_getopt']
	no file '/Users/DigitalVeer/.luarocks/share/lua/5.2/alt_getopt.lua'
	no file '/Users/DigitalVeer/.luarocks/share/lua/5.2/alt_getopt/init.lua'
	no file '/usr/local/share/lua/5.2/alt_getopt.lua'
	no file '/usr/local/share/lua/5.2/alt_getopt/init.lua'
	no file '/usr/local/lib/lua/5.2/alt_getopt.lua'
	no file '/usr/local/lib/lua/5.2/alt_getopt/init.lua'
	no file './alt_getopt.lua'
	no file '/Users/DigitalVeer/.luarocks/lib/lua/5.2/alt_getopt.so'
	no file '/usr/local/lib/lua/5.2/alt_getopt.so'
	no file '/usr/local/lib/lua/5.2/loadall.so'
	no file './alt_getopt.so'
stack traceback:
	[C]: in function 'require'
	...ocal/lib/luarocks/rocks-5.2/moonscript/0.3.2-1/bin/moonc:3: in main chunk
	[C]: in ?

In an attempt to fix this, I tried removing moon script, lapis, and openresty and tried reinstalling.
I also reinstall Lua using home-brew.

This here is my "luarocks list" output:

alt-getopt
   0.7.0-1 (installed) - /usr/local/lib/luarocks/rocks-5.2

ansicolors
   1.0.2-3 (installed) - /usr/local/lib/luarocks/rocks-5.2

busted
   2.0.rc10-0 (installed) - /usr/local/lib/luarocks/rocks-5.2

dkjson
   2.5-2 (installed) - /usr/local/lib/luarocks/rocks-5.2

etlua
   1.2.0-1 (installed) - /usr/local/lib/luarocks/rocks-5.2

lapis
   1.0.2-1 (installed) - /usr/local/lib/luarocks/rocks-5.2

loadkit
   1.0.0-1 (installed) - /usr/local/lib/luarocks/rocks-5.2

lpeg
   0.12.2-1 (installed) - /usr/local/lib/luarocks/rocks-5.2

lua-cjson
   2.1.0-1 (installed) - /usr/local/lib/luarocks/rocks-5.2

lua-term
   0.3-1 (installed) - /usr/local/lib/luarocks/rocks-5.2

lua_cliargs
   2.5-1 (installed) - /usr/local/lib/luarocks/rocks-5.2

luafilesystem
   1.6.3-1 (installed) - /usr/local/lib/luarocks/rocks-5.2

luasocket
   3.0rc1-2 (installed) - /usr/local/lib/luarocks/rocks-5.2

luassert
   1.7.9-0 (installed) - /usr/local/lib/luarocks/rocks-5.2

mediator_lua
   1.1.2-0 (installed) - /usr/local/lib/luarocks/rocks-5.2

moonscript
   0.3.2-1 (installed) - /usr/local/lib/luarocks/rocks-5.2

penlight
   1.3.2-2 (installed) - /usr/local/lib/luarocks/rocks-5.2

say
   1.3-1 (installed) - /usr/local/lib/luarocks/rocks-5.2

This here is my brew list:
cscope	lua	luajit	macvim	openssl	pcre	vim	wget

I am using the most updated version of openresty currently.

**Comment by leafo** [comment]
The search paths listed in the exception backtrace do not list the location where you have alt-getopt installed. Additionally you're going to run into issues since Lapis/OpenResty is designed to work with Lua 5.1, not 5.2. Is it possible to use a 5.1 version of LuaRocks?

**Comment by DigitalVeer** [comment]
I installed Lua 5.1 separately but installed the latest version of Luarocks separately.
Will this make a difference?

Also, I rebuilt alt-getopt and moonscript and its all working fine now!
Thanks @leafo !

I love your work! I plan on showing moonscript and Lapis to my High School CS teacher since I think Lua is a great language and you've just improved upon it so much.
