### ISSUE TITLE
Lapis documentation does not mention supported authentication methods for Postgres

### ISSUE THREAD

**Issue by jgonggrijp** [leafo/lapis#338]
I installed PostgreSQL 9.4.4 through MacPorts, which required me to manually create the `PGDATA` directory, `chown` it to `postgres` and run `initdb`. Being a complete Postgres n00b, I had no idea that `md5` is the de facto standard authentication method and chose `password` instead. Since pgmoon doesn't support `password`, I ran into rather opaque errors when trying to connect to my database from Lapis. With some perseverance I was able to find the cause, and fixed it by changing the default authentication method in `$PGDATA/pg_hba.conf`.

In my humble opinion, the Lapis documentation should mention this requirement early on. Lapis users are generally not going to read the pgmoon Readme first.

**Comment by leafo** [comment]
We've updated pgmoon to support the most common auth methods now. I'm going to close this issue, as most people should no longer run into this issue.
