### ISSUE TITLE
POST File integration

### ISSUE THREAD

**Issue by yurevich1** [leafo/lapis#341]
Please, add upload File feature using lapis feature via POST method.
It would be awsome, if you integrate lua-resty-upload for Lapis.
Link for the project.
https://github.com/openresty/lua-resty-upload

**Comment by qaisjp** [comment]
[don't we already have this?](http://leafo.net/lapis/reference/utilities.html#file-uploads)

**Comment by yurevich1** [comment]
Oh, thanks. This is a new feature. Wonder! Or, at least, no information was in manual when I read it.

**Comment by qaisjp** [comment]
Glad I could help!

Please close the issue :)
