### ISSUE TITLE
Failed loading module socket.url

### ISSUE THREAD

**Issue by aidylewis** [leafo/lapis#342]
I have installed lua (Lua 5.2.4) through linuxbrew
```
$ lapis new --lua
/home/lewisa29/.linuxbrew/bin/lua: /home/lewisa29/.linuxbrew/share/lua/5.2/lapis/util.lua:1: module 'socket.url' not found:Failed loading module socket.url in LuaRocks rock luasocket 3.0rc1-2
	no field package.preload['socket.url']
	no file '/home/lewisa29/.luarocks/share/lua/5.2/socket/url.lua'
	no file '/home/lewisa29/.luarocks/share/lua/5.2/socket/url/init.lua'
	no file '/home/lewisa29/.linuxbrew/share/lua/5.2/socket/url.lua'
	no file '/home/lewisa29/.linuxbrew/share/lua/5.2/socket/url/init.lua'
	no file '/home/lewisa29/.linuxbrew/lib/lua/5.2/socket/url.lua'
	no file '/home/lewisa29/.linuxbrew/lib/lua/5.2/socket/url/init.lua'
	no file './socket/url.lua'
	no file '/home/lewisa29/.luarocks/lib/lua/5.2/socket/url.so'
	no file '/home/lewisa29/.linuxbrew/lib/lua/5.2/socket/url.so'
	no file '/home/lewisa29/.linuxbrew/lib/lua/5.2/loadall.so'
	no file './socket/url.so'
	no file '/home/lewisa29/.luarocks/lib/lua/5.2/socket.so'
	no file '/home/lewisa29/.linuxbrew/lib/lua/5.2/socket.so'
	no file '/home/lewisa29/.linuxbrew/lib/lua/5.2/loadall.so'
	no file './socket.so'
```

**Comment by leafo** [comment]
1. Looks like your LUA_PATH isn't configured to match where you installed luasocket, or something about luasocket didn't install correctly
2. Lapis should only be used with 5.1, since that's what openresty is running. It's possible to use 5.2 but not worth the trouble of managing dependencies in two installation.

**Comment by aidylewis** [comment]
Thanks for the heads-up, but after a day of trying to get the server running, I've given up.

**Comment by leafo** [comment]
Why were you using linuxbrew? Your os most likely has the packages you need if you're on linux

**Comment by aidylewis** [comment]
I'm on RedHat 6.7. 

There is the Lua 5.1.4 package, but for LuaRocks I needed to manually compile. During ./configure, I get:

```
Checking Lua includes... lua.h not found
....
configure failed.

Makefile:2: config.unix: No such file or directory
make: *** No rule to make target `config.unix'.  Stop.
```

I might try the Docker route. 

Thanks

**Comment by leafo** [comment]
There are two flags you can pass to ./configure on a luarocks install to specify where your headers and libs are (there might be another flag to specify the version as well)
