### ISSUE TITLE
Documentation error -- named routes?

### ISSUE THREAD

**Issue by luhkevin** [leafo/lapis#344]
Was going through the documentation and something didn't look right to me. 
This section here: http://leafo.net/lapis/reference/actions.html#named-routes

Should this line:

    app:match("user_profile", "/", function(self)

be this instead?

    app:match("user_profile", "/:name", function(self)

Otherwise, the "user_profile" route is the same as index. However, it seems like you do intend for the route to go to an actual user_profile, which requires a "name" parameter.

**Comment by qaisjp** [comment]
Seems legit, I've created a PR to fix this
