### ISSUE TITLE
layout with etlua

### ISSUE THREAD

**Issue by Romaboy** [leafo/lapis#345]
Is it possible to use etlua and layout at the same time? All sources, that I founded, has moonscript views, it's too woefully for me to do the same. In docs there is: "Create views/layout.etlua": => etlua template, cool, than "app.layout = require "views.layout"", which couldn't work, because server is searching for .lua file. And than: -- the rest of the application..., cool, rest of the application, and how can I tell to etlua templates, that they must to go to the <% content_for("inner") %>? Maybe there is something like yield?

**Comment by soccermitchy** [comment]
To get it to allow you to use etlua templates, you need to call
app:enable'etlua'

**Comment by VaiN474** [comment]
`require "views.layout"` in Lapis is actually searching for "views/layout.etlua". Lapis knows that views are etlua files.  The `content_for("inner")` is where the body of your route/action already goes automatically.

**Comment by Romaboy** [comment]
Here is my tiny app:
Sorry, don't know how to markup the code

lapis = require "lapis"
import respond_to from require "lapis.application"
console = require "lapis.console"
import Widget from require "lapis.html"

class extends lapis.Application
	@include "controllers.auth"
	@enable "etlua"
	layout: require "views.layout"
	"/": =>
		render: 'pages.index'
	"/console": console.make!
	default_route: => render: "pages.404", status: 404

Error told, that lapis search for everything except etllua file:

2015/11/03 12:58:11 [error] 2965#0: *13 lua entry thread aborted: runtime error: ./app.lua:10: module 'views.layout' not found:
        no field package.preload['views.layout']
        no file './views/layout.lua'
        no file '/usr/share/lua/5.1/views/layout.lua'
        no file '/usr/share/lua/5.1/views/layout/init.lua'
        no file '/usr/lib/lua/5.1/views/layout.lua'
        no file '/usr/lib/lua/5.1/views/layout/init.lua'
        no file './views/layout.so'
        no file '/usr/lib/lua/5.1/views/layout.so'
        no file '/usr/lib/lua/5.1/loadall.so'
        no file './views.so'
        no file '/usr/lib/lua/5.1/views.so'
        no file '/usr/lib/lua/5.1/loadall.so'

Or problem not in lapis, but in somewhat configs?

**Comment by Romaboy** [comment]
So I tried to use some odd things, like
layout: => require "views.layout"
layout: => render: require "views.layout"
layout: => render: "layout"

Has anybody success with it? 
VaiN474, so that works in your case?

**Comment by Romaboy** [comment]
Guys?

**Comment by VaiN474** [comment]
[check the documentation](http://leafo.net/lapis/reference/html_generation.html#layouts)

**Comment by bdjnk** [comment]
> Sorry, don't know how to markup the code

This kills my desire to investigate and help. It makes your comment difficult to parse and indicates a certain unwillingness to learn that bodes ill.

**Comment by Guard13007** [comment]
Since bdjnk brings it up... @Romaboy Read [this](https://help.github.com/articles/markdown-basics/#code-formatting). Also, the rest of that page. I would also recommend very carefully re-reading the whole documentation for Lapis. There isn't very much, and I know I had a hell of a time getting anything to work because of my own inexperience, but I managed to figure it out.

**Comment by borikinternet** [comment]
You need something like this:

local lapis = require("lapis")
app:enable("etlua")
app:get("/",function(self){
return {
    layout = "layout_name",
    render = "etlua_template_name"
}

**Comment by Romaboy** [comment]
Thanks, borik, that works
In moon it will sound as

```
lapis = require "lapis"

class App extends lapis.Application
	@enable 'etlua'
	"/": =>
		layout: 'layout', render: 'pages.index'
```
Lua, moon, whatever, now would be great to know how to set layout not for each route, but for whole app

**Comment by Romaboy** [comment]
Solved!
In application.moon of lapis I changed line
layout_path = @options.layout
to
layout_path = @options.layout or @app.layout
Now it's useable!

**Comment by Romaboy** [comment]
Now need some authorization guide

**Comment by leafo** [comment]
I'm not sure what the suggested patch is supposed to fix. It's already possible to specify the layout by name as the return value.

I'm closing this issue, if you're still having an issue feel free to open it  up again.

Thanks

**Comment by bradsoto** [comment]
```moonscript
class extends lapis.Application
  layout: require 'views.layout'
```
