### ISSUE TITLE
Is is possible to setup custom headers?

### ISSUE THREAD

**Issue by yurevich1** [leafo/lapis#349]
Please, give a simple example and/or best practise, if it possible. I can't find thi inforamtion in manual.

**Comment by travisbell** [comment]
Hi @yurevich1 

You can use `ngx.header`:

```
ngx.header["Access-Control-Allow-Origin"] = "*"
ngx.header["Cache-Control"] = "public, max-age=21600"
```

I'm not sure if it's the "best practice" or not but I have been using this successfully.

**Comment by zach-binary** [comment]
I'm a little out of touch with lapis, but in my current site I use the following code to set the content-type of my response to xml.

```moonscript
@res.headers["Content-Type"] = "application/xml"
```

As shown above, the headers are exposed as part of the response property inside of a lapis application.  

Full code can be found here: https://github.com/zach-binary/throw-up/blob/master/applications/sitemap.moon

**Comment by leafo** [comment]
Although the nginx interface works I would recommend the lapis version, if we ever support more servers then the lapis way of doing it would be compatible. Additionally if your code isn't dependent on `ngx` global it's easier to test with the tools lapis provides.
