### ISSUE TITLE
Using Postgres, test driven developement for db connection

### ISSUE THREAD

**Issue by VoittajaTomi** [leafo/lapis#350]
Hi,

I am learning to use Lapis with Postgres database which is running on my computer. I want to create a "db" module to incorporate into my web-app. This module would handle the connection to database and should be runnable separately with luajit-resty. I have managed to do this with sqlite3 database, but now that I want to use Postgres, I am running into a problem:

File test_db_postgres.db:
```lua
local lapis = require("lapis")

local config = require("lapis.config")

local db = require("lapis.db")

config("", {
  postgres = {
    host = "localhost",
    user = "whatever",
    password = "whatever",
    database = "whatever"
  }
})

local res = db.query("select * from cool_db")
print(res)
```

I get error:
```
[user@coding lapis]$ luajit-resty test_db_postgres.lua 
luajit-resty: You have to configure either postgres or mysql
stack traceback:
        [builtin#19]: at 0x00449a40
        [C]: in function 'require'
        test_db_postgres.lua:5: in main chunk
        [C]: at 0x00404760

```

So instead of impelementing this mentioned code into app.lua and running with ```lapis server```, I want to test postgres functions in a separate code module. Help me! What am I doing wrong? 

Also, when should I use pgmoon? It is unclear from the documentation what is the difference of using/not using pgmoon.

Thanks!

**Comment by leafo** [comment]
Calling `require 'lapis.db'` will read the config to find out how to connect to the database. It looks like you're trying to specify the connection configuration afterwards, which won't work. I recommend following the guide and creating a config file instead of baking your config into a script: http://leafo.net/lapis/reference/configuration.html

In your config line you gave the environment as empty string. I'm not sure where you saw that syntax, lapis would never run in the empty string environment typically, so that config will never be picked up by anything.

The default environment is called `development`. If you're using the test helpers then the default environment becomes `test`. (There are ways to override the default as well)

**Comment by leafo** [comment]
Also lapis postgres support is coupled to pgmoon. You should always be using it (inside openresty or outside) when trying to communicate to postgres.

**Comment by VoittajaTomi** [comment]
Thank you very much for your answer Leafo! Im trying out pgmoon. I installed it globally and ```luarocks show pgmoon``` shows:

Installed in: 	/usr/local/openresty/luajit

Modules:
	pgmoon (/usr/local/openresty/luajit/share/lua/5.1/pgmoon/init.lua)
	pgmoon.arrays (/usr/local/openresty/luajit/share/lua/5.1/pgmoon/arrays.lua)
	pgmoon.crypto (/usr/local/openresty/luajit/share/lua/5.1/pgmoon/crypto.lua)
	pgmoon.socket (/usr/local/openresty/luajit/share/lua/5.1/pgmoon/socket.lua)


Unfortunaltely when I try to initialize it as in your example:

```lua
local pgmoon = require("pgmoon")
local pg = pgmoon.new({
  host = "127.0.0.1",
  port = "5432",
  database = "mydb",
  user = "postgres"
})

assert(pg:connect())

local res = assert(pg:query("select * from users where username = " ..
  pg:escape_literal("leafo")))
```

I get:
stdin:1: attempt to index global 'pgmoon' (a nil value)

What I am doing wrong?

**Comment by leafo** [comment]
you don't happen to have a file called pgmoon.lua in the same directory that you're trying in, do you?

The require statement should never return nil if it's loading the module's code

**Comment by VoittajaTomi** [comment]
I sure don't leafo! It is weird since requiring something 100% nonexistent results in an error. Doesnt work with superuser priviledges either. Any more ideas?

**Comment by leafo** [comment]
my only guess is that there's something strange about your luarocks install. Print out `package.path` and step through it to figure the full path of the pgmoon.lua or pgmoon/init.lua that is being loaded and open it up in your text editor to make sure it's not blank

**Comment by leafo** [comment]
Closing this since it seems to be outdated. 

If you're stilling having the issue feel free to re-open with any more information.

Thanks
