### ISSUE TITLE
need help: name of the page appended at the beginning of an image src 

### ISSUE THREAD

**Issue by takethispie** [leafo/lapis#352]
Hello,
I don't know why but when I have an Image on a page with GET params it changes the path of the image wich is in a variable, adding the name of the page at the beginning, I don't even understand where is my mistake so some help would be great:
```Lua
app:match("hebinfo","/hebinfo/:hebId", function(self)
    self.session.hebInfo.ID = self.params.hebId
    self.session.hebergement = HEBERGEMENT:find(self.session.hebInfo.ID)
    return{render = true}
end)
```
the part where the image is displayed in hebinfo.etlua, 
session.hebergement.PHOTOHEB contains the path to the image:
```html
<p><img src= <%= session.hebergement.PHOTOHEB %></p>
```
I get the error [500] GET /hebinfo/static/images/chalet3.jpeg
but it should be /static/images/chalet3.jpeg, the name of the page is added at the beginning with no reason

**Comment by leafo** [comment]
I don't recommend using the session to pass data down to the views. You can just assign the variable to self to be able to access it from your template.

As for why the value is wrong, there's not enough information here for me to tell, perhaps an issue somewhere further up in your code? Are you prefixing the url with `/` so it looks from the root directory?
