### ISSUE TITLE
Authentication tutorial/module

### ISSUE THREAD

**Issue by Immortalin** [leafo/lapis#353]
Lapis should have an authentication module a la [devise](https://github.com/plataformatec/devise).

**Comment by qaisjp** [comment]
the leafo/luarocks-site is a good enough example

**Comment by bdjnk** [comment]
Another good example is the [streak.club](https://github.com/leafo/streak.club) repository. The [helpers/app.moon](https://github.com/leafo/streak.club/blob/master/helpers/app.moon) file is particularly instructive. It shows a simplicity that somewhat obviates the need for a module.

**Comment by nonchip** [comment]
see also: https://github.com/nonchip/lazuli/tree/master/src/lazuli/modules/user_management. already modular, just `@enable "user_management"` (and mixin some views+migrations as needed).
