### ISSUE TITLE
How to turn off the error message?

### ISSUE THREAD

**Issue by yurevich1** [leafo/lapis#354]
What is the proper way to switch of error page with direct error?
I mean client html-page; error log at server have to work.

**Comment by leafo** [comment]
Is this what you're looking for? http://leafo.net/lapis/reference/actions.html#error-handler

**Comment by yurevich1** [comment]
No. As I understood, app.handle_404 is called only if page was not found. But what if I have an error for my PostrgreSQL request? This error message will be shown for any user. I want to hide this. Is it possible?

**Comment by leafo** [comment]
I linked to the section below `handle_404`, you should overwrite `handle_error` to change how unexpected errors are dealt with.

**Comment by yurevich1** [comment]
Yes. That's it!
