### ISSUE TITLE
resolve domain in db conf

### ISSUE THREAD

**Issue by jney** [leafo/lapis#355]
i had to change host, giving the ip to connect my db, or i got errors, the domain is not resolved.

```lua
config("production", {
  postgres = {
    database = "db",
    -- host     = "some.domain.on.rds.amazonaws.com:5432",
    host     = "1.2.3.4:5432",
    password = "lorem",
    user     = "admin"
  }
})
```

by the way i didn't not if i should post the issue there on in  `pgmoon` project

**Comment by starius** [comment]
Try setting the IP of DNS server in nginx.conf directive `resolver`, as shown here: http://leafo.net/lapis/reference/utilities.html#making-http-requests

**Comment by jney** [comment]
@starius same problem there

**Comment by leafo** [comment]
does `some.domain.on.rds.amazonaws.com` resolve on your computer? Or is that an internal address? The `8.8.8.8` resolver only works with publicly available DNS. You might need to add the IP of the resolver used on the machine running in AWS. (Check `/etc/resolve.conf` maybe? Not familiar with how it's set up on aws)

**Comment by leafo** [comment]
Also the port is a separate field, not part of the host.

```lua
postgres = {
  host = "blah.com",
  port = "2000"
}

```

**Comment by jney** [comment]
@leafo the documentation tells : 

```
If a non-default port is required it can be appended to the host with colon syntax: my_host:1234 (Otherwise 5432, the PostgreSQL default, is used).
```
anyway, both declarations work for me.

i realized i was not explicit enough about my environment. the current app is running in a docker container.

**Comment by zunware** [comment]
I am having the same problem. Im trying to use Heroku Postgres
I cannot resolve the host address for the postgress. My `config.lua` looks like this:

```
local config = require("lapis.config")


return config("heroku", {
	port = os.getenv("PORT"),
	postgres = {
		host = "xxx-xx-xx-xx-xxx.compute-1.amazonaws.com",
		port = "5432",
		user = "xxxxxxxxx",
		password = "xxxxxxxxx",
		database = "xxxxxxxxxxxx",
	},
	postgresql_url = os.getenv("DATABASE_URL"),
})

```

and my `nginx.conf`:

```
worker_processes ${{NUM_WORKERS}};
error_log stderr notice;
daemon off;
env LAPIS_ENVIRONMENT;

events {
  worker_connections 1024;
}

http {
  include mime.types;

  upstream database {
      postgres_server ${{pg POSTGRESQL_URL}};
  }

  server {
    
    listen ${{PORT}};
    lua_code_cache off;

    location / {
      default_type text/html;
      content_by_lua_file "web.lua";
    }
location /static/ {
      alias static/;
    }

    location /favicon.ico {
      alias static/favicon.ico;
    }

location = /query {
      internal;
      postgres_pass database;
      postgres_query $echo_request_body;
    }
}
}
```

Please help!!!

**Comment by starius** [comment]
Does `host = "<IP-address>"` work?

**Comment by jney** [comment]
for me it does, but what if multiple ips are associated to a domain name ?

**Comment by leafo** [comment]
the internal query location and upstream is no longer necessary with `pgmoon` btw:

```
  upstream database {
      postgres_server ${{pg POSTGRESQL_URL}};
  }

location = /query {
      internal;
      postgres_pass database;
      postgres_query $echo_request_body;
    }
}
```

You should use `os.getenv` to read the environment variable in your lapis config file

**Comment by zunware** [comment]
I solved my problem by adding the correct `resolver`! Thanks leafo. 

I had some struggle finding the right `resolver` for my heroku instance. I finally found the correct one by doing this in case anyone else is struggling:

`heroku run shell`
then inside heroku:
`cat /etc/resolv.conf` then used that in my config file.
