### ISSUE TITLE
for some reason @session won't "commit"

### ISSUE THREAD

**Issue by qaisjp** [leafo/lapis#361]
see my gist https://gist.github.com/qaisjp/9c3c9c6a6e6a7e2c3236

in app.moon: when `@session.user_id = nil` is executed, `to_json @session` has the correct change but this doesn't actually get "committed"

in auth.moon: `@session.user_id = nil` successfully logs me out

I have no idea what is going on here

**Comment by leafo** [comment]
The system can't currently identify settings things to `nil` as a change since the session is lazily loaded via metatable and setting a `nil` value is the same as just the value never being there.

This is how I've been doing logging out: https://github.com/leafo/luarocks-site/blob/master/applications/user.moon#L110

**Comment by qaisjp** [comment]
interesting, that doesn't explain why logging out works fine (setting it to nil in one place) and somewhere else setting it to another value doesn't persist the change to the next request

**Comment by qaisjp** [comment]
Hmmm, for this code:

```
	[become: "/become/:username"]: capture_errors {
		on_error: => @html -> p @errors[1]

		=>
			@session.user_id = false
			redirect_to: @urL_for "home"
	}
```

I get

```
Error

/usr/local/share/lua/5.1/lapis/application.lua:659: ./applications/admin.lua:79: attempt to call method 'urL_for' (a nil value)
stack traceback:
	./applications/admin.lua: in function <./applications/admin.lua:76>
Traceback

stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/lapis/application.lua:659: in function 'handler'
	/usr/local/share/lua/5.1/lapis/application.lua:393: in function 'resolve'
	/usr/local/share/lua/5.1/lapis/application.lua:402: in function </usr/local/share/lua/5.1/lapis/application.lua:400>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/lapis/application.lua:400: in function 'dispatch'
	/usr/local/share/lua/5.1/lapis/nginx.lua:205: in function 'serve'
	content_by_lua(nginx.conf.compiled:42):1: in function <content_by_lua(nginx.conf.compiled:42):1>
```

**Comment by leafo** [comment]
hmm, looks like I patched sessions a long time ago, here's the discussion: #32

The different application shouldn't' matter, how are you using both of them in your config? Are you trying to run both at the same time independently?

**Comment by qaisjp** [comment]
I haven't read that discussion yet, but I found something that might be helpful.

I was just changing some settings and I came across cookies. I got curious and started looking around through all my cookies. I found that my WIP site had multiple cookies, and after playing around (clearing the cookies for the site first) I managed to reproduce it. I got this:

![image](https://cloud.githubusercontent.com/assets/923242/12171432/cd71af7e-b541-11e5-83b5-140c3345ee30.png)

Whilst on the `/admin/users` page I POST to `/admin/become`. That creates the cookie on `/admin` to "change" the user. Anywhere I else on the website I can login/out and it will create the cookie on the root level `/`.

Deleting the first cookie allows me to only access my admin panel with whoever I was trying to become (I was trying to become another admin).

This seems to be what is causing my problem.

**Comment by qaisjp** [comment]
Looking over my last comment, I noticed that "accessible to script" was yes.

It turns out that my cookie_attributes was interfering with things.

**Comment by leafo** [comment]
Also keep in mind if you have subdomains you must set the correct correct domain cookie attribute to ensure the same cookie is used across the subdomain

**Comment by leafo** [comment]
What do you mean set it as a table?

This is how I'll typically set cookie attributes:

```moon
  cookie_attributes: =>
    expires = date(true)\adddays(365)\fmt "${http}"
    attr = "Expires=#{expires}; Path=/; Domain=.#{config.host}; HttpOnly"
    attr ..= "; Secure" if config.force_https
    attr

```

**Comment by qaisjp** [comment]
"set it as a table":

something like:

```moon
attr.Expires = expires
attr.Path = "/"
attr.Domain = config.host
attr.HttpOnly = ""
attr.Secure = "" if config.force_https
```
