### ISSUE TITLE
support Model\include_in on a single instance

### ISSUE THREAD

**Issue by qaisjp** [leafo/lapis#363]
This is unnecessary since we have model relations but I'm reporting this issue because I wasted a lot of time trying to figure out why this code wouldn't work:

```moonscript
assert_error Users\include_in @ban, "banned_user", as: "banned_user"
```

*wouldn't work* = silently not update the `banned_user` key for `@ban`

Naturally, `...Users\include_in {@ban}...` works perfectly fine. Perhaps include_in should check if the supplied table is actually a class instance or a table of instances. If it's an instance, do what is expected.

You could also just error out instead of letting it work on the single instance, which would remind developers to use the relations feature (which I am moving to now).

Side note/question: I don't think you don't need to use assert_error here.

Merry Christmas :)

**Comment by qaisjp** [comment]
Actually, I didn't do much thinking about this, but why is include_in a feature when relations could be used?

**Comment by leafo** [comment]
yup, but with the next version there's a new method called `preload_relations` that does an include in for you by just passing the relations name

**Comment by leafo** [comment]
closing this unless there's an issue you're having
