### ISSUE TITLE
Can't get `relations` to work.

### ISSUE THREAD

**Issue by qaisjp** [leafo/lapis#365]
```moonscript
content: =>
		banned_user = @ban\get_banned_user!
		h2 "Ban on " .. to_json banned_user

		Users\include_in {@ban}, "banned_user", as: "banned_user"
		h2 "Ban on " .. to_json @ban.banned_user
```
So the first header shows only the user ID on the user (just a plain integer), whereas the second header shows the full row information (a dictionary array). They should both contain the same information.

In the bans model, this is the `relations` table:
```moonscript
    -- Relations
    @relations: {
    	{"banned_user", has_one: "Users", key: "id"}
    	{"banner", has_one: "Users", key: "id"}
    }
```

Really sorry for using the issue tracker as a support forum, but I'd love to know where I'm going wrong!

Thanks, and Happy *Boxing Day*!

**Comment by leafo** [comment]
Can you show me what your schema looks like. Also `key: "id"` is most likely the problem, the key is supposed to be the foreign key column on the other model. Did you mean to use a belongs_to relation?

Also the two relations you wrote would load the same exact thing, so I don't think you intended that

**Comment by leafo** [comment]
Open again if you're still having issue.

**Comment by qaisjp** [comment]
Sorry for the late reply. 

Yes, belongs_to seems to be what I need. It looks like (for me), `get_??` returns a number (which is just the id of the user)
