### ISSUE TITLE
do ... end helper in etlua

### ISSUE THREAD

**Issue by Romaboy** [leafo/lapis#366]
Is it possible to make template helper like in erb?
<%= form_tag do %>
  Form contents
<% end %>

**Comment by leafo** [comment]
there is no equivalent in etlua at the moment. Just so I understand what you're trying to do, you'd like to capture a chunk of template to string so you can pass that as an argument to a function?

**Comment by Romaboy** [comment]
Not exactly, in that case "form content" would be str, form_tag would return env, so I'll try to modify etlua by adding new symbol, let it be <℅~, and it will do 1) exec function in first expression and 2) paste result of etlua.render(str, env)

**Comment by Romaboy** [comment]
I forget, that form_for, form_tag are wrappers and will return <form ...> + etlua.render ... + </form>

**Comment by Romaboy** [comment]
Form + etlua + /form, github striped tags in previous

**Comment by Romaboy** [comment]
Done! https://github.com/Romaboy/lairs/blob/master/lairs_moon/etl.moon
So my helpers returns html before block, after block and then plenty of vars
`<% function form(x) return "<form *attributes*>", "*csrf_token*</form>", x, 12 end %>`
And maximum rails similarity when calling them:
`<%~ form(42) do |x, y| %>
	<%- x %>
	<%- y %>
<%~ end %>`
