### ISSUE TITLE
Question on contribution guidelines...

### ISSUE THREAD

**Issue by soccermitchy** [leafo/lapis#368]
I'd like to rewrite the console command for Lapis to add more features, ie. per-app commands and better descriptions the commands. Only problem is that I'm not a big fan of Moonscript (just feels 'weird' to write) so I'd probably write everything for it in Lua. If I do it and make a PR for it, how likely is it to be accepted?

**Comment by leafo** [comment]
Lapis will continue to be written in MoonScript, I have no intention of merging any Lua code unless it's for Lua specific testing. You should discuss the changes you want to make as well to make sure we all agree.

**Comment by leafo** [comment]
Just to answer your question a little more directly, if someone were to submit a valuable patch in Lua I would rewrite it to MoonScript. But that's going to add delay in the functionality being merged, so I'd prefer if the original author just wrote it in MoonScript.

**Comment by leafo** [comment]
Closing, reopen if you have any more questions
