### ISSUE TITLE
OSX cannot install version 1.4

### ISSUE THREAD

**Issue by jessegreathouse** [leafo/lapis#370]
For some reason I cannot install version 1.4 of lapis on OSX on version 2.2.2 of luarocks

    A-JGREATHOUSE:luarocks-2.2.2 jgreathouse$ luarocks install lapis 1.4.0-1

    Error: No results matching query were found.
    A-JGREATHOUSE:luarocks-2.2.2 jgreathouse$ luarocks

    LuaRocks 2.2.2, a module deployment system for Lua

When I install it without the version tag I get an older version:

    A-JGREATHOUSE:luarocks-2.2.2 jgreathouse$ luarocks install lapis
    Installing https://luarocks.org/lapis-1.0.2-1.src.rock...
    Using https://luarocks.org/lapis-1.0.2-1.src.rock... switching to 'build' mode
    Updating manifest for /usr/local/lib/luarocks/rocks-5.2
    lapis 1.0.2-1 is now built and installed in /usr/local (license: MIT)

Am I doing something wrong?

**Comment by leafo** [comment]
Lapis only works on lua 5.1, because of the openresty dependency. There are some incorrectly tagged rockspecs, #367 that will let you install older version of lapis on newer version of lua

**Comment by jessegreathouse** [comment]
I see, my OSX version was on lua 5.2. This makes sense. Thanks for the info.
