### ISSUE TITLE
POST request gets redirected to Index with error 302.

### ISSUE THREAD

**Issue by zunware** [leafo/lapis#372]
I am having problems with my POST, I keep on getting redirected with a 302 message to the index and my handler code never gets run. Please help!!!

http://stackoverflow.com/questions/34562578/lapis-post-gets-redirected-to-index

    app:post("/api/new", capture_errors(function(self)
        print("handling post <<<<<")
        return {redirect_to = self:url_for("index")}
    end))

**Comment by leafo** [comment]
are you sure the handler is not being run? Where are you looking for the print output?

**Comment by zunware** [comment]
I have been trying different things and still can't figure out why the POST is not being run. I am getting the logs from a Heroku instance with the command `heroku logs -t` .

I tought maybe my http authetification was messing things up, so I removed it, but I still dont get the POST to work.

**Comment by zunware** [comment]
I finally found the problem. It was failing to match the POST url. I hanged my `app:post("/api/new"...)` handler function to a `app:match("/api/new/*", ...)`  and now my handler is running correctly. Working with Lapis is beautiful! Thanks @leafo.
