### ISSUE TITLE
Model.find can be somewhat unreliable (psql)

### ISSUE THREAD

**Issue by karai17** [leafo/lapis#378]
```lua
local m = Model:extends("table")
local row = m:find(100) -- returns the row where id or the pk is 100
print(row.id) -- 100

local row = m:find { col1=val1, col2=val2 } -- if more than one result matches the criteria, the result that is returned is undefined/random
print(row.id) -- 100? 123? 99?
```

As the above code shows, find does not pull form the db in a reliable way when searching for a single row when the criteria could produce several. I would expect that find would grab the first row ordered by the table's pks ascending, but that seems to not be the case.

I've had to fallback on slightly uglier code to get reliable results:

```lua
local m = Model:extends("table")
local rows = m:select("where col1=? and col2=? order by id asc limit 1", val1, val2)
local row = rows[1]
```

**Comment by leafo** [comment]
posgres doesn't make any guarantees about the order returned. lapis should not add an order by clause because it will change the index requirments on the query.

btw a cleaner way to write it would be

```lua
local row = unpack(m:select("where col = ? order by id asc limit 1", 123))
```

**Comment by karai17** [comment]
Alright, thanks for the info.


---
Landon Manning
lmanning17@gmail.com
