### ISSUE TITLE
post() shorcut not working ?

### ISSUE THREAD

**Issue by coxnegative** [leafo/lapis#381]
I have a html form defined like this:

```
<form action="unsub" method="post">
```

In my Lapis app I am trying to process this POST with the following action
```
app:post("/unsub", function(self) ....
```
But I am getting this error
```
...cal/openresty/luajit/share/lua/5.1/lapis/application.lua:399: don't know how to respond to POST
```

Firefox inspector reveals that the call is indeed a POST request to the server
```
Request URL: http://localhost:8080/unsub
Request Method: POST
```

I have also tried putting `/unsub` in the action attribute, but I am getting the same error

Note that a `app:get()` in the same app is working just fine.

Any hint ?

Thanks,
Luis

**Comment by leafo** [comment]
is it possible something else is taking precedence and serving the action instead? If you comment out `:get` and leave `:post` does it make any difference?

**Comment by coxnegative** [comment]
Hi,

I have another action in my app

```
app:get("/:id", function(self)...
```

Commenting this action makes the post() request to work fine. My understanding was that actions are matched verbatim for a given HTTP verb, but it seems that actions are matched regardless of the verb. Is this so ? 

Thanks,
Luis

**Comment by leafo** [comment]
the routes are matched first, then the verbs. That route pattern is very generic and will match `/unsub` because of the higher precedence since it's declared first.

I agree the precedence issue is confusing, but haven't spent time coming up with a solution yet.

**Comment by coxnegative** [comment]
All set now. I have modified my first match

```
app:get("/view/:id", function(self)
```

to avoid the generic pattern I had before.

Thanks for your support. 
Luis
