### ISSUE TITLE
Not getting request headers

### ISSUE THREAD

**Issue by JamesSparks** [leafo/lapis#382]
I followed your example for retrieving headers in the docs, but I am not receiving any of my input headers. I do however receive a set of common headers, e.g.

{
    "host": "localhost:8080",
    "accept-language": "en-US,en;q=0.8",
    "cache-control": "no-cache",
    "connection": "keep-alive",
    "accept": "*/*",
    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36",
    "postman-token": "0f577c4a-a804-6be9-4257-691223fc7b30",
    "accept-encoding": "gzip, deflate, sdch"
  }

but any custom headers I send as a part of the request are not contained here. Am I missing a step?

**Comment by jessegreathouse** [comment]
The dreaded "underscores_in_headers" config strikes again!

http://nginx.org/en/docs/http/ngx_http_core_module.html#underscores_in_headers
