### ISSUE TITLE
Pass same self into before and GET/POST

### ISSUE THREAD

**Issue by karai17** [leafo/lapis#383]
For each route in my application, I have a `before`, `GET`, and `POST` function that passes in `self`. Each of these selves seemingly have the same data, but are different tables. If I modify the `self` in `before`, those modifications do not pass into `GET`. Because of this, I need to set local variables in my Lua file to pass data out of `before` and into whatever else.

Considering the data in each function is the same, would it not be good to pass the same table around? This could make `before` slightly more valuable to use as it can cut out a lot of duplicate code.

**Comment by karai17** [comment]
Disregard, I'm an idiot.

**Comment by leafo** [comment]
:+1:
