### ISSUE TITLE
Routing pattern matching overhaul

### ISSUE THREAD

**Issue by leafo** [leafo/lapis#384]
I want to add many more pattern options for the router. Just collecting ideas before I start writing code.

## The router today

`:param` - matches into a param named `param`, all characters except `/`
`*` - matches all characters to the end, stored in a param named `splat`

Splat has a couple issues, since it's greedy, the following route will never match anything: `/hello/*/world` since the splat would grab to the end of string, and `/world` would fail.

## Planned

- [x] characters after splat can match - `/hello/*/world/`
- [x] characters after variable can match - `/hello/:filename.zip`
- [x] literal routes take precedence over variable routes, take precedence over splat routes
- [x] character pattern classes to named paramaters - restict param to only digits, not sure on synax
- [x] optional parts of routes - `/hello(/world/:something)`
- [x] splat should be inserted when using `url_for` #358

### Considering

- naming the splat something else, having two splats - not entire sure how useful this is
- add a routing mode that lets you use regex

## Route ordering

Route ordering in somewhat broken. It currently gives precedence to what's define first. This doesn't work in MoonScript because there is no guaranteed ordering of members of a class. Having ambiguous routes is necessary

Also, in Lua mode you might get confused when the following declaration of routes doesn't do what you expect:

`/:username`
`/about` - impossible to match, the other route will take precedence

Especially if you have a larger file it can be hard to keep track of route outer. Maybe some sort of auto precedence algorithm can be used to order routes? 

Here's the proposed new implementation. Not perfect but an improvement.

Here's the precedence order from highest to lowest

* Literal routes - `/hello`
* Variable routes - `/some/:var`
* Splat routes - `/things/*`
* Splat & variable - `/group/:name/*`

Routes of the same precedence are checked in the order they are declared 

## Reference

* [rails routing](http://guides.rubyonrails.org/routing.html)
* [path to regexp](https://www.npmjs.com/package/path-to-regexp)

## Misc

Another approach would be to just use regex for routes, but this would be a breaking change. Additionally the nginx runtime provides a pcre binding, we would need to find a lua module that provides the same interface so tests can run outside of nginx

**Comment by kikito** [comment]
Hi! I have implemented a router in Lua in the past:

https://github.com/APItools/router.lua

In our case, the precedence between: `/:username` and `/about` was clear: static routes always where resolved first, and then the params. 

We didn't need to use * in any route so we never implemented that.

**Comment by leafo** [comment]
All done!
