### ISSUE TITLE
config in existing openresty server

### ISSUE THREAD

**Issue by coxnegative** [leafo/lapis#385]
I am trying to execute a Lapis app in a existing openresty server that has this ``lua_package_path``

```
lua_package_path '/usr/local/openresty/apps/?.lua;;';
```

Then, all my applications use a full package path ``require``. For example,

```
local foo = require "application.subsystem.module"
```

We do this to avoid a huge ``lua_package_path``, that is difficult to maintain.

So, our lapis app is under the directory ``/usr/local/openresty/apps/unsub`` and I have this snippet in nginx.conf

```
        location / {
		lua_code_cache off;
                default_type text/html;
                content_by_lua '
                        require("lapis").serve("unsub.app")
                ';
        }
```

Our config file contains

```
local config = require("lapis.config")


config("production", {
  mysql = {
    host = "[redacted]",
    user = "[redacted]",
    password = "[redacted]",
    database = "test"
  }
})
```

and our ``app.lua``contains the usual stuff

```
local lapis = require("lapis")
local app = lapis.Application()
```

However, I am getting a strange error that I am not able to solve

```
2016/01/19 18:28:57 [error] 30834#0: *314 lua entry thread aborted: runtime error: You have to configure either postgres or mysql
stack traceback:
coroutine 0:
	[C]: in function 'require'
	/usr/local/openresty/luajit/share/lua/5.1/lapis/init.lua:15: in function 'serve'
	content_by_lua:2: in function <content_by_lua:1>
```

Not sure if this is related to our ``lua_package_path`` or it is some misunderstanding about how Lapis use the configuration of an application.

**Comment by leafo** [comment]
That typically means that the "config" module can't be found in your package path.

**Comment by leafo** [comment]
It's a shortcoming of lapis right now, but it's hardcoded to search for `config`, hoping it would find one in the working directory of nginx. Since your app is located `apps/unsub` it's not finding `apps/unsub/config.lua`. 

Three solutions are:
* move `config.lua` up to the apps directory
* change the package.path to point to the `unsub` directory, you would also need to update any require calls if they reference `unsub` in them
* include both the directories in the lua_path

I don't think any of these are ideal, I'd prefer to have the config module be parameterized

**Comment by coxnegative** [comment]
I have tried the 3rd approach, adding both paths to ``lua_package_path``and changing all the ``require`` accordingly, but still getting the same error.

Maybe it is a config problem. How does lapis choose the configuration name to use when deployed in an existing openresty installation ? My config has:

```
local config = require("lapis.config")


config("production", {
  mysql = {
    host = "[redacted]",
    user = "[redacted]",
    password = "[redacted]",
    database = "test"
  }
})
```

Maybe Lapis is looking for something different than ``production `` ?

Thanks.

**Comment by nonchip** [comment]
another idea: do something like this:

                content_by_lua '
                        package.loaded["config"]=require("unsub.config")
                        require("lapis").serve("unsub.app")
                ';

**Comment by coxnegative** [comment]
I just tried this and the ``config`` problem is solved. However, I run into a similar problem loading the ``views``.

I am to deploy it with ``lapis server`` with an openresty reverse proxy in front of it.

Thanks for all your suggestions. Lapis is a great fit for some of our internal applications.
