### ISSUE TITLE
 module 'lapis' not found:

### ISSUE THREAD

**Issue by dongzhecao** [leafo/lapis#386]
luarocks install lapis
lapis new --lua
lapis server
no error when starting server.
but,when I requesting localhost:8080,found error: 
stack traceback:
coroutine 0:
        [C]: in function 'require'
        content_by_lua(nginx.conf.compiled:22):2: in function <content_by_lua(nginx.conf.compiled:22):1>, client: 192.168.1.100, server: , request: "GET / HTTP/1.1", host: "192.168.1.113:8080"
2016/01/21 04:48:01 [error] 14451#0: *92 lua entry thread aborted: runtime error: content_by_lua(nginx.conf.compiled:22):2: module 'lapis' not found:
        no field package.preload['lapis']
        no file '/usr/share/lua/5.1/lapis/lapis.lua'
        no file '/usr/local/openresty/lualib/lapis.lua'
        no file '/usr/local/openresty/lualib/lapis/init.lua'
        no file './lapis.lua'
        no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta1/lapis.lua'
        no file '/usr/local/share/lua/5.1/lapis.lua'
        no file '/usr/local/share/lua/5.1/lapis/init.lua'
        no file '/usr/local/openresty/luajit/share/lua/5.1/lapis.lua'
        no file '/usr/local/openresty/luajit/share/lua/5.1/lapis/init.lua'
        no file '/usr/local/openresty/lualib/lapis.so'
        no file './lapis.so'
        no file '/usr/local/lib/lua/5.1/lapis.so'
        no file '/usr/local/openresty/luajit/lib/lua/5.1/lapis.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'

"lua -v" shows Lua 5.1.4 ("which lua" shows /usr/bin/lua)
my operating system: centos6.6
So how do I fix this? who can help me
thanks very much.

**Comment by dongzhecao** [comment]
luarocks show lapis
Modules:
        lapis (/usr/share/lua/5.1/lapis/init.lua)
        lapis.application (/usr/share/lua/5.1/lapis/application.lua)
        lapis.cache (/usr/share/lua/5.1/lapis/cache.lua)
        lapis.cmd.actions (/usr/share/lua/5.1/lapis/cmd/actions.lua)
        lapis.cmd.leda (/usr/share/lua/5.1/lapis/cmd/leda.lua)
        lapis.cmd.nginx (/usr/share/lua/5.1/lapis/cmd/nginx.lua)
.....................
not found 5.2

**Comment by dongzhecao** [comment]
> print(package.path)
./?.lua;/usr/share/lua/5.1/?.lua;/usr/share/lua/5.1/?/init.lua;/usr/lib64/lua/5.1/?.lua;/usr/lib64/lua/5.1/?/init.lua
> print(package.cpath)
./?.so;/usr/lib64/lua/5.1/?.so;/usr/lib64/lua/5.1/loadall.so

**Comment by leafo** [comment]
what version of lua is luarocks built for? Just run `luarocks` and it's on the bottom on the configuration section.

**Comment by dongzhecao** [comment]
I have solve this problem,there was two luajit in my system;
so, This is not a lapis issue. This is an environment issue.
thanks!

**Comment by leafo** [comment]
great, glad you figured it out

**Comment by robertomarin** [comment]
It took me something like 30 minutes to figure out that `lapis` only works with `lua 5.1`. It would be nice if it was very clear on the website. :)

![lapis-install](https://cloud.githubusercontent.com/assets/451051/12718963/4c9db248-c8d9-11e5-99d4-38b6dc47f664.png)
