### ISSUE TITLE
Allow any CSRF token name when validating

### ISSUE THREAD

**Issue by Gskartwii** [leafo/lapis#391]
Currently, `require "lapis.csrf".assert_token` and `.validate_token` expect the CSRF token to be called `csrf_token` in the request parameters. This may not be desired if the developer wants to have multiple forms in their page, and wants to, say, have a prefix for each form's inputs' `name` attributes for clarity.

**Comment by leafo** [comment]
is it necessary to have more than on csrf token though? I can't see any additional security benefits by having a unique one per form

**Comment by Gskartwii** [comment]
If you're like me you like to make IDs the same as the element's name attribute. :-)

But yeah, it's not necessary, just a nice thing to have.

**Comment by leafo** [comment]
Alright, going to keep it as is then since adding multiple csrf tokens doesn't have any security benefits. Sharing one across all forms will work just as well should also simplify your code.
