### ISSUE TITLE
Param arrays do not work correctly

### ISSUE THREAD

**Issue by qaisjp** [leafo/lapis#395]
Say you have a bunch of checkboxes like:

```moon
input type: "checkbox", name: "myarray[]", value: "testvalue1"
input type: "checkbox", name: "myarray[]", value: "testvalue2"
input type: "checkbox", name: "myarray[]", value: "testvalue3"
```

Note that between `[` and `]` there "is an empty string": `""`. This creates an array like:
```moon
@params.myarray = {
    [""]: "testvalue3"
}
```

However, with this code:
```moon
input type: "checkbox", name: "myarray[1]", value: "testvalue1"
input type: "checkbox", name: "myarray[2]", value: "testvalue2"
input type: "checkbox", name: "myarray[3]", value: "testvalue3"
```

You get this:
```moon
@params.myarray = {
    ["1"]: "testvalue1"
    ["2"]: "testvalue2"
    ["3"]: "testvalue3"
}
```

The first lapis html builder snippet should output the same as the second snippet, except with the keys being numbers (and not strings).

Where is the code for this?

**Comment by leafo** [comment]
There are a handful of issues for this:

#346 #294 #198

code lives here: https://github.com/leafo/lapis/blob/master/lapis/nginx.moon#L76

**Comment by qaisjp** [comment]
Ah, sorry for the duplicate issue submission!

**Comment by Guard13007** [comment]
So looking over the various issues related to this, I am a little confused, can someone explain how this is supposed to work?

**Comment by qaisjp** [comment]
[Hopefully this helps](https://stackoverflow.com/questions/3314567/how-to-get-form-input-array-into-php-array)

**Comment by Guard13007** [comment]
@qaisjp Are you certain it is intended to function that way? And that it is working that way currently? I'll try when I get the chance, but I'd prefer to know for certain as I've been way too frustrated by development recently.

**Comment by qaisjp** [comment]
Feel free to Google "form arrays" for yourself. Whether or not this
functions correctly can be observed by testing or reading through to the
other links (this issue was closed due to it being a duplicate).

**Comment by videni** [comment]
seem this problem not resolved in the latest lapis ,
the following request should be the same, but the key received in Lua is different. 
```
url -XPOST  http://localhost:8001/consumers/2c4db6a3-1c54-4fb9-bc
b5-9f719d6de495/routes -d 'routes[0]=2e729009-932d-4a83-83ce-7b31a17d6c65&routes[1]=816a9
c7e-b341-454f-b30c-69851b3f15c9'
```
result in two keys
```
{
  [ [=[routes[0]]=] ] = "2e729009-932d-4a83-83ce-7b31a17d6c65",
  [ [=[routes[1]]=] ] = "816a9c7e-b341-454f-b30c-69851b3f15c9"
}
```
```
url -XPOST  http://localhost:8001/consumers/2c4db6a3-1c54-4fb9-bc
b5-9f719d6de495/routes -d 'routes[]=2e729009-932d-4a83-83ce-7b31a17d6c65&routes[]=816a9
c7e-b341-454f-b30c-69851b3f15c9'
```
only one key
```
 {
  [ [=[routes[]]=] ] = {
    "2e729009-932d-4a83-83ce-7b31a17d6c65",
    "816a9c7e-b341-454f-b30c-69851b3f15c9"
  }
}
```

**Comment by videni** [comment]
@qaisjp, how do you solve this problem?
