### ISSUE TITLE
Can't setup heroku postgres

### ISSUE THREAD

**Issue by Ranguna** [leafo/lapis#396]
In the last couple of days, I've been trying to setup lapis on heroku with heroku's addon Postgres but I am unable to do so, the site crashes whenever I access it giving 500 Internal server error with the following line in heroku logs:
`[error] 21#0: *3 lua entry thread aborted: runtime error: You have to configure either postgres or mysql`
But I belive everything is properly configured, here's my nginx.conf:

```
worker_processes ${{NUM_WORKERS}};
error_log stderr notice;
daemon off;
pid logs/nginx.pid;

events {
  worker_connections 1024;
}

http {
  include mime.types;
  server {

    listen ${{PORT}};
    lua_code_cache ${{CODE_CACHE}};

    location / {
      default_type text/html;
      content_by_lua '
        require("lapis").serve("app")
      ';
    }

    location = /query {
      internal;
      postgres_pass database;
      postgres_query $echo_request_body;
    }
  }
  upstream database {
   postgres_server ${{pg POSTGRES_URL}};
  }
}
```

And here's my config.lua:

``` lua
local config = require("lapis.config").config
return config("heroku", {
    port = os.getenv("PORT"),
    postgres_url = os.getenv("DATABASE_URL"),
    code_caCHE = os.getenv("CODE_CACHE")
})
```

Heroku injects `DATABASE_URL" into the enviroment, it contains the postgres url and it follows the following format:
`postgres://user:password@host:port/database`
My app.lua:

``` lua
local lapis = require("lapis")
local app = lapis.Application()
local db = require('lapis.db')

app:get("/", function()
  return "Welcome to Lapis " .. require("lapis.version")
end)
app:get("/index", function()
    return "You are inside index."
end)
app:get("/db",function()
    return tostring(db)
end)

return app
```

Whenever I try to access the app, it crashes and I don't know why.

Can anyone help me ?
Thanks

**Comment by Ranguna** [comment]
I've changed my config.lua by reading throught #355 :
``` lua
local config = require("lapis.config").config
local _HdbURL = os.getenv("DATABASE_URL")
return config("heroku", {
	port = os.getenv("PORT"),
	postgres_url = os.getenv("DATABASE_URL"),
	postgres = {
		host = _HdbURL:match('@(.-):'),
		port = _HdbURL:match(_HdbURL:match('@(.-):'):sub(-4) .. ':(%d-)/'),
		user = _HdbURL:match('://(.-):'),
		password = _HdbURL:match(_HdbURL:match('://(.-):') .. ':(.-)@'),
		database = _HdbURL:match(_HdbURL:match(_HdbURL:match('@(.-):'):sub(-4) .. ':(%d-)/') .. '/(.+)'),
	},
	code_cache = os.getenv("CODE_CACHE"),
})
```
The local `_HdbURL` captures the enviromental variable containing the DB address and it's split it into parts using the match() string function. I've debugged everything so all the match() patterns are correct. However, my problem is that lua reads `_HdbURL` as a nil value and I've debugged it too, it contains the correct address, maybe lapis sets it to nil somehow ?
heroku logs :
```4 [error] 21#0: *3 lua entry thread aborted: runtime error: /app/packages/share/lua/5.1/lapis/config.lua:133: ./config.lua:7: attempt to index local '_HdbURL' (a nil value)```

**Comment by Ranguna** [comment]
Partialy fixed by inputing the data manualy, here's how:
Type `heroku run bash`, once the console loades run `cat /etc/resolv.conf` and copy the nameserver IP and set the `host` index of the postgres table in your config.lua to that.
Next, go to the settings tab of your heroku app and copy the `DATABASE_URL` string, it should be something like this:
`postgres://user:pass@host:port/database`
set the user index to user, password to pass, port to port and database to database, everything should be in string format.
Push everything to heroku and run your app, everything should be working now.

Never the less, the problem still precists, what I want is to be able to get access to the enviromental variable `DATABASE_URL` to set everything dynamicly inside the config.lua file but for some reason, lua is identifying the variable `_HdbURL` as nil despite the fact that I've set it to the `DATABASE_URL` env var.

**Comment by leafo** [comment]
Your nginx config must specify which evironment variables will be made available to worker processes: http://nginx.org/en/docs/ngx_core_module.html#env

You can add

```
env DATABASE_URL;
```

to your nginx config.


Sorry for the confusion about how you initially tried. That was for lapis' older method of postgres integration which has since been removed. Were you working from this? https://github.com/leafo/heroku-lapis-example I can update it

**Comment by Ranguna** [comment]
Adding the enviroment variable to the nginx conf fix it, everything works now.

I was working with that and with a lot of other stuff, the reason for that is that I couldn't find proper documentation on how to setup heroku's postgres with lapis and nginx. Maybe you could write some docs for that ?
