### ISSUE TITLE
Lapis community?

### ISSUE THREAD

**Issue by Guard13007** [leafo/lapis#398]
I thought there was already an issue for this, but I can't seem to find it.

I think there was some debate on what kind of a forum there should be, and while I'm sure that's still something to be worked out, a Discord server could be set up pretty quickly. Have you considered setting one up?

Edit: The issue that I was thinking of was on the MoonScript repo: [#238](https://github.com/leafo/moonscript/issues/238)

**Comment by leafo** [comment]
I've tried discord but it's annoying keeping another thing open. For chat I recommend the #moonscript channel on freenode.

**Comment by CatLover91** [comment]
While I am a big fan of IRC, I noticed that the channel is really low traffic. 
![image](https://user-images.githubusercontent.com/7215827/27496957-3456ee56-5826-11e7-84d0-17b2c9a940cf.png)
Both Lapis and Moonscript would benefit from driving more traffic towards the channel, but it is not mentioned on Lapis's home page (even though the homepage still references moonrocks). 

Personally, I would appreciate greater focus on the IRC channel as a resource because it is my opinion that most users are unaware that it is the only community resource available.

**Comment by karai17** [comment]
The MoonScript and Lapis communities are virtually non-existant and basically only exist in GitHub's issue tracker, which is obviously not great. The `#moonscript` IRC channel is largely dead, even @leafo doesn't really frequent it much these days. I'd definitely like to see (and be willing to help with) more drive to build a solid community around these great technologies. I am a really huge fan of Lapis and would like to evangelize it more but I have no place to direct people other than the API documentation.

If you want to set up an official Discord server for MoonScript and Lapis, I think that could be useful. I'd help moderate it if you'd like, too. Also more community promotion would be grand as well, having links to the official IRC/Discord/etc on the front pages of the respective project websites and GitHub repo READMEs might help with building a community around these projects. I know that I find it very difficult to find people to talk to about Lapis where I end up resorting to just emailing @leafo for help, which I am sure is only a little annoying for him.

One pro for Discord over IRC is that a Discord server allows for many channels. Setting up a `leafo` server and then having `#general`, `#off-topic`, `#moonscript`, and `#lapis` channels could help keep discussion relatively organized, similar to forums. Throw in `#itch.io` and `#lua` channels too.

While I agree with @leafo that having many things open can be annoying, Discord's web interface is really good. A pinned tab has been pretty fine and out of the way for me.

**Comment by karai17** [comment]
Update: We have an official Discord now! https://discord.gg/Y75ZXrD

**Comment by leafo** [comment]
I added it to the readme and added it to lapis-site (which will get deployed sometime in the near future)
