### ISSUE TITLE
Can not install lapis on Ubuntu 14

### ISSUE THREAD

**Issue by ngocdo1987** [leafo/lapis#402]
I installed Lua 5.2.4 and Luarocks 2.3 on Ubuntu 14.04, I tried to install Lapis many times but not successfully

**luarocks install http://rocks.moonscript.org/manifests/leafo/lapis-dev-1.rockspec**

Or I download source of Lapis and command in source folder

**luarocks make**

But always receive this error

**Missing dependencies for lapis:
lua ~> 5.1
Error: Could not satisfy dependency: lua ~> 5.1**

If I use

**luarocks install lapis**

then

**Error: No results matching query were found.**

Can you help me, leafo?

**Comment by soccermitchy** [comment]
You need Lua 5.1 to install Lapis, not 5.2.

**Comment by raingloom** [comment]
I have the same issue on Arch. I installed both OpenResty (`openresty`) and Luarocks (`openresty_luarocks`) from the AUR. `luajit -e "print(_VERSION)"` reports Lua 5.1. So why isn't it installing then?

**Comment by leafo** [comment]
I don't know what `openresty_luarocks` is. If you're on archlinux then install `luarocks5.1` and use the command `luarocks-5.1` on you shell to install packages: 

```
luarocks-5.1 install lapis
```

**Comment by raingloom** [comment]
Turns out the PKGBUILD was outdated. I have uploaded the fixed version and it now installs without problems.

@ngocdo1987 how are you installing Luarocks? The build script I used originally ran `make` and then `make install` instead of `make build` and `make install`.

**Comment by leafo** [comment]
Closing this since it appears to be a Lua mismatch issue. Feel free to open again if there are any updates.
