### ISSUE TITLE
no pg_hba.conf entry 

### ISSUE THREAD

**Issue by exqt** [leafo/lapis#404]
I deployed a Lapis app on Heroku using https://github.com/leafo/heroku-lapis-example
But it didn't work.. I realized that the repo is using old verison.
So i edited some files and now the app gives me an error.
It looks like this

` /app/packages/share/lua/5.1/lapis/db/postgres.lua:46: FATAL: no pg_hba.conf entry for host "54.234.4.133", user "<user>", database "<db>", SSL off`

Any suggestions would be appreciated.

**Comment by leafo** [comment]
You're using the environment variables to extract credentials for the database correct? Is it password based connection? It sounds like the server is not configured to allow connections from where you're trying to connect from

**Comment by leafo** [comment]
closing this since it doesn't appear to be a lapis issue
