### ISSUE TITLE
Lua 5.2 & 5.3?

### ISSUE THREAD

**Issue by bigtunacan** [leafo/lapis#406]
Just started checking out Lapis and it seems really cool.  I'm new to the whole Lua eco system so I wasn't familiar with the rocks and such.  Started out with Lua 5.2, couldn't get Lapis working, eventually downgraded to 5.1 and got it working after some help.

I'm curious though why Lapis does not work with Lua 5.2 & 5.3.  Is this planned?  Are there technical challenges?

Thanks.

**Comment by bdjnk** [comment]
Lapis relies on the Lua implementation in [OpenResty](http://openresty.org/), which is [LuaJIT](http://luajit.org/luajit.html), which [only supports Lua 5.1](http://lua-users.org/lists/lua-l/2012-01/threads.html#00784).

**Comment by CriztianiX** [comment]
LuaJIT supports some language and library extensions from Lua 5.2.

    goto and ::labels::.
    Hex escapes '\x3F' and '\*' escape in strings.
    load(string|reader [, chunkname [,mode [,env]]]).
    loadstring() is an alias for load().
    loadfile(filename [,mode [,env]]).
,,,,

http://luajit.org/extensions.html
