### ISSUE TITLE
Linux console

### ISSUE THREAD

**Issue by Romaboy** [leafo/lapis#407]
Hi, I wrote console script, maybe it will be usefull. Not lua, but moonscript. Features: ctrl+left/right arrow jumps on words, end and home buttons are working, there is a history of commands, all expressions write their result. Tested on archlinux, I think on windows or macos it will not work, but who cares.
Here is it! https://github.com/Romaboy/lairs/blob/904a38b8cf5853ec112d5cc282162f8baa17f663/console.moon

**Comment by qaisjp** [comment]
Buddy, this issue tracker is for issues about lapis only. Please close this.

**Comment by Romaboy** [comment]
And where is right place for lua/moonscript web dev tools? Yea, maybe openresty channel, next time will post there.
