### ISSUE TITLE
belongs_to relation with same key name doesn't set the key

### ISSUE THREAD

**Issue by qaisjp** [leafo/lapis#409]
```moon
   @relations: {
        {"receiver", belongs_to: "Users", key: "banned_user"}
        {"sender", belongs_to: "Users", key: "banner"}
    }
```

will work, but

```moon
   @relations: {
        {"banned_user", belongs_to: "Users", key: "banned_user"}
        {"banner", belongs_to: "Users", key: "banner"}
    }
```

won't.

`object\get_banner!` will be a number (the column), but `object\get_sender!` will be the correct object...

**Comment by qaisjp** [comment]
Maybe related to this? https://github.com/leafo/lapis/blob/master/lapis/db/model/relations.moon#L106

**Comment by leafo** [comment]
You can't have a relation name match the name of a column, since it's storing it's data as that field on the table.

I recommend suffixing all foreign key columns with `_id`.

I'm not sure it's worth removing this limitation.
