### ISSUE TITLE
layout for subapplications

### ISSUE THREAD

**Issue by nonchip** [leafo/lapis#411]
`@include`ing this falls back to parent layout:

```moonscript
class extends require"lapis".Application
  layout: false
  path: "/api"
  name: "api_"
  [index: "/"]: =>
    "…"
```

(returning `layout: false, "…"` works, but looks ugly if used in every action)

**Comment by qaisjp** [comment]
duplicate of #360

**Comment by nonchip** [comment]
true, sorry. closing.
