### ISSUE TITLE
schema.create_table causes runtime error

### ISSUE THREAD

**Issue by reisenmachtfreude** [leafo/lapis#415]
HI there,

I'm very glad that I recently found lapis. It's exactly what I need.
However, I would like to use the "schema.ceate_table" functionality so I copied your example code in my app.lua file. It looks like the following

```
local lapis = require("lapis")
local db = require("lapis.db")
local schema = require("lapis.db.schema")
local types = schema.types

local app = lapis.Application()

-- initialise database
schema.create_table("users", {
  {"id", types.serial},

  {"username", types.varchar},

  "PRIMARY KEY (id)"
})

-- Describe routes
app:get("/info", function()
  return "play with me..."
end)
return app  
```

The resulting error can be seen in the server console:

```
2016/03/15 19:30:30 [error] 17089#0: *1 lua entry thread aborted: runtime error: attempt to yield across C-call boundary
stack traceback:
coroutine 0:
	[C]: in function 'require'
	/usr/local/share/lua/5.1/lapis/init.lua:15: in function 'serve'
	content_by_lua(nginx.conf.compiled:22):2: in function <content_by_lua(nginx.conf.compiled:22):1>, client: 127.0.0.1, server: , request: "GET /info HTTP/1.1", host: "localhost:8080"
```

If I remove the schema.create_tables lines the code works.
Also the db connection seems to be configured correctly, because I'm able to run db.query commands without error.

Please help :)

**Comment by leafo** [comment]
Where did you have the `db.query`call that worked? Was it in the top scope or inside the callback for the action? You can try putting the `create_table` call in the route callback to see if it makes any difference.

BTW you can run your create table scripts from the command line with the lua5.1 or luajit runtime. I recommend putting things like that in a migration: http://leafo.net/lapis/reference/database.html#database-migrations

**Comment by reisenmachtfreude** [comment]
yes, you are right.

Inside a callback it works perfectly, sorry didn't see this in the manual.

`app:get("/init", function()
  schema.drop_table("users")
  schema.drop_table("events")

  -- initialise database
  schema.create_table("users", {
    {"id", types.serial},
    {"username", types.varchar},
    {"public_id", types.varchar},
    {"created_at", schema.types.time},
    {"updated_at", schema.types.time},
    "PRIMARY KEY (id)"
    })
  schema.create_table("events", {
    {"id", types.serial},
    {"user_id", types.serial},
      "PRIMARY KEY (id)"
  })
end)
`
