### ISSUE TITLE
Is there a way to execute timed events?

### ISSUE THREAD

**Issue by Guard13007** [leafo/lapis#418]
I have a table I wanted updated every half hour, is there a way to schedule something to happen at a certain time in the future? Or would I have to do something like set up a cron job to curl a specific URL every once in a while?

**Comment by leafo** [comment]
There's no built in way to do this. Openresty would have to provide something. You can kind of work around it with nginx timers, but it's not ideal.

In previous projects I've had success with cron jobs either running command line scripts, or triggering a URL that only listens to localhost.

**Comment by turbo** [comment]
It might be a good idea to mainline a job framework, this is pretty essential in a lot of web projects (see .NET and Hangfire, Ruby and Qless, Node and Agenda etc.).

Go's buffalo project is somewhat comparable to the lapis strategy, they also include a lightweight job system.

A pretty good candidate would be `lua-resty-qless`. One can even port `lua-resty-qless-web` to use lapis.

**Comment by leafo** [comment]
@turbo  anything that works with openresty should work with lapis. The only consideration to make is that you're releasing DB connections back into the pool after your job runs.

**Comment by turbo** [comment]
Yeah, I just meant it would be nice to have a clean/official API for that, kinda like the lapis db interface.
