### ISSUE TITLE
Is close_test_server still a thing?

### ISSUE THREAD

**Issue by vadi2** [leafo/lapis#424]
https://github.com/leafo/lapis/blob/master/docs/testing.md mentions using ``close_test_server``, but that doesn't seem to be an available function, and from the looks of it, ``use_test_server`` already sets it up on teardown anyway. Is manually using ``close_test_server`` any good?

**Comment by leafo** [comment]
I recommend using `use_test_server` instead of manually starting and stopping it with `start_test_server` and `close_test_server`. Those to functions will always exist. The documentation there needs to be updated.
