### ISSUE TITLE
changing the <title> tag with etlua templates

### ISSUE THREAD

**Issue by paperpunk** [leafo/lapis#427]
hello!
is it possible to change the `<title>` tag of the page generated with an etlua template? if yes, how?

thank you!

**Comment by leafo** [comment]
Hello,

You probably want to replace the default layout?

http://leafo.net/lapis/reference/lua_getting_started.html#creating-a-view/creating-a-layout

**Comment by leafo** [comment]
re-open if you're still having trouble

**Comment by paperpunk** [comment]
thank you! i don't know how i missed the very first example... :)
