### ISSUE TITLE
Cannot install with luarocks

### ISSUE THREAD

**Issue by maciejjankowski** [leafo/lapis#433]
Hello,
I am trying to install lapis, but I get:
````
No results matching query were found.
````

I am using the latest lua

**Comment by leafo** [comment]
lapis is for lua 5.1 at the moment, since it's coupled to openresty

**Comment by mylesbarros** [comment]
Specifically if you're new to lua & luarocks you'll want to try...
`luarockt-5.1 install lapis`
Be sure you have a Lua 5.1 install first, though.
