### ISSUE TITLE
mock_request and request do not seem to handle json "post" in a similar way

### ISSUE THREAD

**Issue by saucisson** [leafo/lapis#434]
`request` allows to pass a JSON string as `post`, that can be later decoded using `json_params`, but `mock_request` always tries to encode them with `encode_query_string`.

A simple fix seems to replace (in [lapis/spec/request.moon](https://github.com/leafo/lapis/blob/master/lapis/spec/request.moon)):
```lua
      get_body_data: -> opts.body or opts.post and encode_query_string(opts.post) or nil
```
with:
```lua
      get_body_data = function()
        opts.post = opts.post and  (headers ["Content-type"] ~= "application/json" and encode_query_string(opts.post)) or opts.post
        return opts.body or opts.post or nil
      end,
```
(sorry, i do not speak Moonscript)

Not really tested, it just works on my project to be able to test in both server and mock modes.

**Comment by leafo** [comment]
You can use the body param to send a json blob, the post param is used for constructing a form. Example in tests: https://github.com/leafo/lapis/blob/master/spec/request_spec.moon#L65
