### ISSUE TITLE
lapis run in win10 & lua5.1 get error

### ISSUE THREAD

**Issue by damody** [leafo/lapis#438]
Hello leafo:

I want to make a portable binary in windows like xampp,
but I get some problem.

I use https://github.com/LomoX-Offical/nginx-openresty-windows
1.9.15.1001 64bit version 

and use this Win64 OpenSSL v1.0.2g
http://slproweb.com/products/Win32OpenSSL.html
and this my lua
[lua.zip](https://github.com/leafo/lapis/files/243624/lua.zip)

and I set all environment  variable ok
run get fail result.
So, how could I figure out any method?

```
C:\Users\summy\Downloads\nginx>lapis server
Error: 27: attempt to index local 'out' (a nil value)
 * Run with --trace to see traceback
 * Report issues to https://github.com/leafo/lapis/issues
```

![screen](https://cloud.githubusercontent.com/assets/6639075/14936348/623676dc-0f1d-11e6-9d2d-39704910015d.png)

**Comment by nonchip** [comment]
maybe start by doing what's advised in the output: run with `--trace` so we can see what's going on.

**Comment by CriztianiX** [comment]
I wanted to help, but I can not understand how to download the files from this sites . Sorry.

**Comment by damody** [comment]
```
C:\Users\summy\Downloads\nginx\lapis_gwui>lapis server
Error: 27: attempt to index local 'out' (a nil value)
 * Run with --trace to see traceback
 * Report issues to https://github.com/leafo/lapis/issues

C:\Users\summy\Downloads\nginx\lapis_gwui>lapis server --trace
Error: c:\lua\\systree/share/lua/5.1/lapis\cmd\nginx.lua:127: attempt to index local 'out' (a nil value)
stack traceback:
        c:\lua\\systree/share/lua/5.1/lapis\cmd\nginx.lua:127: in function 'check_binary_is_openresty'
        c:\lua\\systree/share/lua/5.1/lapis\cmd\nginx.lua:116: in function <c:\lua\\systree/share/lua/5.1/lapis\cmd\nginx.lua:99>
        (tail call): ?
        c:\lua\\systree/share/lua/5.1/lapis\cmd\actions.lua:104: in function <c:\lua\\systree/share/lua/5.1/lapis\cmd\actions.lua:100>
        (tail call): ?
        [C]: in function 'xpcall'
        c:\lua\\systree/share/lua/5.1/lapis\cmd\actions.lua:323: in function 'execute'
        ...\\systree\lib\luarocks\rocks\lapis\1.5.0-2\bin\lapis:4: in main chunk
        [C]: ?
```

[luarocks-2.3.0-rc2.zip](https://github.com/leafo/lapis/files/248729/luarocks-2.3.0-rc2.zip)

[Openresty_For_Windows_1.9.15.1001_64Bit.zip](https://github.com/leafo/lapis/files/248728/Openresty_For_Windows_1.9.15.1001_64Bit.zip)

**Comment by CriztianiX** [comment]
As you see in nginx.lua, nginx binaries are being search in:
```lua
    nginx_search_paths = {
      "/usr/local/openresty/nginx/sbin/",
      "/usr/local/opt/openresty/bin/",
      "/usr/sbin/",
      ""
    }
```
So, i think that lapis is at the moment *nix dependent.
