### ISSUE TITLE
how to get/post plain text for ajax

### ISSUE THREAD

**Issue by damody** [leafo/lapis#440]
http://www.w3schools.com/jquery/jquery_ajax_get_post.asp
I want to make ajax like this example
I use etlua
but usually return 
`<!DOCTYPE HTML><html lang="en"><head><title>Lapis Page</title></head><body>MYDATA_TEXT</body></html>`
but I don't need `<!DOCTYPE HTML><html lang="en"><head><title>Lapis Page</title></head><body>`
and `</body></html>`
just get the `MYDATA_TEXT`

my etlua like this
```
<%
-- some thing compute
data = "MYDATA_TEXT"
%>
<%=data%>
```

**Comment by leafo** [comment]
You can set the content type to text/plain and disable the layout:

```lua
app:get(function()
  -- ...
  return { content_type = "text/plain", layout = false, render = true }
end)
```

**Comment by damody** [comment]
yes, but how to write it in moon script ?

**Comment by nonchip** [comment]
by returning exactly the same thing:

    class extends lapis.Application
      "/some/route": => content_type: "text/plain", layout: false, render: true

**Comment by damody** [comment]
"/msgzhtw": => content_type: "text/plain", layout: false, render: "msgzhtw"
it's work! thanks.
