### ISSUE TITLE
Arch Linux: lapis does not find openresty by default

### ISSUE THREAD

**Issue by Alloyed** [leafo/lapis#441]
The [OpenResty AUR](https://aur.archlinux.org/packages/openresty/) package installs itself using `./config --prefix=/opt/openresty`, so the correct full search path is
```
/opt/openresty/nginx/sbin/
```

**Comment by CriztianiX** [comment]
Can you make a symbolic link?
as root. you can try:
```bash
cd /usr/local ; sudo ln -sf /opt/openresty/ openresty
```

**Comment by Guard13007** [comment]
@CriztianiX I would think it would be better if Lapis knew that OpenResty could be installed there instead of having to tell everywhere to go make a symlink.

**Comment by CriztianiX** [comment]
Ok... the path should be add it in:

https://github.com/leafo/lapis/blob/master/lapis/cmd/nginx.moon#L16

**Comment by CriztianiX** [comment]
This PR contains the fix

https://github.com/leafo/lapis/pull/442

**Comment by leafo** [comment]
fixed now, thanks
