### ISSUE TITLE
adding charset to response header for json

### ISSUE THREAD

**Issue by romanesko** [leafo/lapis#446]
Laps rewrites any content-type header I set when it renders json
I need to add ';charset=utf-8' to content-type header

**Comment by CriztianiX** [comment]
You can try in your nginx.conf

```code
 location / {
      ...
       add_header 'Content-Type' 'charset=UTF-8';
     ...
}
```

**Comment by 8026787** [comment]
I've tried to do it in the first place, but lapis rewrites this header

**Comment by leafo** [comment]
You can pass the content type directly as a return parameter using the key `content_type`

http://leafo.net/lapis/reference/quick_reference.html#how-do-i-set-the-content-type

**Comment by 8026787** [comment]
Doesn't work for json:

`return { status = 200, text = 'test', content_type = 'application/json; charset=utf-8'}`

`< Content-Type: application/json; charset=utf-8`

`return { status = 200, json = {text = 'test'}, content_type = 'application/json; charset=utf-8'}`

`< Content-Type: application/json`

**Comment by CriztianiX** [comment]
@8026787 yes...

https://github.com/leafo/lapis/blob/master/lapis/request.moon#L45

@leafo  This line overrides the headers on json response. i will try to fix it as soon posible and send a PR

**Comment by leafo** [comment]
yeah, looks like a `or=` would work there
