### ISSUE TITLE
Is it possible to render content as is (without wrapping)?

### ISSUE THREAD

**Issue by 8026787** [leafo/lapis#447]
If I'd like to render just text as is. Without template wrapping? Is it possible?

something like:
`return { status = 20, content = '[]', content_type = 'tapplication/json; charset=utf-8'}`

I'd like to use LuaJSON instead of cjson, because it knows how to render empty arrays…

**Comment by 8026787** [comment]
Oh no… LuaJSON doesn't render empty arrays either (
So anyway I need to render it manualy

**Comment by leafo** [comment]
You should pass `layout: false` to turn off the layout.
