### ISSUE TITLE
file upload problem

### ISSUE THREAD

**Issue by 8026787** [leafo/lapis#449]
I have form
```
<form action="/upload" enctype="multipart/form-data" method="post">
    <input type="file" name="file">
    <input type="hidden" name="test" value="ok">
    <input type="submit" value="Send">
</form>
```

and lua script:
```
local lapis = require("lapis")
local app = lapis.Application()
local to_json = require("lapis.util").to_json;

app:post("/upload", function(self)
    print(to_json(self.params));
end)

return app
```

on file upload I get 

```
lps_1 | 2016/06/24 16:28:15 [warn] 22#0: *6 a client request body is buffered to a temporary file /opt/openresty/nginx/conf/client_body_temp/0000000017, client: 192.168.99.1, server: , request: "POST /upload HTTP/1.1", host: "192.168.99.100", referrer: "http://192.168.99.100/static/form.html"
lps_1 | 2016/06/24 16:28:15 [notice] 22#0: *6 [lua] upload.lua:9: handler(): {}, client: 192.168.99.1, server: , request: "POST /upload HTTP/1.1", host: "192.168.99.100", referrer: "http://192.168.99.100/static/form.html"
```

so the params are empty.

if I set `enctype="application/x-www-form-urlencoded"`:

```
lps_1 | 2016/06/24 16:33:52 [notice] 22#0: *8 [lua] upload.lua:9: handler(): {"file":"222806243_6998870255536173871.jpg","test":"ok"}, client: 192.168.99.1, server: , request: "POST /upload HTTP/1.1", host: "192.168.99.100", referrer: "http://192.168.99.100/static/form.html"
```

p.s. in fact there is no /opt/openresty/nginx/conf/client_body_temp/0000000017 file exists, the folder is empty

**Comment by leafo** [comment]
You should be using `multipart/form-data` for file uploads.  If you don't use multipart you'll just get the name of the file in params (that's all the browser sends). 

Also be aware that you might need to adjust nginx settings for max post size. The default is pretty small, if your image is greater than that then it will be dropped: http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size

That's probably why you didn't see anything in the params.

The warning message is not an issue, it's pretty much telling you the file was too large to sit in memory, so it will be buffered to disk. You can configure using these directives: http://nginx.org/en/docs/http/ngx_http_core_module.html#client_body_buffer_size

The file path is lists will be cleaned up immediately after the request finishes so it's unlikely you'll see the file on disk.

Relevant documentation: Did you see this part of the documentation? http://leafo.net/lapis/reference/utilities.html#file-uploads

**Comment by leafo** [comment]
Re-open if you're still having  trouble.

**Comment by romanesko** [comment]
I found the problem: it was because of `lua_need_request_body on;` directive in my `nginx.conf`
