### ISSUE TITLE
Can a migration be run while a server is still running?

### ISSUE THREAD

**Issue by Guard13007** [leafo/lapis#452]
I am setting up my website using Lapis, and setting it up to automatically update when I push to GitHub, which will include running migrations. I'd prefer to run migrations and then use `lapis build production` to continue running the server seamlessly.

Can it be done this way?

**Comment by CriztianiX** [comment]
Yes,, just...

```ua
lapis migrate production
lapis build production
```

**Comment by Guard13007** [comment]
Cool. Now, is there a potential danger in doing this? Say I change how the database works in the migration, and the site is still live, and something happens in an order where a user does something with the old page after migration was run, before the rebuild.

**Comment by Guard13007** [comment]
Say they change something successfully that breaks how it's supposed to work post-migration. Does Lapis have any kind of protection against a mistake like this, or do I just have to make sure I don't allow it to happen?
