### ISSUE TITLE
Can you put custom variables into nginx.conf from config.moon?

### ISSUE THREAD

**Issue by Guard13007** [leafo/lapis#453]
I was under the impression that you could add your own custom variables into nginx.conf this way:

```moonscript
config = require "lapis.config"

config "production", ->
  some_var "some value"
```

And in nginx.conf:

```
server {
  some_config_thing ${{SOME_VAR}};
}
```

But I realize I was wrong. Is there a way to do this? If not, consider this a feature request...or is there a better way to achieve the same thing? Essentially, I want to keep customized configurations outside of the files I will be updating automatically using git to pull changes.

**Comment by leafo** [comment]
That's the correct syntax, that should work. If you look at `nginx.conf.compiled` what do you see?

**Comment by Guard13007** [comment]
The custom variables in the compiled config are completely unmodified. In retrospect I might've forgotten to compile the moonscript first or I might've forgotten to import the variables. I'll double check these when I get the chance and report back.

**Comment by Guard13007** [comment]
I figured out what I was doing wrong, and it was a pretty dumb error. Essentially, something like this:

```moonscript
import var_name from "something" -- var_name is a string

config "production", ->
  var_name var_name
```

So the error was trying to call a string because I didn't think about how I was trying to use the same variable name as two different things essentially. Somehow I didn't read this out of the error I was getting either until an unrelated error made me go back and carefully look through everything again.

Anyhow, sorry for wasting your time.
