### ISSUE TITLE
[BUG] app.lua not found (moon)

### ISSUE THREAD

**Issue by handicraftsman** [leafo/lapis#456]
Hello. I just made clear installation of lapis'es moonscript skeleton. When i am launching it, it tries to run app.lua, not app.moon. Of course, in lua skeleton all is good. Can you fix it? (now i am just using script, which parses app.lua, and after runs "lapis server")

**Comment by Guard13007** [comment]
You have to compile the MoonScript to Lua.

**Comment by leafo** [comment]
Re-open if you've discovered what the issue is, otherwise it sounds like you didn't compile.

**Comment by handicraftsman** [comment]
Guide does not asks about compiling to lua. Can you fix it?

**Comment by Guard13007** [comment]
@handicraftsman I'm assuming you meant the reference manual, and it is right near the begining: http://leafo.net/lapis/reference/moon_getting_started.html

If you meant somewhere else, where are you talking about?
