### ISSUE TITLE
lapis/db/pagination.lua:163: attempt to call field 'parse_clause' (a nil value)

### ISSUE THREAD

**Issue by Guard13007** [leafo/lapis#460]
Within a request handler:

```moonscript
Paginator = Messages\paginated "ORDER BY timestamp ASC", per_page: 50
if page > Paginator\num_pages!
  return redirect_to: @url_for "all", page: Paginator\num_pages!
```

Leads to:

![screenshot_2016-07-26_11-51-05](https://cloud.githubusercontent.com/assets/15093567/17151234/cb95951a-5327-11e6-8962-15b9ca92560a.png)

**Comment by leafo** [comment]
are you using mysql?

**Comment by Guard13007** [comment]
Yes

**Comment by leafo** [comment]
The mysql query parser hasn't been written yet, so you'll have to write the queries manually :(

**Comment by Guard13007** [comment]
Hmm, I might take a look at it and see if I can figure it out then. I'm
pretty bad with SQL though.

Thanks!

**Comment by Guard13007** [comment]
Looking at that, I have no idea where I'd begin. I'm gonna close this issue though, as it really is the underlying issue that needs to be done.
