### ISSUE TITLE
Handling Requests Error from Example in Documentation: attempt to index field 'req' (a nil value)

### ISSUE THREAD

**Issue by bastiandebyl** [leafo/lapis#461]
From: http://leafo.net/lapis/reference/actions.html#handling-http-verbs
Code: 
```moonscript
lapis = require "lapis"
import respond_to from require "lapis.application"

class App extends lapis.Application
  [create_account: "/create-account"]: respond_to {
    GET: => render: true
    POST: =>
      do_something @params
      redirect_to: @url_for "index"
  }
```

Error message:
`/usr/local/share/lua/5.1/lapis/application.lua:352: attempt to index field 'req' (a nil value)`

Traceback:
```
stack traceback:
	/usr/local/share/lua/5.1/lapis/application.lua:352: in function 'thing'
	/usr/local/share/lua/5.1/lapis/request.lua:89: in function 'write'
	/usr/local/share/lua/5.1/lapis/application.lua:130: in function 'resolve'
	/usr/local/share/lua/5.1/lapis/application.lua:161: in function </usr/local/share/lua/5.1/lapis/application.lua:159>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/lapis/application.lua:159: in function 'dispatch'
	/usr/local/share/lua/5.1/lapis/nginx.lua:214: in function 'serve'
	content_by_lua(nginx.conf.compiled:22):2: in function <content_by_lua(nginx.conf.compiled:22):1>
```

Page is not rendered, simply returns error message although lapis server shows **GET** request with the following header:
`request: "GET /login HTTP/1.1"`

Lapis Version: 1.5.1
nginx version: openresty/1.9.15.1

**Comment by bastiandebyl** [comment]
This issue does not occur when using lapis server as lua insteas of moonscript.

**Comment by leafo** [comment]
I don't see any issues with that code. Are you sure you've pasted exactly what you're running? If you still can't figure it out share your nginx file too so I can see how the app is being executed.

**Comment by bastiandebyl** [comment]
I've tried it with lua as opposed to moonscript and that seemed to work. I
don't have the older, possibly problematic, nginx file on hand anymore.


Thanks!
