### ISSUE TITLE
enum does not contain key 1 (contains: 1:pending, 2:reviewed, 3:rejected)

### ISSUE THREAD

**Issue by Guard13007** [leafo/lapis#469]
... I'm a bit confused by that. It does not contain something it clearly contains?

**Comment by Guard13007** [comment]
So I was using a parameter that was supposed to be a number, but since all parameters are strings, it was erroring about there being no *string* "1".

Solved by doing this:

```moon
status: Crafts.statuses\for_db tonumber @params.status
```

This is very similar to a lot of issues I've run into due to wrong type. One of a few small things that makes it a bit difficult for beginners working with Lapis.

**Comment by leafo** [comment]
btw I recommend using the string names when passing the value aaround as a param, and the db variants only when putting into the model.
