### ISSUE TITLE
Can a migration be run to change the default value on a column?

### ISSUE THREAD

**Issue by Guard13007** [leafo/lapis#473]
I have a column with no default value set, and I now want to add a default value. Is this possible with the migrations system in Lapis?

**Comment by leafo** [comment]
Yes, but there's no helper function to generate the query. You'll have to write the raw SQL and pass it to `db.query`

**Comment by Guard13007** [comment]
I'm not very good with SQL, could you give me an example with a string?

**Comment by leafo** [comment]
```sql
alter table mytable alter mycolumn set default 1234
```

https://www.postgresql.org/docs/9.5/static/sql-altertable.html

**Comment by Guard13007** [comment]
Cool, thank you!
