### ISSUE TITLE
[bug] random strings are bad random strings due to re-seeding

### ISSUE THREAD

**Issue by Tieske** [leafo/lapis#477]
Lapis reseeds the random generator on each call to create a random string. And it seeds only with `os.time`, which has second precision. Hence, it will create many duplicates, especially when under load.

I don't know whether it is used to generate tokens etc, but then this actually is a security issue.

resolution;
 - seed only once per worker process, and make sure it's unique
 - drop the [randomseed calls](https://github.com/leafo/lapis/search?utf8=%E2%9C%93&q=randomseed)

consider using this library by @thibaultcha; https://github.com/thibaultcha/lua-resty-jit-uuid

**Comment by leafo** [comment]
randomseed only happens once when the module is loaded, which happens once per worker. There is potentially for duplicates if two workers get initialized at the same time though, so I do agree it's an issue.

**Comment by leafo** [comment]
On a second look, that function is defined in the `cmd` module, which would only be used by command line tools. Doesn't look like it's used anymore though. I was using it at one point to generate randomized nginx configuration endpoint but I changed my approach. I'll remove the code so others don't try to use it.

**Comment by Tieske** [comment]
thx!
