### ISSUE TITLE
Looks like a misprint in documentation

### ISSUE THREAD

**Issue by Qdamage** [leafo/lapis#478]
Hi guys, it is about "File Uploads" section.

```
local app = lapis.Application()

app:post("/my_action", function(self)
  local file = self.params.uploaded_file
  if file then
    return "Uploaded: " .. file.filename .. ", " .. #file.content .. "bytes"
  end
end)
```

self.params doesn't contain uploaded_file, but it has .file

**Comment by Guard13007** [comment]
~~The file upload will be in whatever name attribute you give the file upload. In that example, you can see they named it uploaded_file, so it was under `self.params.uploaded_file`~~

I just noticed you're looking at the Lua documentation. Switch over to MoonScript and you'll see the piece of the example that was missing. They named their file upload `uploaded_file`, so it got that name in the `self.params`. It's not so much a misprint as a lacking detail on the Lua side.

**Comment by Qdamage** [comment]
Ok, thank you!
