### ISSUE TITLE
Setting session data in Widget

### ISSUE THREAD

**Issue by Feilkin** [leafo/lapis#482]
I'm trying to implement Flask style message flashing, where i would `flash()` messages in code, which would get added to session table (session.flashed_messages), and in my layout, I would call `@get_flashed_messages`, which should return the messages from session.flashed_messages, AND remove them from the session.

However, session and cookies are written before the layout is rendered, so i can't just set the table to nil in the function i call from my layout.

I managed to get this to work with the following function, but it's not clean, and sends the session cookie twice.

```
@get_flashed_messages = (consume=true) =>
    messages = @session.flashed_messsages
    if consume
        @session.flashed_messsages = nil
        assert @@support.write_session @
        @@support.write_cookies @

    return messages

```

I know setting session variables from widgets is mixing logic with presentation, but i think it should still be possible.

**Comment by DarkWiiPlayer** [comment]
Why would you want to do that? just create a new table and add your messages there, then pass that table to the widget / template.

**Comment by Feilkin** [comment]
@DarkWiiPlayer I'm not sure what you mean by that? The messages should only be consumed IF they are rendered, and I'm not sure how I would implement that with just passing a table to the widget.

**Comment by DarkWiiPlayer** [comment]
@Feilkin Then you should decide which ones to render outside of the widget.

**Comment by leafo** [comment]
Hmm, missed this ticket. The session is written before the view is rendered currently. I would recommend reading & consuming the flash into a instance variable on the request, then using that to conditionally render it on the screen.

I don't think there was a particular reason for me putting it before the render, but a change like this could have unintended consequences, so if you think it should be moved tell me why.

Thanks

**Comment by Feilkin** [comment]
I see now that I was mistaken. Closing the issue :)
