### ISSUE TITLE
How to remove Content-Type header?

### ISSUE THREAD

**Issue by vadi2** [leafo/lapis#485]
I'm implementing the ``Prefer representation=minimal`` header form [RFC 7240](https://tools.ietf.org/html/rfc7240#section-4.2) and I need to have the Content-Type header not to be sent to the client, because they'd like to cut down on the bandwidth. Anything I tried, the default of ``text/html`` always gets added in. Is there a way of getting rid of it entirely so I can satisfy the RFC?

**Comment by leafo** [comment]
At the moment, if there is no content type then `text/html` is added. You might be able to remove it by adding code to strip it in your nginx config by running a line of code to do so after lapis handles the request

**Comment by vadi2** [comment]
Thanks, I'll see what I can do!

**Comment by vadi2** [comment]
This worked in nginx.conf - I set Content-Type to some value which I check later:

```lua
      default_type text/html;
      content_by_lua '
        require("lapis").serve("app")
      ';

      header_filter_by_lua_block {
        if ngx.header["Content-Type"] == "${{NO_RETURN_CONTENT_TYPE}}" then
          ngx.header["Content-Type"] = nil
        end
      }
    }
```

This is just a workaround for not being able to set it in Lapis, though.
