### ISSUE TITLE
Documentation on writing Model class and instance methods?

### ISSUE THREAD

**Issue by jprjr** [leafo/lapis#487]
Hi there!

I was browsing some lapis code [here](https://github.com/leafo/luarocks-site/blob/master/models/users.moon) and realized it's possible to write custom Class methods and instance methods for Lapis models.

I tried finding documentation on how to do this (particularly with Lua, I still write most things in Lua). It looks like adding/overriding methods on the model is pretty straightfoward, ie:

``` lua
local Model = require('lapis.db.model').Model
local User = Model:extend('users');

function User:create(username, password)
  if(self:check_unique_constraint("username",username)) then
    return nil, "Username already taken"
  end
  local encrypted_password = bcrypt.digest(password,5)

  return Model.create(User, {username = username, encrypted_password = encrypted_password });

end
```

But how do I create custom methods for the individual instances?

In my link above, it looks like methods like `check_password` instance methods, that's what prompted me to ask about this.

Thanks so much!

**Comment by leafo** [comment]
You can add instance methods by passing them into the table  as the second argument to `Model:extend`

```lua
Model:extend("users", {
  name_for_display = function(self)
    return self.display_name or self.username
  end
})
```

**Comment by jprjr** [comment]
Sweet, thank you so much! 

On November 3, 2016 1:16:37 PM CDT, leaf <notifications@github.com> wrote:
>You can add instance methods by passing them into the table  as the
>second argument to `Model:extend`
>
>```lua
>Model:extend("users", {
>  name_for_display = function(self)
>    return self.display_name or self.username
>  end
>})
>```
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/leafo/lapis/issues/487#issuecomment-258228900

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by leafo** [comment]
You could also use the function syntax by adding a method to `__base` on the model. All models are MoonScript classes, so you can learn more about them here: http://leafo.net/guides/moonscript-classes.html

```lua
local Model = require("lapis.db.model").Model
local Users = Model:extend("users")

function Users.__base:hello()
	print("hello from", self.username)
end

local user = Users:find(1)
user:hello()
```
