### ISSUE TITLE
/postgres.lua:55: module 'pgmoon' not found

### ISSUE THREAD

**Issue by timburgess** [leafo/lapis#488]
I've installed openresty and then luarocks and then lapis using luarocks but my install seems unusable.

I configured openresty with `--prefix=/usr/local`. I can run it without error and I can run luajit on the commandline without issue.

I then installed luarocks 2.4.1 and ran `./configure` that failed to find the /usr/local install. So after some investigation, I got it working with `./configure --lua-suffix=jit --with-lua=/usr/local/luajit --with-lua-include=/usr/local/luajit/include/luajit-2.1`

To my `.profile` I added:

`export LAPIS_OPENRESTY=/usr/local/bin/openresty`

`export PATH=/usr/local/luajit/bin:$PATH`

`export LUA_PATH='?.lua;/usr/local/luajit/share/luajit-2.1.0-beta2/?.lua;/usr/local/share/lua/5.1/?.lua;/home/ubuntu/openresty/lib/?.lua`

and then did a `source ~/.profile`

i then installed lapis with `sudo luarocks install lapis` as it failed without the sudo.

In a  project directory, I've run `lapis new --lua` that builds the initial files

Creating a `test.lua` with:

    local config = require("lapis.config")
    local db = require("lapis.db")
 
    --db connection
    config("development", {
     postgres = {
        host = "127.0.0.1",
        user = "ubuntu",    
        password = "xxxxxx",
       database = "test"
      }
     })

on the next line which is a `db.query(select .....)`

I get:

    luajit: /usr/local/share/lua/5.1/lapis/db/postgres.lua:55: module 'pgmoon' not found:
	no field package.preload['pgmoon']
	no file 'pgmoon.lua'
	no file '/usr/local/luajit/share/luajit-2.1.0-beta2/pgmoon.lua'
	no file '/usr/local/share/lua/5.1/pgmoon.lua'
	no file '/home/ubuntu/openresty/lib/pgmoon.lua'
	no file './pgmoon.so'
	no file '/usr/local/lib/lua/5.1/pgmoon.so'
	no file '/usr/local/luajit/lib/lua/5.1/pgmoon.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'

There is no `pgmoon.lua` in `/usr/local/share/lua/5.1/` but there is a pgmoon directory. There is no `pgmoon.lua` in the `pgmoon` directory though.

**Comment by leafo** [comment]
it looks like your package.path is missing the `init.lua` check.

Here's what a stock lua5.1 package.path looks like on my system:

```
;./?.lua;/usr/share/lua/5.1/?.lua;/usr/share/lua/5.1/?/init.lua;/usr/lib/lua/5.1/?.lua;/usr/lib/lua/5.1/?/init.lua
```

Notice the `?/init.lua` path, that needs to exist for any custom paths you use.

BTW you can use the `luarocks path` command line command to get the environment data you should be using for your installation of luarocks

**Comment by timburgess** [comment]
Thankyou! I wasn't aware of `luarocks path`. Also discovered the `luarocks path --bin`. And thanks for all your hard work on lapis. It's awesome.
