### ISSUE TITLE
Does not install cleanly on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by ttfkam** [leafo/lapis#489]
Lapis looks very interesting. Unfortunately the install documentation is insufficient for an install on to Ubuntu 16.04 LTS. The following does not successfully install.

% sudo luarocks install lapis

"Error: Failed installing dependency: https://rocks.moonscript.org/luacrypto-0.3.2-2.src.rock - Could not find expected file openssl/evp.h, or openssl/evp.h for OPENSSL -- you may have to install OPENSSL in your system and/or pass OPENSSL_DIR or OPENSSL_INCDIR to the luarocks command. Example: luarocks install luacrypto OPENSSL_DIR=/usr/local"

OpenSSL is installed however. I realize this is an issue from one of Lapis's dependencies, but the end result is the same: Lapis can't be installed.

**Comment by CriztianiX** [comment]
You need openssl devel
```bash
sudo apt-get install libssl-dev
 ```

**Comment by Guard13007** [comment]
I thought this was mentioned in the reference manual, but looking at the getting started page shows nothing. I can only assume this is not mentioned because that dependency should have already been installed when installing OpenResty, but perhaps it should be mentioned somewhere anyhow?

@ttfkam Has installing `libssl-dev` fixed the issue for you?

**Comment by ttfkam** [comment]
Needed a little more. From a clean server install, needed the following:

      `sudo apt-get install luarocks lua-sec libssl-dev git`

luarocks obviously. lua-sec to avoid warning about falling back to wget. git needed for dependency builds.

For reference, I'm using lapis with the package nginx-extras instead of the full openresty build. The dependencies above are all that are required to install on a bare server setup though.
