### ISSUE TITLE
Printing non-english characters in a view

### ISSUE THREAD

**Issue by anshzinc** [leafo/lapis#492]
Hi, I'm doing an API call on a service, and getting some texts. I need to display that result in a view.

but the response contains non-english characters and they do not apprar correctly by doing just a 

`<%= result %>`

what would be the easiest way to resolve this?

edit: was a issue with the charset. :) 

edit2: issue is not solved.

I have a string that looks like this:

"\u0915\u094d\u092f\u093e \u0926\u0947\u0936 \u092e\u0947\u0902 \u0910\u0938\u0947 \u0939\u093e\u0932\u093e\u0924\u094b\u0902 \u0915\u0947 \u092c\u0940\u091a \u0915\u093f\u0938\u0940 \u0936\u093e\u0926\u0940 \u092e\u0947\u0902 \u0907\u0924\u0928\u093e \u0916\u0930\u094d\u091a \u0920\u0940\u0915 \u0939\u0948?"

I need to pass this to a view, but right now it does not render. How can this be done?

**Comment by leafo** [comment]
Why doesn't it renderl, what happens? Lua strings can contain any encoding, so as long as the content encoding of whatever is rendering is set correctly it should appear. Does the string show correctly if you try printing it to the console?

**Comment by anshzinc** [comment]
It just renders like this: "\u0915\u094d\u092f\u093e \u0926\u0947\u0936 ...".

I should tell you I'm sending an HTTP request to an API, which returns json. 
see:
http://gadgets.bhaskar.com/fbcommented/ 

I need to show the text in a dashboard. 

Lets say my data looks like this: 
`{"title":"100 \u0930\u0941\u092a\u090f \u092e\u0947\u0902 \u092c\"}`

and I need to pass that data, so I do:

`self.title = utils.from_json(data).title`

and in the view I do: 

` <%= title %> `

but it doesn't render on the webpage. 

Also doing just a...

`print('{"title":"100 \u0930\u0941\u092a\u090f \u092e\u0947\u0902 \u092c"}')`

...gives this (expected) error:  invalid escape sequence near ''{"title":"100 '.

What am I doing wrong here?

**Comment by leafo** [comment]
is `from_json` extracting the characters correctly? It shouldn't output escape sequences, but the actual binary string. You should be able to load and print the json object on the command line.

**Comment by leafo** [comment]
Any updates on this? There's nothing I'm aware of about lapis that would be interfering with this. Open again if you're still having a problem.
