### ISSUE TITLE
Question about Model instance update method

### ISSUE THREAD

**Issue by Guard13007** [leafo/lapis#495]
I have a model with `name` and `description`.

I have an `instance` with `name` = `Same` and `description` = `something`.

Say I call that instance: `instance\update { name: "Same", description: "Different" }`

Does this break because part of the update is trying to update with the same data the model instance already had?

---

I recently started having a model sporadically fail to update after changing some code that made it so that an update method could be called with data that was unchanged. I noticed that some fields will update on their own, despite other data being present with unchanged values, but other fields would fail to update *unless* more than one field was changed. It all seems very random and got me thinking the only explanation is that the update method doesn't handle unchanged data well.

I've checked and double-checked my code, the only change is that now some unchanged data is passed through an update call, whereas before only actual changes went through.

**Comment by Guard13007** [comment]
I have since fixed the issue of passing through unchanged data on my code, and everything is working perfectly again, so I believe that was the issue.

Is this SQL or Lapis or what? And why doesn't it error? :/

**Comment by leafo** [comment]
Calling update will run the SQL query to update the fields, then copy the models into the model. It will happen regardless of what the current values are, there is no issue with updating an existing model with the same values, but it will create an unnecessary query.

**Comment by Guard13007** [comment]
That's really strange then, because it certainly was failing and that was the only thing wrong, the moment I stopped it, it stopped failing to update.

**Comment by leafo** [comment]
If you can provide a minimal set of code that reproduces the error it would be really helpful.
