### ISSUE TITLE
Got an issue with config.lua

### ISSUE THREAD

**Issue by transifex3** [leafo/lapis#496]
![111](https://cloud.githubusercontent.com/assets/16120391/20913866/a7e98d9c-bbbe-11e6-95b3-8593adec789b.png)
![222](https://cloud.githubusercontent.com/assets/16120391/20913867/a7ea01d2-bbbe-11e6-885a-e906c16b7d32.png)
![333](https://cloud.githubusercontent.com/assets/16120391/20913864/a7e914de-bbbe-11e6-8863-2840abfbdb8d.png)
![444](https://cloud.githubusercontent.com/assets/16120391/20913865/a7e97f00-bbbe-11e6-9a89-5f8b1b5435ef.png)
![555](https://cloud.githubusercontent.com/assets/16120391/20913868/a7ea876a-bbbe-11e6-8530-6e0edae18375.png)
![666](https://cloud.githubusercontent.com/assets/16120391/20913902/d6899606-bbbe-11e6-85d7-d610ad98f595.png)

If not compile config.moon, `lapis server` works but show me "internal error" on web page.
I am really new to here so just followed [This tutorial](http://leafo.net/lapis/reference/database.html)
Anything i missed?

**Comment by Kngrektor** [comment]
Hey, You just missed putting a `config = require "lapis.config"` at the top as seen in http://leafo.net/lapis/reference/configuration.html

**Comment by transifex3** [comment]
My god i was so stupid :( `lapis server` works perfectly now! Thanks Kngrektor.
