### ISSUE TITLE
working with postgresql

### ISSUE THREAD

**Issue by cslarson** [leafo/lapis#5]
I'm seeing the following error:

```
/usr/local/share/lua/5.1/lapis/db/model.lua:329: bad argument #1 to 'unpack' (table expected, got nil)
```

My development configuration has the following:

```
postgresql_url "postgres://postgres:my_password@127.0.0.1/my_db"
```

and in web.moon is:

```
lapis = require "lapis"
db = require "lapis.nginx.postgres"
import Model from require "lapis.db.model"

class Users extends Model
  @timestamp: true

class App extends lapis.Application
  "/": =>
    user = Users\find 1
    user.email

lapis.serve App
```

at various times I was also receiving the following message:

```
found RDS format version 1129268257, but we can only handle version 3
```

Is there a specific version of openresty i should be using?

**Comment by checkraiser** [comment]
I use this config, but nginx throws error: unknown directive "postgres_pass"
How to resolve this ?

**Comment by leafo** [comment]
This is outdated way of working with postgres. It's been removed from lapis. Follow the directions here: http://leafo.net/lapis/reference/database.html#establishing-a-connection

**Comment by gitrus** [comment]
Documentation is still invalid. In docs only conf script file but no words about nginx conf file.
