### ISSUE TITLE
Small suggestion for the documentation

### ISSUE THREAD

**Issue by DarkWiiPlayer** [leafo/lapis#504]
I know I promised, but I just had to go for that wonderful number 100. I'm sorry.

Anyway, I noticed that in the [documentation](http://leafo.net/lapis/reference/actions.html#error-handler) there's this line of code:
```lua
app.handle_404 = function(self)
```
Which I found really weird, since it can be written much more nicely as
```lua
function app:handle_404()
```

**Comment by leafo** [comment]
feel free to make a PR: https://github.com/leafo/lapis/blob/master/docs/actions.md#error-handler

**Comment by leafo** [comment]
Now fixed
