### ISSUE TITLE
lapis term - Aborting: failed to find nginx process

### ISSUE THREAD

**Issue by ph55** [leafo/lapis#511]
Can't stop server with `lapis term` when running in background with `daemon on`
Following error thrown:

```
root@vagrant-ubuntu-trusty-64:/var/www/web-app# lapis term
Aborting: failed to find nginx process
```

Nginx process:
```
root@vagrant-ubuntu-trusty-64:/var/www/web-app# ps aux | grep nginx
root      4402  0.0  0.3 149876  1944 ?        Ss   07:15   0:00 nginx: master process /usr/sbin/nginx -p /var/www/web-app/ -c nginx.conf.compiled
nobody    4403  0.0  0.9 149880  4688 ?        S    07:15   0:00 nginx: worker process
```

OS:
```
root@vagrant-ubuntu-trusty-64:/var/www/web-app# cat /etc/os-release
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```

**Comment by leafo** [comment]
Did you change where the pid file is written? Lapis expects pid file to be in the default location, in the logs directory alongside your application.

**Comment by ph55** [comment]
@leafo No. Nothing changed. 

Here is content of logs directory of app (after `lapis server`) :

```
root@vagrant-ubuntu-trusty-64:/var/www# ls -l /var/www/web-app/logs/
total 0
-rw-r--r-- 1 root root 0 Jan 19 09:48 access.log
-rw-r--r-- 1 root root 0 Jan 19 09:48 error.log
root@vagrant-ubuntu-trusty-64:/var/www#
```
Is there should be PID file ?

**Comment by leafo** [comment]
yeah, normal installations should produce this:

```
(master) ~/code/sites/sightreading.training > ls -lah logs
total 196K
drwxr-xr-x  2 leafo users 4.0K Jan 19 11:53 .
drwxr-xr-x 17 leafo users 4.0K Jan 19 11:40 ..
-rw-r--r--  1 leafo users 173K Jan 19 12:25 access.log
-rw-r--r--  1 leafo users 2.4K Jan 19 11:53 error.log
-rw-r--r--  1 leafo users    5 Jan 19 11:53 nginx.pid
```

**Comment by ph55** [comment]
Ok. Found the problem.
`lapis new` generates `nginx.conf` with `pid logs/nginx.pid;`

But for version control I've copied `nginx.conf` from [official-docs](http://leafo.net/lapis/reference/getting_started.html#creating-an-application/nginx-configuration) that lacks this row.

Thanks.

**Comment by leafo** [comment]
It's not required to have the pid file statement in you config unless your nginx is compiled with a configuration option that overrides the default. I can update the docs to reflect the latest config template though.
