### ISSUE TITLE
Is there a way to stop @build_url and @url_for from including port number when generating URLs?

### ISSUE THREAD

**Issue by Guard13007** [leafo/lapis#515]
I run my Lapis server(s) on a non-standard port with an instance of NGINX proxying requests based on domain name. I would prefer URLs to only use the domain name, without port number.

(On a related note, I would like to block the port from being accessible other than through the proxy, but I know that's outside of the scope of this project. Something I need to learn how to do with iptables I'm guessing.)

**Comment by DarkWiiPlayer** [comment]
http://mailman.nginx.org/pipermail/nginx/2009-February/009947.html
and
http://serverfault.com/questions/667798/allow-only-local-users-in-nginx

(https://duckduckgo.com?q=nginx+reject+local+requests&t=vivaldi&ia=qa)

**Comment by Guard13007** [comment]
Answering my own question: The behavior of `@build_url` can be modified by passing a table of options: http://leafo.net/lapis/reference/actions.html#request-object-methods/build_url

This isn't what I want, but considering what I want is probably misguided, this is good enough.

**Comment by leafo** [comment]
I do think it's common for people to run the server behind a reverse proxy, so they would want to hide the port of the internal server. What I've done in the past if I need to change default behavior is subclass the `Request`class and provide an intermediate implementation of `build_url` but that's a bit complicated

**Comment by leafo** [comment]
I added a new support method on request that can be overwritten to provide custom default params for build_url

**Comment by padicao2010** [comment]
@leafo How can I customize the default params for build_url? Any document? I just met with the same issue with https.

**Comment by leafo** [comment]
@padicao2010 you can subclass the defaul request and override the `default_url_params` support method.

You can see an example of this here:  https://github.com/leafo/streak.club/blob/master/helpers/request.moon

Then to use your custom request object you can do this:

https://github.com/leafo/streak.club/blob/master/app.moon#L26

**Comment by padicao2010** [comment]
Great, it works. Thanks.
