### ISSUE TITLE
no os write permission when run on port 80?

### ISSUE THREAD

**Issue by JamieRoling** [leafo/lapis#521]
Not sure if this is nginx or lapis really, but I have this piece of code to write an image blob to disk

```lua
imageLocation = 'static/media/' .. arg1.feedName .. '/' .. postID .. fileExt
imageFile = io.open(imageLocation, 'w')
if imageFile then
  imageFile:write(arg1.postImage.content)
  imageFile:close()
else
  imageLocation = nil
end
```

but whenever I try and run it on port 80 it refuses to write files to disk. Other ports work fine.

Anyone know a solution?

Kind regards.

**Comment by leafo** [comment]
Is it possible you're running the server with a different user when you're changing the port it's bound to, and that user is unable to write to that location? Or maybe the running directory changed and the `static` directory doesn't exist?

Lapis doesn't know anything about file permissions, or change user. This would be an nginx problem. You'll have to figure out why the nginx worker doesn't have permission to write there. Maybe looking at the running process and the user it's using might give you a hint
