### ISSUE TITLE
How to get the MySQL "res" row count?

### ISSUE THREAD

**Issue by ghost** [leafo/lapis#523]
Is there a function like PDO's "$stmt->rowCount()"?
Anyway #res will do it, maybe not the ideal though.

**Comment by DarkWiiPlayer** [comment]
I'd have to dig through the code, but I assume `#res` just uses the lua standard way of counting the length of an array; but it might also be that lapis sets a custom metamethod for that. I *assume* the way lua does it is to look at the size of the tables internal array, which should be relatively fast (linear speed?) so there's nothing really wrong with it.

**Comment by leafo** [comment]
Counting the items in the result set is the way to go.
