### ISSUE TITLE
How to write nginx.conf in order to implement php? 

### ISSUE THREAD

**Issue by sheguibo** [leafo/lapis#524]
How to write nginx.conf in order to implement php?   php-fpm already run ，the nginx.conf how to config?  help,, i need run some php in lapis

**Comment by sheguibo** [comment]
i create the new file test.php   in "/Users/Macx/coding/php"

the config file:
...
location ~ \.php\$ {
            root /Users/Macx/coding/php;
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME /Users/Macx/coding/php$fastcgi_script_name;
            include /usr/local/openresty/nginx/conf/fastcgi_params;
        }
...

when i open the "localhost:8080/test.php",,

it show
" Failed to find route: /test.php"..

**Comment by kosaho** [comment]
That's weird, I just tested it for you and it's working fine.

```
location ~ \.php$ {
    root /home/me;
    include /usr/local/openresty/nginx/conf/fastcgi_params;
    fastcgi_pass unix:/var/run/php5-fpm.sock;
    fastcgi_param SCRIPT_FILENAME /home/me$fastcgi_script_name;
}
```

Are you sure PHP is listening port 9000?
Also, make sure you're inserting this code inside the server{} block.

**Comment by sheguibo** [comment]
ohh,thank you,,maybe the nginx.conf  ,i write wrong,,  i put 
"location ~ .php$ {
root /Users/Macx/coding/php;
fastcgi_pass 127.0.0.1:9000;
fastcgi_index index.php;
fastcgi_param SCRIPT_FILENAME /Users/Macx/coding/php$fastcgi_script_name;
include /usr/local/openresty/nginx/conf/fastcgi_params;
}"

in the file  in the end and inside the server{} ,,thanks！！

**Comment by sliceofcode** [comment]
@sheguibo You might want to close this issue.
![closing a github issue](https://cloud.githubusercontent.com/assets/4206232/23583811/837cd1c8-0103-11e7-9e0c-8ec01fc23adb.gif)

**Comment by sheguibo** [comment]
thank
