### ISSUE TITLE
Turns out nil and nothing aren't the same

### ISSUE THREAD

**Issue by DarkWiiPlayer** [leafo/lapis#527]
<% local table = require "lapis.db.model".Model:extend("table") %>
    <%= table:find"something_that_doesnt_exist"  %>
this throws an error. But fear not, no need to debug this, because I already know the problem!
As it turns out, the documentation lied to us when saying "find returns an instance of the model if it could be found, nil otherwise", because find does NOT return nil. It returns nothing. And no matter what the lua documentation wants to make you believe, those two are not the same. `return nil` returns an actual nil, while `return;` or just `end` without ever returning don't return nothing. Try it at home: `tostring(function() return nil end())` works, but `tostring(function() return end())` throws an error.

Quick fix for anybody having the same problem: <%= table:find"something_that_doesnt_exist"  or nil %>

Conclusion: When you say you return nil, make sure you actually do return nil.

**Comment by DarkWiiPlayer** [comment]
Did some minor code digging, and it seems the implementation of the find function uses the `table.unpack` function. And there we have our culprit. try `tostring(table.unpack{})`, which is exactly what ends up happening in this case, except removing some steps in between.

**Comment by DarkWiiPlayer** [comment]
@leafo Is there a reason why you use unpack here instead of just indexing with [1]?

`if result = unpack @db.select "* from #{table_name} where #{cond} limit 1"`

**Comment by leafo** [comment]
no particular reason @DarkWiiPlayer
