### ISSUE TITLE
Error: attempt to index local '_with_0' (a nil value)

### ISSUE THREAD

**Issue by sfederici** [leafo/lapis#529]
After first installation (via luarocks) when I run "lapis server" I get the following error message:

Error: attempt to index local '_with_0' (a nil value)
 * Run with --trace to see traceback
 * Report issues to https://github.com/leafo/lapis/issues

When running with --trace what I get is the following

Error: /usr/local/share/lua/5.1/lapis/cmd/path.lua:33: attempt to index local '_with_0' (a nil value)
stack traceback:
	/usr/local/share/lua/5.1/lapis/cmd/path.lua:33: in function </usr/local/share/lua/5.1/lapis/cmd/path.lua:29>
	(tail call): ?
	(tail call): ?
	/usr/local/share/lua/5.1/lapis/cmd/actions.lua:110: in function </usr/local/share/lua/5.1/lapis/cmd/actions.lua:100>
	(tail call): ?
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/lapis/cmd/actions.lua:323: in function 'execute'
	...usr/local/lib/luarocks/rocks/lapis/1.5.1-1/bin/lapis:4: in main chunk
	[C]: ?

Thanks in advance for your help

**Comment by sfederici** [comment]
Sorry, wrong user. Running the server as "su" solve the issue.

**Comment by leafo** [comment]
generally you should avoid running the server as su, is there a permissions issue with some of the config files in your project's directory?

**Comment by sfederici** [comment]
Hi, I'm just following instructions I found on the github project "beetlecloud". To make them work I had to be su.
