### ISSUE TITLE
Difference between escaping raw strings with quotes or double brackets in Moonscript

### ISSUE THREAD

**Issue by cscomfort** [leafo/lapis#530]
I'm just now getting familiar with Lapis and Moonscript, the latter of which I'm taking advantage of in my templates. One thing I'm trying to get a better sense of is the difference between escaping raw strings with quotes and double brackets--especially in cases where I'm passing a variable from the action to the template.

Consider the following, noting that I'm obviously using Lua to write the app logic and Moonscript for the templates (just so I can get some exposure to both while learning):

**app.lua**
```lua
app:get("/", function(self)
  self.name = "Chris"
  return {
    render = "index",
    layout = require("views.layout")
  }
end)
```

**In .moon template with quotes**
```moonscript
@content_for "ractive_data", ->
  script type: "text/javascript", ->
    raw "
      var ractive = new Ractive({
        el: '#container',
        template: '#template',
        data: { name: '#{@name}' }
      });
    "
```

**...output (with data passed as desired)**
```javascript
<script type="text/javascript">
  var ractive = new Ractive({
    el: '#container',
    template: '#template',
    data: { name: 'Chris' }
  });
</script>
```

**In .moon template with double brackets**
```moonscript
@content_for "ractive_data", ->
  script type: "text/javascript", ->
    raw [[
      var ractive = new Ractive({
        el: '#container',
        template: '#template',
        data: { name: '#{@name}' }
      });
    ]]
```

**...output**
```javascript
<script type="text/javascript">
  var ractive = new Ractive({
    el: '#container',
    template: '#template',
    data: { name: '#{@name}' }
  });
</script>
```

I've tried to find some documentation that explains the difference, looking in both the Lapis and Moonscript docs, but can't seem to find anything.

Could you help clarify?

Thanks and keep up the great work!

**Comment by Guard13007** [comment]
It's a feature of Lua. There is no escaping inside of a string denoted by double brackets. Everything within them is completely literal.
