### ISSUE TITLE
Does Lapis really depend on Openresty?

### ISSUE THREAD

**Issue by tongson** [leafo/lapis#533]
As far as I can tell Lapis only depends on the Nginx Lua module (ngx_http_lua_module.so).

I have a simple Lapis application working with just that module loaded.

Does Lapis need any of the components listed in:
http://openresty.org/en/components.html

**Comment by tongson** [comment]
Looking around the site, pgmoon needs the Openresty's socket API. Any other part of Lapis that needs a Openresty component?

**Comment by tongson** [comment]
ngx_http_lua_module.so does include the socket API. https://github.com/openresty/lua-nginx-module/blob/master/src/ngx_http_lua_socket_tcp.c

**Comment by leafo** [comment]
what's in master no longer depends on openresty, I started adding support for https://github.com/daurnimator/lua-http as an http server. It's not 100% complete. 

Additionally, much of lapis can be run without a web server on the command line. You can all the database modules perfectly fine on the command line or in another server app. Just keep mind you might not get asynchronous IO if lapis isn't aware of the environment it's running in

**Comment by tongson** [comment]
Good to know.

I'm running the latest release and I'm just forcing detection for Openresty.

A bit OT, I also see that only one function is used in LuaCrypto. In my application I removed that dependency and used the HMAC sha1 implementation in:
https://github.com/kikito/sha1.lua

    --- lapis/util/encoding.lua
    +++ lapis/util/encoding.lua
    @@ -15,9 +15,9 @@
    decode_base64 = function(...)
         return (unb64(...))
    end
    -  local crypto = require("crypto")
    +  local sha1 = require("sha1")
       hmac_sha1 = function(secret, str)
    -    return crypto.hmac.digest("sha1", str, secret, true)
    +    return sha1.hmac_binary(secret, str)
       end
    end
    local encode_with_secret

Thanks!

**Comment by leafo** [comment]
Closing this since we have much better support for cqueues & lua-http now.
