### ISSUE TITLE
Redirect Issue

### ISSUE THREAD

**Issue by Dvineone** [leafo/lapis#534]
I hope this is the right place to post this. I have tried everything i can think of to get the server to redirect after making a database call however i have yet to figure it out. 

This is the post route i am using

```
app:post("login", "/login", function(self)
    local username = self.params.username
    local password =  self.params.password
    local user = dbUser.query("select username from user_creds where username=?", username)

    for k, v in ipairs(user) do
        if(v["username"] ~= self.params.username) then
            return { render = self:url_for("login") }
        end
    end
    return { render = self:url_for("home") }
end)
```

if i comment out all the database code the route will redirect fine.

This is the ajax call that i am using to pass data back to the route
```
$.ajax({
                method: "POST",
                action: "/login",
                data: { username: user, password: pass},
                success: function(data) {
                    window.location.href = "<%= url_for("home") %>";
                },
                error: function(jqXHR, exception) {
                    console.log("Error Called!!!");
                }
            });
```

without returning a json this will fail. however it fails anyway if i have the database call active.

Any help would be appreciated.

**Comment by leafo** [comment]
Render takes the name of a template to render as HTML. Perhaps you mean to use `{redirect_to = self:url_for()}` instead of `{render = self:url_for()}`

http://leafo.net/lapis/reference/actions.html#render-options

**Comment by Dvineone** [comment]
Tried redirect_to that also did nothing.

**Comment by leafo** [comment]
Can you check the browser console or the lapis log to see what kind of response it is returning. If you database call is throwing an error then it's going to render a 500 error page and halt all other code from running.

**Comment by Dvineone** [comment]
I will post a screen capture of the logs when I get home tonight. Ty for your help.

**Comment by Dvineone** [comment]
This is the first screen shot of the logs from lapis when i post the user name and password.

![selection_001](https://cloud.githubusercontent.com/assets/4534564/24686380/2d61df20-1979-11e7-8ae7-cce0e71c9083.png)


The code:
```
app:post("login", "/login", function(self)
    local username = self.params.username
    local password =  self.params.password
    local user = dbUser.query("select username from user_creds where username=?", username)

    --for k, v in ipairs(user) do
    --    if(v["username"] ~= self.params.username) then
    --        return { redirect_to = self:url_for("login") }
    --    end
    --end
    return { redirect_to =  self:url_for("home") }
end)
```
I know that the logs show a redirect happens but you will have o take my word that the only thing that happens is the login page is refreshed.

The second capture

![selection_002](https://cloud.githubusercontent.com/assets/4534564/24686376/24ba5bcc-1979-11e7-87d2-a1181d8c6fc8.png)


The Code:
```
app:post("login", "/login", function(self)
    local username = self.params.username
    local password =  self.params.password
    local user = dbUser.query("select username from user_creds where username=?", username)

    --for k, v in ipairs(user) do
    --    if(v["username"] ~= self.params.username) then
    --        return { redirect_to = self:url_for("login") }
    --    end
    --end
    return { json = { }  }
end)
```

Capture without database call

![selection_003](https://cloud.githubusercontent.com/assets/4534564/24686369/14b4cd20-1979-11e7-8078-03ff0e297c8a.png)


The Code
```
app:post("login", "/login", function(self)
    local username = self.params.username
    local password =  self.params.password
    --local user = dbUser.query("select username from user_creds where username=?", username)

    --for k, v in ipairs(user) do
    --    if(v["username"] ~= self.params.username) then
    --        return { redirect_to = self:url_for("login") }
    --    end
    --end
    return { redirect_to = self:url_for("home")  }
end)
```

Final Capture

![selection_004](https://cloud.githubusercontent.com/assets/4534564/24686366/0b64bd7a-1979-11e7-9fa3-2786d64ef142.png)

The code:
```
app:post("login", "/login", function(self)
    local username = self.params.username
    local password =  self.params.password
    --local user = dbUser.query("select username from user_creds where username=?", username)

    --for k, v in ipairs(user) do
    --    if(v["username"] ~= self.params.username) then
    --        return { redirect_to = self:url_for("login") }
    --    end
    --end
    return { json = { }  }
end)
```

I know that most of these show a redirect in the logs but the only one that actually redirects is the final one.

This is the message in the browser console from all but the last capture.

![selection_005](https://cloud.githubusercontent.com/assets/4534564/24686353/f5b3fea0-1978-11e7-8b03-ff1831304a27.png)

The last capture has this message

![selection_006](https://cloud.githubusercontent.com/assets/4534564/24686346/e8c8750e-1978-11e7-8df1-657ecd98cfce.png)


These two messages are called from the ajax return handlers.

**Comment by VaiN474** [comment]
I know it's been a while since this issue was posted, but I thought I'd give some feedback just in case it's helpful.

Is the route to `login` only for the Ajax call?  If so, you don't want to redirect inside the route, but instead redirect from within your jQuery based on the returned value.

Regarding the database call, I'd highly recommend taking advantage of [Models](http://leafo.net/lapis/reference/models.html).

```lua
local Model = require("lapis.db.model").Model
local Users = Model:extend("user_creds")
local user = Users:find({ username = username })
if user == nil then
  return { json = { val = 0, message = "Username is not registered" } } -- login fail
else
  -- check login creds
  return { json = { val = 1 } } -- login success
end
```

Just an example. Hope that helps.

**Comment by leafo** [comment]
Closing older tickets, feel free to reply if you're still having an issue.
