### ISSUE TITLE
Virtual servers management with LAPIS

### ISSUE THREAD

**Issue by webandbusiness** [leafo/lapis#536]
Hello, i am using a plateform with debian8 and Openresty as based serveur.
I share multiples virtual servers
I want to use each virtual server with 1 lapis application.

How can i configure 
Thanks

**Comment by leafo** [comment]
Typically the easiest way to do this is to to run many instances of lapis all on unique ports, then have a single nginx listening on 80 that is configured to reverse proxy to the lapis

**Comment by webandbusiness** [comment]
Thanks for ya reply.

is it not simpler to use it as a openresty module in the require folder.

and implement this way:
Let me know what you think? what are pros? and con? of the following implementation
-----------------------------------------------------------------
-------------app.lua in his folder root
------------------------------------------------------------------
local lapis = require("lapis")
local utils = require("lapis.util")
local app = lapis.Application()

app:enable("etlua")
app:match("/:path", function(self)
  self.pets = {
    "Cats",
    "Horses",
    "Skateboards"
  }
return { status = 404, render="page1",uuid }
end)
lapis.serve(app)


---------------------------------------------------------------------
--------------nginx.conf main server config file
----------------------------------------------------------
--------- Virtual server N
server {
	server_name  domain.com  www.domain.com;
        listen 80 so_keepalive=10s:2s:2;
        resolver 8.8.8.8;
        
	  location / {
	  default_type text/html;
	  content_by_lua_file /path/to/app.lua;
	  }
    }

**Comment by leafo** [comment]
It is also possible to run many lapis application from the same nginx but each worker will share the same lua runtime for every app. This means that you can only have one working directory, and you need to name all your modules so there aren't any conflicts. Lapis makes the assumption that a single app will own the working directory, so you might need to tweak default module loading parameters.
