### ISSUE TITLE
reactive apps with lapis

### ISSUE THREAD

**Issue by jack0088** [leafo/lapis#537]
is it possible to have the views auto-update themselfs from the databse? similar to what meteorjs or emberjs pr reactjs do.. reactive one-page-apps. I'd like to create something similar to a chat.

**Comment by Guard13007** [comment]
There is nothing built-in for that. You'd have to come up with your open method for it.

**Comment by CatLover91** [comment]
There are very few resources for writing a react-based Lapis application, but I believe streak.club partially utilizes react, and you can [check the source](https://github.com/leafo/streak.club/tree/master/static/coffee/main) for reference when building.
