### ISSUE TITLE
how to assert_error on a function that returns boolean?

### ISSUE THREAD

**Issue by ghprince** [leafo/lapis#540]
So Lapis has this very helpful `assert_error` method

> It is idiomatic in Lua to return nil and an error message from a function when it fails. For this reason the helper assert_error exists. If the first argument is falsey (nil or false) then the second argument is thrown as an error, otherwise all the arguments are returned from the function unchanged.

And here is the current implementation
```lua
local assert_error
assert_error = function(thing, msg, ...)
  if not (thing) then
    yield_error(msg)
  end
  return thing, msg, ...
end
```

I am curious why it is checking `falsy` instead of `nil` for the first return value?
And what is the idiomatic way to have a function that returns a boolean value? with current `assert_error` implementation, a good valid `false` return will be treated as an error.

**Comment by leafo** [comment]
`assert_error` matches the api to Lua's `assert` function, so both false and nil cause it to fail.

You could potentially write something like this:

    assert_error(false == myfunction(), "some error message")

but you would have to provide your own error message, and you would lose any return values being passed through.

You might also be interested in the `yield_error` function which just lets you throw an error directly, so you would have to provide your own `if` statement but the code might look cleaner.
