### ISSUE TITLE
Tup failed to parse

### ISSUE THREAD

**Issue by aiibe** [leafo/lapis#541]
New to Lapis. I am currently trying to add some "decorator" function to my helpers and Tup won't parse it. I don't get it. Here's the code: (helpers/app.moon)
```moonscript
error404 = {render: "error404", status: 404}
anonymous = (fn) ->
	=>
		if @current_user
			redirect_to: @url_for "create"
		else
			fn @

super_required = (fn) ->
	=>
		if @current_user and @current_user.flag == 2
			fn @
		else
			error404
{:super_required, :anonymous} 
```
Sublime Text highlights the line " if @current_user " in anonymous function.
Lapis and Moonscript are really awesome btw, thanks @leafo

**Comment by aiibe** [comment]
I changed the anonymous function to :
```moonscript
anonymous = (fn) ->
	=>
		if not @current_user
			fn @
		else
			redirect_to: @url_for "create"
```
Now works fine. Still don't get it why.

**Comment by leafo** [comment]
Hey, thanks for the report. This is actually a MoonScript bug, there's a syntax precedence problem that needs to be fixed. In the meantime you can write this: 

```
error404 = {render: "error404", status: 404}
anonymous = (fn) ->
  =>
    if @current_user
      { redirect_to: @url_for "create" }
    else
      fn @
```

Note the `{}` round the `redirect_to`
