### ISSUE TITLE
install fails through luarocks 

### ISSUE THREAD

**Issue by aajjbb** [leafo/lapis#545]
I'm trying to install Lapis through Luarocks (Lua 5.1 and Luarocks 2.4.0 in a fresh Manjaro install). In this version of Lua/Luarocks, it's currently not possible to install Lapis because the dependency [luacrypto](https://luarocks.org/modules/starius/luacrypto) build is failing. Is there another way to install lapis through luarocks overcoming this issue ?

**Comment by concatime** [comment]
I got problems with luacrypto using the openssl sources. I just install libssl-dev (Ubuntu), and it compiled correctly.

**Comment by nonchip** [comment]
see also #430. luacrypto is pretty much dead.

**Comment by mitki** [comment]
I can reproduce it on Arch Linux, luacrypto does not build.

**Comment by concatime** [comment]
Well, It seems that they changed to `luaossl`

**Comment by mitki** [comment]
@concatime the issue isn't solved yet since the luarocks package still depends on luacrypto.

**Comment by aajjbb** [comment]
Apparently the issue was solved here but a new version without `luacrypto` isn't in LuaRocks yet.

**Comment by leafo** [comment]
You need to have openssl-1.0 installed on your system and tell luarocks to build with it. A lot of distros are using 1.1 by default.

On archlinux:

```
sudo payman -Sy openssl-1.0

luarocks install luacrypto CFLAGS='-I/usr/include/openssl-1.0 -O2 -fPIC' LIBFLAG='-L/usr/lib/openssl-1.0 -shared'
```

**Comment by leafo** [comment]
Closing this since we switched to `luaossl` a while back.
