### ISSUE TITLE
Upload Issue is_file

### ISSUE THREAD

**Issue by whitebook** [leafo/lapis#550]
Hello @leafo 

I am not sure when I try to  upload using Python requests I get response "File Missing"; however using the browser with input=file it works fine.

here is the python requests snippet.

req = requests.post("http:/localhost/media/upload", files={"file":open(file, "rb")}, params={"name":"val"})
req.response

'{"errors":["Missing file"]}'

req.request.headers 

{'Content-Length': '800271', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'User-Agent': 'python-requests/2.17.3', 'Connection': 'keep-alive', 'Content-Type': 'multipart/form-data; boundary=ffa1ef5ed68d44fdab2ee14f498427ab'}

req.request.body (Truncated)
req.request.body
'--ffa1ef5ed68d44fdab2ee14f498427ab\r\nContent-Disposition: form-data; name="file"; filename="video000000.mp4"\r\n\r\n\x00\x00\x00\x18ftypmp42\x00\x00\x00\x00isommp42\x00\x00\x07\xfbmoov\x00\x00\x00lmvhd\x0...
\r\n--ffa1ef5ed68d44fdab2ee14f498427ab--\r\n'

So the interesting thing to note, if I use python requests and I call 

@params.file -- I get the uploaded data but not the file handler to call "file.content"

Any ideas where to look to solve this issue...

Or am I doing something wrong...

Thanks in advance for any pointers..

**Comment by whitebook** [comment]
@leafo seems that if you dont pass the content-type on the upload "is_file" fails

'--39d3d32a12d64567920742248349eac0\r\nContent-Disposition: form-data; name="upload_file"; filename="file.mp3"\r\nContent-Type: audio/mpeg\r\n\r\n...

**Comment by whitebook** [comment]
@leafo 
I think the cause is from this line lapis/nginx.moon 

line 25: if name == "Content-Disposition"
I noticed some Clients dont send proper case headers, so the file validation fails.

seems if you do name\lower == "content-disposition" it works in all cases.

Any objections to such a change?

Thanks.

**Comment by leafo** [comment]
@whitebook no objection to the change, feel free to make a PR

**Comment by whitebook** [comment]
@leafo Thx! See PR #552
