### ISSUE TITLE
compile error when 'luarocks install lapis'

### ISSUE THREAD

**Issue by uudiin** [leafo/lapis#551]
lua_cjson.c:1298:13: error: static declaration of ‘luaL_setfuncs’ follows non-static declaration
 static void luaL_setfuncs (lua_State *l, const luaL_Reg *reg, int nup)
             ^
In file included from lua_cjson.c:44:0:
/usr/local/openresty/luajit/include/luajit-2.1/lauxlib.h:88:18: note: previous declaration of ‘luaL_setfuncs’ was here
 LUALIB_API void (luaL_setfuncs) (lua_State *L, const luaL_Reg *l, int nup);

**Comment by travisbell** [comment]
This has been discussed here already, check out: https://github.com/leafo/lapis/issues/539
