### ISSUE TITLE
Lapis migrate does not find database configuration

### ISSUE THREAD

**Issue by lasfter** [leafo/lapis#555]
Running lapis migrate fails with the following error:
```Error: You have to configure either postgres or mysql```

This is despite my config.lua containing
``` lua
local config = require "lapis.config"

config("development", {
  postgres = {
    host = "127.0.0.1",
    user = "postgres",
    password = "postgres",
    database = "dev_db"
  },
  -- more stuff
})
```
The dev_db database exists, and the postgres passwords are correct.
 
config.lua is in the root directory of the app, alongside my nginx.conf and migrations.lua. I run lapis migrate in that directory as well.

Curiously, if I manually run the migration with lua code, it _sometimes_ works, and sometimes gives the same error. 

Some other weird results lead me to believe that lapis caches the configuration somewhere? Could that be the issue?

**Comment by leafo** [comment]
Is it possible you're running the command in a different environment?

If you want to verify that the configuration file is being loaded you can put `error("hello world")` at the top of the config file. If it is being loaded you should see that error when running migrate.

The fact that it sometimes works, and sometimes doesn't, is strange. Are you sure nothing else is changing?

**Comment by lasfter** [comment]
The issue was with my rockspec file. My config.lua wasn't read (putting an error() call changed nothing).

I changed the environment from "development" to production (so that there would be no more development config in my config.lua) and calling the various lapis CLI commands in the development environment still used the old configuration (which no longer exists!). 

The issue came about because my rockspec file listed my config as a module. It's strange because I didn't have any such issues with app.lua, but by removing config.lua as a module everything works as expected.

``` lua
build = {
   type = "builtin",
   modules = {
      app = "app.lua",
      -- remove this
      config = "config.lua",
      models = "models.lua"
   }
}
```

**Comment by leafo** [comment]
Interesting, so the luarocks package path was taking precedence over the working directory? You might want to consider changing the order
