### ISSUE TITLE
Connecting to postgresql

### ISSUE THREAD

**Issue by PetrChalov** [leafo/lapis#556]
Application drops when I try to query the database (PostgreSQL) with the output:

> 2017/07/01 16:04:26 [error] 31284#0: *8 lua entry thread aborted: runtime error: attempt to yield across C-call boundary stack traceback: coroutine 0: [C]: in function 'require' /usr/local/share/lua/5.1/lapis/init.lua:15: in function 'serve' content_by_lua(nginx.conf.compiled:22):2: in function , client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:8080"

The code that causes the error:

```
local db = require("lapis.db");
local res = db.query("SELECT * FROM users");
```

config.lua:

```
config({ "development", "production" }, {
    postgres = {
        host = "0.0.0.0",
        port = "5432",
        user = "wars_base",
        password = "12345",
        database = "wars_base"
    }
})
```

The database is running, the table is created, in table 1 there is a record.

What could be the problem?

**Comment by leafo** [comment]
I'm guessing you're putting a query in the top level of a module file. You should run a query in the action of an application, in response to a request, not when the module is being loaded.

**Comment by PetrChalov** [comment]
Thanks, helped.
Is it possible to use queries not only in the action on the request?

**Comment by leafo** [comment]
As far as I undertstand, during the initialization of OpenResty the socket interface is not available. You can make something that lazily runs the query for the first time when an action hits it though.
