### ISSUE TITLE
View Cells [feature]

### ISSUE THREAD

**Issue by CriztianiX** [leafo/lapis#558]
From popular frameworks view cells are:

> View cells are small mini-controllers that can invoke view logic and render out templates.

I've created a minimal component for archive this goal:
[lapis-components - cell](https://github.com/CriztianiX/lapis-components)

are there any plan for something like this to be incorporated into the core of lapis?

**Comment by Guard13007** [comment]
What's the difference between this concept and widgets? Either I'm completely missing something or it's the same concept..

**Comment by CriztianiX** [comment]
I do not think so, the cell only sends data to be used within an element (etlua template)

The concept was taken from
https://book.cakephp.org/3.0/en/views/cells.html

Maybe, Widgets can be do the same, but i dont know how to do it with etlua templates.

Salutes!
