### ISSUE TITLE
Fresh install of OpenResty / Lapis / MoonScript, failed to run migration

### ISSUE THREAD

**Issue by Guard13007** [leafo/lapis#560]
I don't remember the exact error, but it said it failed to find the module `crypto`.

I fixed this by running `luarocks install luacrypto` but I thought that it should've been installed while running `luarocks install lapis`?

**Comment by leafo** [comment]
The crypto library has been swapped out a while back and is no longer optional dependency

**Comment by Guard13007** [comment]
What was it swapped to?

**Comment by leafo** [comment]
@Guard13007 luaossl

**Comment by Guard13007** [comment]
This same error is occurring on a fresh install, again, I fixed it by installing luacrypto.

Something is wrong here, and I don't know where, but there is definitely something to investigate.
