### ISSUE TITLE
Inverse of db.format_date ?

### ISSUE THREAD

**Issue by Guard13007** [leafo/lapis#562]
I don't know if it is common enough a problem to warrant it, but I would like an inverse of the `db.format_date` function for converting a database entry back to Unix time.

I have implemented it this way for my own use, but I have no idea if it's even a good way of doing it:

```moonscript
db_time_to_unix = (time) ->
  tab = {
    year: tonumber time\sub 1, 4
    month: tonumber time\sub 6, 7
    day: tonumber time\sub 9, 10
    hour: tonumber time\sub 12, 13
    min: tonumber time\sub 15, 16
    sec: tonumber time\sub 18, 19
  }

  return os.time tab
```

Edit: I'm also not 100% sure that's correct, or if it can be fucked up by DST settings or something. I don't think it can, but I'm also not sure how to verify it.

**Comment by leafo** [comment]
I use the [date](https://luarocks.org/modules/tieske/date) library to parse dates coming back from the db:

```lua
local date = require "date"
date_obj = date(mydate)
```

**Comment by Guard13007** [comment]
Is there any reason you'd be against having this as a native of Lapis? I understand how you're handling it, but for someone who wants to avoid dependencies, it'd be nice to have this as it is such a basic piece.

(Mainly curious at this point, since I've solved it acceptably for myself already.)

**Comment by leafo** [comment]
`date` is already a dependency of lapis, it's the recommended approach 

Your function also doesn't handle timezones, and would silently ignore them

**Comment by Guard13007** [comment]
Ah, didn't realize that. Why not include your implementation as a function in Lapis?
