### ISSUE TITLE
json_params doesn't parse arrays correctly?

### ISSUE THREAD

**Issue by Guard13007** [leafo/lapis#563]
I set up a quick recursive print to test what comes it through json_params, and I expected arrays to be parsed into tables...seems only the last item gets sent to a `""` key value?

![image](https://user-images.githubusercontent.com/15093567/28839962-32d4bf70-76aa-11e7-8eb4-7336678f5fb0.png)

**Comment by Guard13007** [comment]
Seems to work fine with explicitly numbered values in an object:

![image](https://user-images.githubusercontent.com/15093567/28840641-7cedaffc-76ac-11e7-8f64-9d56efade854.png)

**Comment by Guard13007** [comment]
After that test with explicitly numbered values, it again started failing even with that. I have no idea where to begin to figure this one out..

**Comment by leafo** [comment]
Are you sure you're sending the data as JSON? Looks like you're letting jquery form encode from what I can see. the form decoder doesn't work with arrays right now

**Comment by Guard13007** [comment]
I thought the data was being encoded as JSON but I'll double check that,
and I am using json_params to decode on the server.

Again, I'll double check and report back with confirmation.

**Comment by leafo** [comment]
Going to close this, open again if you reproduce the issue
