### ISSUE TITLE
column "id" does not exist on Model:create

### ISSUE THREAD

**Issue by VaiN474** [leafo/lapis#567]
I have a postgres database table that does not have an "id" column. When trying to use Model:create, I get the following error:

```
...postgres.lua:82: INSERT INTO ... RETURNING "id"
ERROR: column "id" does not exist (155)
```

I have a different column that is unique, and the primary key, that I would like to return instead. The documentation suggests that Model:create returns the primary keys on creation, but it only seems to look for "id". Docs also suggest that you can use a second table to specify the columns to return, but there's no example usage, and I wasn't able to figure it out.

Any advice would be appreciated.

**Comment by leafo** [comment]
You have to specify the primary keys: http://leafo.net/lapis/reference/models.html#primary-keys

**Comment by VaiN474** [comment]
Ah, and there it is. Thank you so much. Sorry I overlooked that.  :)
