### ISSUE TITLE
Can I use multi database in one website?

### ISSUE THREAD

**Issue by uudiin** [leafo/lapis#569]
My website's data is stored in multi database, How to config it in config.lua?
Thanks.

**Comment by leafo** [comment]
At the moment lapis as a single global db connection, but it should be possible to replace the db connection on a per model basis. Every model has a reference to the `db` object stored on the class then you can swap out. You would be responsible for creating the connection, and closing it at the end of a request though.

In the future lapis should provide an easy way to do this.

**Comment by uudiin** [comment]
Thanks a lot.
