### ISSUE TITLE
Best way to do ratelimit

### ISSUE THREAD

**Issue by kraftman** [leafo/lapis#570]
Hey, I'm looking at adding some basic per user/endpoint rate limiting to my application, using the session  cookie to identify each client. What's the best way to do this? Can I load up the app and run some checks in access_by_lua?

**Comment by tst2005** [comment]
Hello,
take a look at https://github.com/timebug/lua-resty-limit-req
it seems what you need.
I supposed (not tested) you could replace the key (usualy the IP) by a session identifier to check the rate.

Regards

**Comment by kraftman** [comment]
Cheers, I took a look at that but the problem is the session cookie is encrypted so I'd need to load up the whole app just to retrieve the session ID to use for ratelimiting. I might try storing some other unique ID in a normal unencrypted cookie so that I can do a fast check in access_by lua without having to require lapis.

**Comment by leafo** [comment]
I use the nginx rate limiting module when I don't need any access to lapis (database, session, etc.): http://nginx.org/en/docs/http/ngx_http_limit_req_module.html
