### ISSUE TITLE
Documentation for database types not up to date?

### ISSUE THREAD

**Issue by Guard13007** [leafo/lapis#572]
[Migrating for a New Polymorphic Relation](http://leafo.net/lapis/reference/models.html#relations/polymorphic-belongs-to/migrating-for-a-new-polymorphic-relation) has an example using `types.enum` as a column type in migrations, but [Column Types](http://leafo.net/lapis/reference/database.html#database-schemas/column-types) does not show an `enum` type.

**Comment by leafo** [comment]
This has been added to docs, docs haven't been redeployed yet.

**Comment by leafo** [comment]
docs have been redeployed.
