### ISSUE TITLE
How to handle errors across all routes?

### ISSUE THREAD

**Issue by kraftman** [leafo/lapis#574]
I'm currently converting my app to use the built in exception handling, but since capture_errors returns {render = true} by default, I either need to make sure I have a view for every route (which I don't always have, and each one would need its own code to handle errors), or I need to add a custom error handler to every capture_requests call.

Is there a clever way of just using a single error handler for any and all errors that happen? I tried catching errors in my layout, but that only works if the template exists.

**Comment by lasfter** [comment]
I'm not sure I understand exactly what you're asking. Do you want to render the same error page for 500 errors as for ["recoverable" errors](http://leafo.net/lapis/reference/exception_handling.html#capturing-recoverable-errors), as the docs call them?

If so, just wrap capture errors so that it always does the same thing in its on_error callback.
```lua
local function handle_error(self, err, trace)
    self.err = err
    self.trace = trace
    return { status = 500, render = "my_error_page" }
end
-- unrecoverable errors
app.handle_error = handle_error

-- recoverable errors
local lapis_capture_errors = require "lapis.application".capture_errors
local function capture_errors(fn)
    return lapis_capture_errors {
        on_error = function(self)
            -- what you do here depends on your error page/how much info you need
            -- this is just an idea. Passes the error you yielded but no traceback to your error page
            return handle_error(self, self.errors[1], "")
        end,
        fn
    }
end

-- both call the same error page
app:get("/recoverable", capture_errors(function()
    require "lapis.application".yield_error "uh oh"
end))
app:get("/unrecoverable", function() 
    return 1 / 0
end)
```

**Comment by leafo** [comment]
I recommend creating a helper function and overriding the `on_error` handler for `capture_errors`. There's an example of providing a custom error handler here: http://leafo.net/lapis/reference/exception_handling.html#capturing-recoverable-errors
