### ISSUE TITLE
MySQL migration requires ngx

### ISSUE THREAD

**Issue by tpimh** [leafo/lapis#578]
Running `lapis migrate --trace`:

    /usr/local/openresty/luajit/bin/luajit: /usr/local/openresty/luajit/share/lua/5.1/resty/mysql.lua:5: attempt to index global 'ngx' (a nil value)
    stack traceback:
	    /usr/local/openresty/luajit/share/lua/5.1/resty/mysql.lua:5: in main chunk
	    [C]: in function 'require'
	    .../local/openresty/luajit/share/lua/5.1/lapis/db/mysql.lua:101: in function 'backend'
	    .../local/openresty/luajit/share/lua/5.1/lapis/db/mysql.lua:164: in function 'connect'
	    .../local/openresty/luajit/share/lua/5.1/lapis/db/mysql.lua:183: in function 'escape_literal'
	    ...openresty/luajit/share/lua/5.1/lapis/db/mysql/schema.lua:48: in function 'entity_exists'
	    ...l/openresty/luajit/share/lua/5.1/lapis/db/migrations.lua:73: in function 'run_migrations'
	    ...cal/openresty/luajit/share/lua/5.1/lapis/cmd/actions.lua:282: in function 'execute'
	    /usr/local/openresty/luajit/bin/lapis:4: in main chunk
	    [C]: at 0x5610cbc85360

My `config.lua`:

    config = require "lapis.config"

    config("development", {
      port = 8080,
      mysql = {
        backend = "resty_mysql",
        path = "/var/run/mysqld/mysqld.sock",
        database = "test",
        user = "test",
        password = "test"
      },
      redis = {
        path = "/var/run/redis/redis.sock"
      }
    })

My `migrations.lua`:

    local schema = require("lapis.db.schema")
    local types = schema.types

    return {
      [1] = function()
        schema.create_table("things", {
          { "id", types.id },
          { "name", types.varchar }
        })
        schema.create_table("users", {
          { "id", types.id },
          { "username", types.varchar },
          { "password", types.varchar }
        })
      end
    }

Am I doing something wrong?

**Comment by leafo** [comment]
if you're forcing the `resty_mysql` backend then the database connection needs ngx to initialize. Are you able to leave out `backend` in the config? Alternatively you can try `resty-cli` to run the migrations.

**Comment by leafo** [comment]
`lapis exec` should work too, it's effectively the same thing as `nginx-cli`

Try running this: 

```
lapis exec 'require("lapis.db.migrations").run_migrations(require("migrations"))'
```

If that works for you then maybe it would be a good idea to add a flag to the `lapis migrations` command that runs it on the server

**Comment by tpimh** [comment]
The code did run, but no successfully:

```
/usr/local/openresty/luajit/bin/luajit: ...luajit/share/lua/5.1/lapis/cmd/nginx/attached_server.lua:71: Failed to exec code on server, got: 500

SQL: SELECT COUNT(*) as c from information_schema.tables where
    table_schema = 'test' and table_name = 'lapis_migrations' LIMIT 1
...openresty/luajit/share/lua/5.1/lapis/db/mysql/schema.lua:51: attempt to compare number with string
stack traceback:
	[C]: in function 'error'
	...luajit/share/lua/5.1/lapis/cmd/nginx/attached_server.lua:71: in function 'exec'
	...cal/openresty/luajit/share/lua/5.1/lapis/cmd/actions.lua:265: in function 'execute'
	/usr/local/openresty/luajit/bin/lapis:4: in main chunk
	[C]: at 0x563aff68d360
```

**Comment by leafo** [comment]
It looks like the mysql driver is returning a string type in place of a number. I put a quick patch in master, do you want to test it? You can install lapis master branch using luarocks like this:

```
luarocks install https://luarocks.org/manifests/leafo/lapis-dev-1.rockspec
```

(using whatever flags you used to originally install it, `--local` or `--tree`)

**Comment by tpimh** [comment]
Thank you! Now it works.
