### ISSUE TITLE
Lapis test: Don't know if this is correct and how to test in this case

### ISSUE THREAD

**Issue by CodelessFuture** [leafo/lapis#581]
Lapis test:
--- 
The function has three return values: the status code as a number, the body of the response and any response headers in a table.
---
But if I have a redirect (eg. after a valid login) the body is empy......so I cannot match on a text on the redirected page

**Comment by leafo** [comment]
If you get a redirect then you're responsible for making the next request.

So for example, you might get the following return values from the request:

```
302, "", { Location = "https://next-url", ... }
```

You can then take `headers.Location` and make a new request with that URL to get the response.

There are no plans at this time for automatically following redirect, since it's common for specs to test if a redirect happened.

**Comment by CodelessFuture** [comment]
Thank you for your fast response

**Comment by leafo** [comment]
:+1: Open again if you have any issues

**Comment by CodelessFuture** [comment]
I need your help because I did something wrong: 
After your reply I write a second part of the test and a new one. Both failed with body empty (but the app works well). The first redirect is correct (goes to the dashboard after login).
The second redirect to homepage as the session was empty and no user authenticated.
Here I post the code if you can explain what I do wrong:
`local lapis = require("lapis.application")
local request = require("lapis.spec.server").request
local use_test_server = require("lapis.spec").use_test_server
local app = lapis.Application()

local options = {}

describe("Golfcoupon", function()
  use_test_server()

  it("should load homepage if I visit /", function()
    local status, body, headers = request("/")
    assert.same(200, status)
  end)

  it("should redirect to homepage if I visit /dashboard", function()
    local status, body, headers = request("/dashboard")
    assert.same(302, status)
  end)

  it("should load login page if I visit /login", function()
    local status, body, headers = request("/login")
    assert.same(200, status)
  end)

  it("should not login someone if it visit /login and send incorrect credential", function()
    options = {}
    options["post"] = { email = "massimiliano@codelessfuture.com", password="Foobar" }
    local status, body, headers = request("/login", options)
    assert.truthy(body:match("Nome utente o password errati"))
  end)

  it("should login an admin if it visit /login and send correct credential", function()
    options = {}
    options["post"] = { email = "massimiliano@codelessfuture.com", password="Saknussemm73!" }
    local status, body, headers = request("/login", options)
    assert.same(302, status)
    print(headers.Location)
    local status, body, headers = request(headers.Location)
    assert.truthy(body:match("Benvenuto Massimiliano"))
  end)

  it("after the redirect you see a welcome message in the dashboard", function()
    local status, body, headers = request("/dashboard")
    print(headers.Location)
    assert.truthy(body:match("Benvenuto Massimiliano"))
  end)

end)`

**Comment by CodelessFuture** [comment]
I done this:
```
 it("should login and redirect to dashboard an admin if it visit /login and send correct credential", function()
    options = {}
    options["post"] = { email = "massimiliano@codelessfuture.com", password="Saknussemm73!" }
    local status, body, headers = request("/login", options)
    assert.same(302, status)
    assert.truthy(string.match(headers.Location, "http://127.0.0.1/dashboard"))
  end)
```

**Comment by leafo** [comment]
there is no state kept between the requests, so if you need to bring a session  over you need  to read the output of `set-cookie` header on the first request, and insert a `cookie` header on the next request
