### ISSUE TITLE
Api and Web route

### ISSUE THREAD

**Issue by CodelessFuture** [leafo/lapis#582]
I have 2 distinct route in my web app. The first is a web backend for admin and CRUD operation, the second is the API talking with a Mobile app.

The first need session, cookies and views, the second jwt token and son response.

Actually I made this in Nginx.conf and it works (but I'm open to suggestion and better practices):

```
....
server {
    listen ${{PORT}};
    lua_code_cache ${{CODE_CACHE}};

    location / {
      default_type text/html;
      content_by_lua '
        require("lapis").serve("app")
      ';
    }
	
	location /api {
      default_type text/html;
      content_by_lua '
        require("lapis").serve("api")
      ';
    }
....
```

So I have an app.lua and an api.lua and works well, but I have to put /api in all route: there's a method to have automatically /api appended to the route in api.lua?

```lua
-- now:
api:post("/api/seed" , function()
........

-- then:
api:post("/seed" , function()

but always pointing to: /api/lua
```

**Comment by leafo** [comment]
Although this will work, it's not what I do. I have one `/` location in nginx that points to a lapis application that holds  all the routes. This is so I can use `url_for` to generate routes to resources on the web side of things. If you have two separate applications then they aren't aware of the routes on the other.

I still recommend splitting your application routes across multiple files though. You can do something like this:


```lua
-- app.lua
package.loaded.app = lapis.Application()
require("applications.api")
require("applications.web")
```

```lua
-- applications/api.lua
local app = require("app")

app:post("/hello", function() end)
```

```lua
-- application/web.lua
local app = require("app")

app:post("/world", function() end)
```

**Comment by leafo** [comment]
Also for handing the prefixing of routes, I recommend using a decorator pattern:


```lua
local function api_request(path, fn)
   -- you can do other stuff here like wrap `fn` to do additional checking
   return "/api" .. path, fn
end
--- ...
app:post(api_request("/hello", function() end))
```

**Comment by CodelessFuture** [comment]
> I still recommend splitting your application routes across multiple files though. You can do something like this:
> 
> -- app.lua
> package.loaded.app = lapis.Application()
> require("applications.api")
> require("applications.web")
> -- applications/api.lua
> local app = require("app")
> 
> app:post("/hello", function() end)
> -- application/web.lua
> local app = require("app")
> 
> app:post("/world", function() end)

thanks also this I was looking for and it would be the next question!

**Comment by CodelessFuture** [comment]
I think the I split my web apps in many files (as a sort of "controllers"), but I think that for the api I take the situation as I have done so far, because have set a before_filter for session and cookie in app and a before_filter for tokens for api. It is also good for me to have separation of concerns because the webapp and the api share only database data
