### ISSUE TITLE
File uploads validation

### ISSUE THREAD

**Issue by CodelessFuture** [leafo/lapis#585]
Hi.

I need to validate if the field is a file upload but only if present (it is not a required field)

I'm using  
```lua
validate.assert_valid(self.params, {
   ...
   { "logo", is_file = true },
   ....
})
```

But so it is required always giving a "Missing file" error

Also what's the difference with _file_exists = true_ ?

Also I need an optional validation for other field, so the file can be present or not, but if present can have only min 8 max 10 char......and so on.

**Comment by CodelessFuture** [comment]
Also if you prefer to not have issue open for question like this there is another place to post and receive answer?

**Comment by CodelessFuture** [comment]
Reading validation.lua I find this:

    ```
...lua
  if v.optional then
        if not (validate_functions.exists(input)) then
          _continue_0 = true
          break
        end
      end
...
```

So I can set **_optional = true_** for what I need?

**Comment by CodelessFuture** [comment]
Ok, after a couple of test I see I have a validation optional: true that do exactly what I need, but don't work with file upload field.

**Comment by leafo** [comment]
Thanks, didn't realize docs were missing for that part of validation. I've added them

**Comment by CodelessFuture** [comment]
Remember to put online the docs so that anyone using Lapis can use this important feature of validation

**Comment by CodelessFuture** [comment]
Update docs on website is possible?

**Comment by ricardoG08** [comment]
@leafo `is_file` not function with `optional`validation
