### ISSUE TITLE
failed to find model `model` for relation

### ISSUE THREAD

**Issue by CodelessFuture** [leafo/lapis#586]
failed to find model `Golfclubs` for relation

This is my models.lua:
```lua
local autoload = require("lapis.util").autoload
return autoload("models")
```

This are the relations:
```lua
local Model = require("lapis.db.model").Model
local Golfclubs = Model:extend("golfclubs", {
  relations = {
    {"coupons", has_many = "Coupons"}
  }
})
local Coupons = Model:extend("coupons", {
  relations = {
    {"golfclub", belongs_to = "Golfclubs"}
  }
})
```

This are the migrations:
```lua
    schema.create_table("golfclubs", {
      { "id", types.serial },
      { "name", types.text },
      { "logo", types.text({ null = true }) },
      { "description", types.text },
      { "image", types.text({ null = true }) },
      { "address", types.text },
      { "latitude", types.text({ null = true }) },
      { "longitude", types.text({ null = true }) },
      { "phone", types.text({ null = true }) },
      { "email", types.text({ null = true }) },

      "PRIMARY KEY (id)"
    })

    schema.create_table("coupons", {
      { "id", types.serial },
      { "name", types.text },
      { "description", types.text },
      { "condition", types.text },
      { "quantity", types.integer({ default = 1}) },
      { "golfclub_id", types.foreign_key },

      "PRIMARY KEY (id)"
    })
```

**Comment by CodelessFuture** [comment]
Figured by myself (again with source because docs are missing)

**Comment by chelog** [comment]
@CodelessFuture can you elaborate a little? I spent around 2 hours and still can't figure it out, I have approximately the same setup as you described.

**Comment by CodelessFuture** [comment]
I have to create a models subdirectory with a file named as the table for example coupons.lua containing the code

**Comment by CodelessFuture** [comment]
I have to create a models subdirectory with a file named as the table for example coupons.lua containing the code 

----
--
-- Coupons model
--
----
local Model = require("lapis.db.model").Model

local Coupons = Model:extend("coupons", {
  relations = {
    {"golfclub", belongs_to = "Golfclubs"}
  }
})

return Coupons

**Comment by chelog** [comment]
Thank you. Actually you replied just the moment I found the example of [luarocks site](https://github.com/luarocks/luarocks-site/), but it's in moonscript and I'm using lua for Lapis. Do you have any examples of how full-featured app could look like in lua?

**Comment by leafo** [comment]
When you reference a relation by name the class method `get_relation_model` on the model is called to retrieve it.

The default implementation looks like this:

```lua
function Model:get_relation_model(name)
  return requrie("models")[name]
end
```

This means that you need to have a module called `models` that contains references to all of your models in a table indexed by name. You can use `autoload` to help you automatically split all your models across directories: http://leafo.net/lapis/reference/utilities.html#functions/autoload

When using autoload to load your models from a `models/` directory your `models.lua` file would look like this: 

```lua
-- models.lua
return require("lapis.util").autoload("models")
```

**Comment by chelog** [comment]
@leafo thank you a lot. But still, any examples of working apps like luarocks but in lua? It'd be a great help for me to fully understand the framework.

**Comment by leafo** [comment]
@chelog 

Both of these projects are written with lapis in lua:

https://github.com/starius/pasta
https://github.com/karai17/lapis-chan/

I haven't reviewed their code though so I can't guarantee best practices, but it should give you an idea. Generally lapis is pretty free about how you organize things, since everything is just loaded by lua module name, and you can configure those modules are resolved.

**Comment by chelog** [comment]
Someone give @leafo a cookie! Thank you, I really love Lapis and I'm spending 7th night after work in a row to play with it. I already created a pretty static (website)[http://www.octothorp.team/] and a couple of simple apps for my gaming community but want to go deeper. Thank you a lot for this powerful tool and this info!
