### ISSUE TITLE
How can I insert multi value to postgresql at a time?

### ISSUE THREAD

**Issue by uudiin** [leafo/lapis#590]
Cound I insert multi value to db at a time? 

`INSERT INTO "my_table" ("age", "name") VALUES (10, 'Hello World'), (22, 'Hello')`

Is lapis supported?
Thanks a lot

**Comment by leafo** [comment]
Sure, you can use `db.query` to construct the query. The `db.insert` function does not support that.

**Comment by uudiin** [comment]
Thanks
