### ISSUE TITLE
How to change the types.varchar length?

### ISSUE THREAD

**Issue by uudiin** [leafo/lapis#591]
I use the varchar with length 4096, alse as a primary key

`types.varchar(4096, { primary_key = true })`

A runtime error occured. How to fix it?
Thanks.

**Comment by leafo** [comment]
There currently isn't a type constructor for a varchar of a custom length. You can, however, just put a string in place of the type constructor to use that as the type:

```lua
schema.create_table({
  {"my_column", "character varying(255) primary key"}
})
````
