### ISSUE TITLE
Is it possible to obtain status code in a view?

### ISSUE THREAD

**Issue by tpimh** [leafo/lapis#593]
I was trying to print it as `<%= ngx.status %>` and `<%= ngx.var.status %>`, but it didn't work. The only way I get it to work is saving status code before setting it to a variable and then printing it's value. Is there a better way?

**Comment by leafo** [comment]
Sorry about the delay. The status code is not set until all the views are rendered. This means that you'll have to store your status code in your own variable to reference during view loading. (The status code you pass to render options is not made available)
