### ISSUE TITLE
No library CRYPTO

### ISSUE THREAD

**Issue by Pancakeddd** [leafo/lapis#595]
`nathanmoosh@nathanmoosh-GL702VSK:~$ luarocks install lapis
Installing https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/lapis-1.6.0-1.src.rock...
Using https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/lapis-1.6.0-1.src.rock... switching to 'build' mode

Missing dependencies for lapis:
luaossl 
loadkit 
mimetypes 
ansicolors 
date 
pgmoon 
etlua 

Using https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/luaossl-20171028-0.src.rock... switching to 'build' mode

Error: Failed installing dependency: https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/luaossl-20171028-0.src.rock - Could not find library file for CRYPTO
  No file libcrypto.a in /usr/lib
  No file libcrypto.so in /usr/lib
  No file matching libcrypto.so.* in /usr/lib
You may have to install CRYPTO in your system and/or pass CRYPTO_DIR or CRYPTO_LIBDIR to the luarocks command.
Example: luarocks install luaossl CRYPTO_DIR=/usr/local
`

Please help!

**Comment by leafo** [comment]
Do you have openssl installed? 

Here's the documentation for the dependency that is failing to install:
http://25thandclement.com/~william/projects/luaossl.html

**Comment by toopay** [comment]
On xenial, we can have `openssl` installed but still throw that error. Need to install `libssl-dev` in that case.
