### ISSUE TITLE
Parameter parser can crash

### ISSUE THREAD

**Issue by bungle** [leafo/lapis#598]
One problem is here:
https://github.com/bungle/lapis/blob/master/lapis/request.lua#L303

It is not guaranteed that the `curr`is a table. Also here is small example:
https://itch.io/?p[0]=4

**Comment by leafo** [comment]
Do you get an error on that itch.io url? I don't

**Comment by bungle** [comment]
yes, but not anymore. When I hit with this bug, I think I tried to send parameters like:
`path[]=1&path[]=2&path[1]=3`

and with some combination I think that `curr` went to string.

**Comment by bungle** [comment]
Here is one that crash, using httpie on cli:

```
http https://itch.io p=a p=b p[1]=b -f -v
```

**Comment by leafo** [comment]
Thanks for the detailed reproduction, fixed now
