### ISSUE TITLE
Possible Dependency Issues?

### ISSUE THREAD

**Issue by RickCarlino** [leafo/lapis#6]
I did a fresh install of Lua, Moonscript and Lapis on a new box running Linux and got errors when I first attempted to run 'lua help'. The first errors were fixed by installing lua-cjson and the second was fixed after I installed the lpeg luarock. This is the current error I get:

moon: /usr/local/share/lua/5.1/lapis/util/encoding.lua:20: module 'crypto' not found:No LuaRocks module found for crypto
        no field package.preload['crypto']
        no file '/usr/local/share/lua/5.1/crypto.lua'
        no file '/usr/local/share/lua/5.1/crypto/init.lua'
        no file '/home/rick/.luarocks/share/lua/5.1/crypto.lua'
        no file '/home/rick/.luarocks/share/lua/5.1/crypto/init.lua'
        no file '/usr/local/share/lua/5.2/crypto.lua'
        no file '/usr/local/share/lua/5.2/crypto/init.lua'
        no file '/home/rick/.luarocks/share/lua/5.2/crypto.lua'
        no file '/home/rick/.luarocks/share/lua/5.2/crypto/init.lua'
        no file '/usr/local/share/lua/5.2//crypto.lua'
        no file '/usr/local/share/lua/5.2//crypto/init.lua'
        no file '/usr/local/share/lua/5.2/crypto.lua'
        no file '/usr/local/share/lua/5.2/crypto/init.lua'
        no file '/usr/local/lib/lua/5.2/crypto.lua'
        no file '/usr/local/lib/lua/5.2/crypto/init.lua'
        no file './crypto.lua'
        no file '/usr/local/lib/lua/5.1/crypto.so'
        no file '/home/rick/.luarocks/lib/lua/5.1/crypto.so'
        no file '/usr/local/lib/lua/5.2/crypto.so'
        no file '/home/rick/.luarocks/lib/lua/5.2/crypto.so'
        no file '/usr/local/lib/lua/5.2/crypto.so'
        no file '/usr/local/lib/lua/5.2/loadall.so'
        no file './crypto.so'
stack traceback:
        [C]: in function 'require'
        /usr/local/share/lua/5.1/lapis/util/encoding.lua:20: in main chunk
        [C]: in function 'require'
        /usr/local/share/lua/5.1/lapis/session.lua:4: in main chunk
        [C]: in function 'require'
        /usr/local/share/lua/5.1/lapis/application.lua:3: in main chunk
        [C]: in function 'require'
        /usr/local/share/lua/5.1/lapis/init.lua:2: in main chunk
        [C]: in function 'require'
        web.moon:1(1): in main chunk

**Comment by mathieujobin** [comment]
luacrypto fails to compile...
```
luarocks install luacrypto --local
...
src/lcrypto.c: In function ‘luaopen_crypto’:
src/lcrypto.c:1901:19: error: array type has incomplete element type ‘struct luaL_reg’
   struct luaL_reg core[] = {
                   ^

Error: Build error: Failed compiling object src/lcrypto.o
```

**Comment by starius** [comment]
Try the following command:
```
$ luarocks install luacrypto 0.3.2-1 --local
```

See https://github.com/yagop/telegram-bot/issues/241

**Comment by mathieujobin** [comment]
thanks, but it looks like it could not be found...
```
bash$ luarocks install luacrypto 0.3.2-1 --local

Error: No results matching query were found.

bash$ luarocks search luacrypto

Search results:
===============


Rockspecs and source rocks:
---------------------------

luacrypto
   0.3.0.20120524-1 (rockspec) - https://luarocks.org
   0.3.0.20120524-1 (src) - https://luarocks.org
   0.2.0-2 (rockspec) - https://luarocks.org
   0.2.0-2 (src) - https://luarocks.org
   0.2.0-1 (rockspec) - https://luarocks.org
   0.2.0-1 (src) - https://luarocks.org

bash$
```

I tried the other available version but I am getting same compilation error.

```
src/lcrypto.c: In function ‘luaopen_crypto’:
src/lcrypto.c:503:19: error: array type has incomplete element type ‘struct
luaL_reg’
   struct luaL_reg core[] = {
                   ^

```

**Comment by starius** [comment]
[The official rockspec](https://luarocks.org/manifests/luarocks/luacrypto-0.3.2-1.rockspec) for luacrypto has the following Lua version line:
```lua
dependencies = {
        "lua >= 5.1, < 5.3",
}
```
That is why luarocks doesn't list this version for Lua 5.3.

I have [fixed](https://github.com/starius/luacrypto/commit/ab1caf241876466e928a5ccb7a99cfef81387730) incompatibilities with Lua 5.3 this issue in [my fork of luacrypto](https://github.com/starius/luacrypto) and uploaded [modified rockspec](https://gist.githubusercontent.com/starius/b20d3e63929ae678c857/raw/4b4499f442337b6f577422364358590bd00c9d48/luacrypto-0.3.2-2.rockspec) to gist.

The following command installs luacrypto from my fork. It should work for Lua 5.3.

```
$ luarocks install https://gist.githubusercontent.com/starius/b20d3e63929ae678c857/raw/4b4499f442337b6f577422364358590bd00c9d48/luacrypto-0.3.2-2.rockspec --local
```

You can use this workaround until this issue is fixed in [the upstream](https://github.com/mkottman/luacrypto).

**Comment by mathieujobin** [comment]
Thanks very much

**Comment by Guard13007** [comment]
Not sure if related, but same error message about missing `crypto` library that I'm talking about on #560..

**Comment by leafo** [comment]
@Guard13007 there is no longer a reference to the crypto module in the lapis codebase.

* Are you sure you're using the latest version
* Are you sure the error isn't from another dependency?

If you can give me the stack trace then I can tell you what's going on

**Comment by Guard13007** [comment]
Note: Forgot to verify lapis version, but it should be latest as it's on a fresh server with fresh luarocks install using `sudo luarocks install lapis`. I will confirm the version number in a few minutes after fixing a script of my own.

**Comment by Guard13007** [comment]
Lapis version 1.7.0
