### ISSUE TITLE
Try and serve page, and if it fails display the error page ?

### ISSUE THREAD

**Issue by Yarillo4** [leafo/lapis#600]
EDIT: 600th issue ! \o/

Hello, I have a code snippet for you

Basically what I do is I have a route for "/projects/:name" which serves "views.projects." .. self.params.name

If I try to access a view that doesn't exist I'd like to catch that exception and render the "error" page.

Unfortunately I can't use pcall for this as I'm not the one calling the "render" function. Lapis does.

Sooo... am I missing something ? How do I do that ?

Basically i'm only getting the default traceback instead of my error page (or a regular page if I hit a view that exists).

![img](https://i.imgur.com/xzifgoo.png)

```LUA
local lapis = require "lapis"
local lfs = require "lfs"
local app_helpers = require "lapis.application"
local capture_errors, yield_error = app_helpers.capture_errors, app_helpers.yield_error

local app = lapis.Application()

app:enable("etlua")
app.layout = require "views.layout"


local function notfound(self)
	self.pageTitle = "404"
	self.status    =  404
	return { 
		render = "error", --my error page
		status = 404
	} 
end

app:match("/*", notfound)

---------------------------------------------------------------------------
-- Relevant code                                                         --
-- Exception handling doesn't work properly or I misunderstood something --
-- (probably the latter)                                                 --
---------------------------------------------------------------------------
app:match("/projects/:name", capture_errors(
{
	on_error = notfound,
	function(self)
		self.pageTitle = self.params.name
		return { render = "projects." .. self.params.name}
	end
}
))

return app
```

**Comment by leafo** [comment]
I don't recommend loading files off disk based on a user specified param without some sort of whitelist.

In any case, to make what you want work, you need to check to see if that modules exists before trying to render it:

```lua
local exists = pcall(function() require("views.projects".. self.params.name) end)

**Comment by nargyriou** [comment]
Thanks !
