### ISSUE TITLE
Is there a way to modify the URL before it gets matched to a route?

### ISSUE THREAD

**Issue by Guard13007** [leafo/lapis#601]
I have a splat capturing anything that doesn't match another route, which means I can't use the [default_route](http://leafo.net/lapis/reference/actions.html#application-callbacks/default-action), but I want to use the logic to strip trailing `/`'s.

I figure the easiest way to fix this would just be to strip these before matching against routes, since I will never be using a trailing slash anyhow. How would I go about accomplishing this?

Alternately, is there a way I can check if a URL matches against a route elsewhere? I can make my splat check for an existing route after stripping the trailing slash, and redirect, or just go to a 404.

**Comment by leafo** [comment]
You can override the `dispatch` method on the app and do whatever you want to the request object (first argument) before calling super.

Alternatively, if you always want to remove trailing slash you can make a match in your nginx config

**Comment by Guard13007** [comment]
I will always be removing them, so looks like the nginx directive is the way to go. Thanks!
