### ISSUE TITLE
Autoload is failing strangely?

### ISSUE THREAD

**Issue by Guard13007** [leafo/lapis#602]
I have one file that returns a table of Models, and I have modified the default `models.moon` to use a second argument to `autoload` with a require of said file, and *one* of the two Models defined there is successfully accessible, but the other one disappears entirely.

I've tried to replicate the issue with a minimal application, but have not had success. I can require the file that returns a table of Models and access them correctly. I can require them individually, and it works correctly. I can verify everything is functioning correctly EXCEPT requiring `models` and accessing ***one*** of the two Models defined in this other file.

Of course, the whole reason I'm doing things in this convoluted way is because I'm trying to split out some of a site's functionality into a sub-application that defines its own models locally to it, yet have them accessible from elsewhere under the same models path as everything else. Maybe I just shouldn't do it this way.

(Would you be interested in seeing the minimal version that still works correctly? I figured there wasn't a point in sharing it since it doesn't show anything wrong, but maybe it alludes to a flaw in my thinking?)

**Comment by leafo** [comment]
Are you sure that model that can't be loaded is available in the initialization table you pass to `autoload`?

What happens if you dump the contents of table from `models.moon`, you should see everything in there that is already loaded.

**Comment by Guard13007** [comment]
Yes I am, because I can require it separately (the same way it was being
required before being passed to autoload).

I've been using lapis-console to verify things, and can dump the
initialization table showing both models, and dump the autoloaded table,
which shows many models successfully autoloaded from the main models
directory, and only one of the two from the other.

For now, as I can't reproduce in a minimal form, I've refactored the way o
approach these models to avoid the issue. If I have time later today, I
might try a minimal test case bearing more similarity to the project.

On Feb 1, 2018 1:32 PM, "leaf" <notifications@github.com> wrote:

Are you sure that model that can't be loaded is available in the
initialization table you pass to autoload?

What happens if you dump the contents of table from models.moon, you should
see everything in there that is already loaded.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/leafo/lapis/issues/602#issuecomment-362408574>, or mute
the thread

**Comment by leafo** [comment]
I'm going to close this, feel free to post again if you figure anything out.
