### ISSUE TITLE
[bug] encode_query_string does not encode ampersands

### ISSUE THREAD

**Issue by Guard13007** [leafo/lapis#605]
Ampersands should be encoded into `&amp;` within HTML attributes, which is where I assume the output of encode_query_string is intended to be used / most often used.

**Comment by leafo** [comment]
`encode_query_string` isn't for escaping HTML, so it doesn't generate HTML entities:

```moonscript
import encode_query_string from require "lapis.util"
print encode_query_string {
  "hel&lo": "world&thing"
}
```
```
hel%26lo=world%26thing
```

Where are you running into an issue with ampersands and html?

```moon
import escape from require "lapis.html"
print escape "one & two"
```
```
one &amp; two
```

**Comment by Guard13007** [comment]
I'm just assuming its primary purpose is for use in generating URLs, which are commonly used in `<a href=""></a>`, and since ampersands should be escaped in attributes, that it's a bug. I should be handling this myself.

**Comment by leafo** [comment]
I recommend using a templating language that escapes by default, if not you may be vulnerable to cross site scripting. lapis' html views and etlua have escaping by default.
