### ISSUE TITLE
cqueue support

### ISSUE THREAD

**Issue by CodelessFuture** [leafo/lapis#607]
Hi,

I'm interested in queue http-lua support.

This let Lapis be compatible be compatible with Lua 5.3? Are you planning to update on Luarocks?

**Comment by leafo** [comment]
It's only been tested with luajit, but it should be possible to be compatible with greater versions of lua now. The test suite is hard coded to work with luajit & openresty right now. Postgres is the only db backend that is going to support cqueues as well.

**Comment by rise-cons** [comment]
I'm actually using Lapis with Lua 5.4 and http / cqueues using Nginx as a rexerse proxy and for serving the static files
