### ISSUE TITLE
Handling request method 'OPTIONS' - best practice (CORS)

### ISSUE THREAD

**Issue by aiibe** [leafo/lapis#610]
This is how my API handles 'POST' requests : 
```
class extends lapis.Application
	[hello:'/api/hello']: respond_to {
		OPTIONS: =>
		 	@res.headers["Access-Control-Allow-Origin"] = "*"
		 	@res.headers["Access-Control-Allow-Headers"] = "Access-Control-Allow-Origin,Content-Type"

		POST: json_params =>
			@res.headers["Access-Control-Allow-Origin"] = "*"
			json: { message: 'hello' }
	}
```
It works fine, but I wonder if this is a good practice (?)

**Comment by aiibe** [comment]
I changed the code above to : 
```
class extends lapis.Application
	[hello:'/api/hello']: respond_to {
		OPTIONS: =>
		POST: json_params =>
			@res.headers["Access-Control-Allow-Origin"] = "*"
			json: { message: 'hello' }
	}
```
and it works too. However I have to put OPTIONS in respond_to, otherwise nothing is returned from the server and a CORS would warning pop in the browser console.

**Comment by leafo** [comment]
This would be the appropriate way to do it. When using respond_to you need to explicitly specify all the methods you support.

If you need to do this for many actions then you can make a wrapper function that wraps an action with the necessary setup
