### ISSUE TITLE
"fetch " data after query mysql 

### ISSUE THREAD

**Issue by VuDn5** [leafo/lapis#611]
Dear @leafo ! 
i have example:  
` 
 function testFunction(arg)
        local res
        res = db.query("select * FROM subscriber  where username =169693")
        local ha1 = res.ha1b
return to_json(ha1)
`

but it return null,  json of variable ** " res" ** is:
[{"username":"169693","ha1b":"2004e0563f67b646abf038626961b6db"}]

My question is, how can i take a ha1b from res variable? Thank you!

**Comment by leafo** [comment]
`db.query` returns an array of results, so you would index the first item, then get the `ha1b` field out of it. Does that answer your question?

**Comment by VuDn5** [comment]
thanks you Sir, it's very simple! ^-^
