### ISSUE TITLE
error: can not detect sig_atomic_t size

### ISSUE THREAD

**Issue by harshkalra** [leafo/lapis#613]
Hi, 
i am trying to setup openresty on a digital ocean server running ubuntu 16.04 LTS.
when i run `./configure -j2 --with-pcre-jit --with-ipv6 ` , i get the following error.

`./configure: error: can not detect sig_atomic_t size`
`ERROR: failed to run command: sh ./configure --prefix=/usr/local/openresty/nginx \...`

how to fix this?
Thanks!

**Comment by leafo** [comment]
This is an issue for openresty, not lapis. Leave a comment if you think it's related to lapis.
