### ISSUE TITLE
Module 'views.index' not found

### ISSUE THREAD

**Issue by daelvn** [leafo/lapis#616]
## Module `views.index` not found
Hello, I have been testing my website and I get an error while trying to render my file `views/index.html`.
I have tried reading [this issue](#199) and [this StackOverflow QA](https://stackoverflow.com/questions/26840933), however, in the issue, it didn't end up being resolved, and in the QA, the accepted question modifies the path to include Lapis itself, and the solution belows puts views in the path.
Below is my directory structure in which I'm starting the server:
```
voyager@neptune:~/diversity$ ls *
app.lua  config.lua  LICENSE.md  mime.types  models.lua  nginx.conf  nginx.conf.compiled  README.md

client_body_temp:

css:
main.css  main.css.map

fastcgi_temp:

logs:
access.log  error.log

proxy_temp:

scgi_temp:

uwsgi_temp:

vendor:
bootstrap  popper.js

views:
index.html  layout_community.etlua  layout_gallery.etlua  layout_hello.etlua  layout_users.etlua
```
And below, my `app.lua` file that should be rendering `views/index.html` with the layout `views/layout_:page.etlua`. I have enabled `etlua` for the application and have set `views` as the `views_prefix` before coming to post here. I have also tried to add a pair of paths to `package.path`
```lua
-- Path
package.path = package.path .. ";./?.lua;./?.etlua"

-- Lapis
local Lapis = require "lapis"

-- Application
local app = Lapis.Application ()
app:enable "etlua"
app.views_prefix = "views"

-- Routing
app:match ("irender", "/irender/:page", function (self)
  local page = self.params.page
  return {
    render = "index",
    layout = "layout_" .. page
  }
end)

-- Return
return app
```
This is the error that Lapis gives me when trying to access `irender/hello`:
```
/usr/local/share/lua/5.1/lapis/request.lua:205: module 'views.index' not found:
	no field package.preload['views.index']could not load `etlua` file
	no file '/usr/local/openresty/site/lualib/views/index.ljbc'
	no file '/usr/local/openresty/site/lualib/views/index/init.ljbc'
	no file '/usr/local/openresty/lualib/views/index.ljbc'
	no file '/usr/local/openresty/lualib/views/index/init.ljbc'
	no file '/usr/local/openresty/site/lualib/views/index.lua'
	no file '/usr/local/openresty/site/lualib/views/index/init.lua'
	no file '/usr/local/openresty/lualib/views/index.lua'
	no file '/usr/local/openresty/lualib/views/index/init.lua'
	no file './views/index.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/views/index.lua'
	no file '/usr/local/share/lua/5.1/views/index.lua'
	no file '/usr/local/share/lua/5.1/views/index/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/views/index.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/views/index/init.lua'
	no file './views/index.lua'
	no file './views/index.etlua'
	no file '/usr/local/openresty/site/lualib/views/index.so'
	no file '/usr/local/openresty/lualib/views/index.so'
	no file './views/index.so'
	no file '/usr/local/lib/lua/5.1/views/index.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/views/index.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/usr/local/openresty/site/lualib/views.so'
	no file '/usr/local/openresty/lualib/views.so'
	no file './views.so'
	no file '/usr/local/lib/lua/5.1/views.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/views.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
```

I am starting the server in the `development` environment, which has the following configuration:
```lua
-- Lapis
local Config = require "lapis.config"

-- Configuration
Config ("development", {
  port         = 8080,
  session_name = "dev_diversity_session"
})
```
And this is the `nginx.conf` for it:
```
worker_processes ${{NUM_WORKERS}};
error_log stderr notice;
daemon off;
pid logs/nginx.pid;

events {
  worker_connections 1024;
}

http {
  include mime.types;

  server {
    listen ${{PORT}};
    lua_code_cache ${{CODE_CACHE}};

    location / {
      default_type text/html;
      content_by_lua '
        require("lapis").serve("app")
      ';
    }

    location /static/ {
      alias static/;
    }

    location /favicon.ico {
      alias static/favicon.ico;
    }
  }
}
```

Any help would be greatly appreciated, please let me know if there is some information missing to be able to figure out the issue, thanks in advance!

**Comment by leafo** [comment]
etlua uses the `.etlua` extension, so in order to lua to load the `views.index` module then a file named `views/index.etlua` must exist. So rename `index.html` to `index.etlua`

```
package.path = package.path .. ";./?.lua;./?.etlua"
```

You shouldn't edit the package path directly, etlua loading is handled by a separate module, [loadkit](https://github.com/leafo/loadkit) which is configured how to understand how to turn etlua sourcode into a lua module. If you add `etlua` to the package path then Lua will try to execute that file as lua and fail.

**Comment by daelvn** [comment]
Thanks! Changing that indeed worked, I thought that as it was a HTML file without any etlua component it would be fine to do that. I'll have that in mind.
