### ISSUE TITLE
"module 'crypto' not found" when running "lapis migrate"

### ISSUE THREAD

**Issue by danieldiekmeier** [leafo/lapis#619]
I'm using a fresh Lapis installation in a Docker container. OpenResty is running, Lapis is returning HTML, everything works.

But then I tried to run migrations, and this happened:

```
$ lapis migrate
Error: module 'crypto' not found:No LuaRocks module found for crypto
	no field package.preload['crypto']
	no file '/root/.luarocks/share/lua/5.1/crypto.lua'
	no file '/root/.luarocks/share/lua/5.1/crypto/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/crypto.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/crypto/init.lua'
	no file './crypto.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/crypto.lua'
	no file '/usr/local/share/lua/5.1/crypto.lua'
	no file '/usr/local/share/lua/5.1/crypto/init.lua'
	no file '/root/.luarocks/lib/lua/5.1/crypto.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/crypto.so'
	no file './crypto.so'
	no file '/usr/local/lib/lua/5.1/crypto.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
 * Run with --trace to see traceback
 * Report issues to https://github.com/leafo/lapis/issues
```

This is probably related to #560, but I opened a new issue because #560 was closed.

I ran `luarocks install luacrypto` and now everything works, but this is probably not the expected behaviour.

**Comment by leafo** [comment]
Can you show the whole trace? luacrypto is not a dependency of lapis anymore so it seems like another library is trying to load it.

**Comment by leafo** [comment]
If you check the stack trace you can see that the crypto module is being loaded in pgmoon:

```
stack traceback:
	[C]: in function 'require'
	/usr/local/openresty/luajit/share/lua/5.1/pgmoon/crypto.lua:6: in main chunk
```

You'll need luacrypto for md5 support for md5 auth in pgmoon. (Although seeing this error, I think patching pgmoon to support both is a good idea)

**Comment by danieldiekmeier** [comment]
Yes, I agree. Do you want me to reopen the issue in your pgmoon repo and close this issue here?

**Comment by mbelicki** [comment]
@ryanford-frontend you can disable the `md5` authentication method in your PostgreSQL configuration. pgmoon will not try load luacrypto unless Postgres server requests `md5` method. The authentication method is defined in `pg_hba.conf`.
