### ISSUE TITLE
Worker segfaults every second request localhost only lapis only wtf

### ISSUE THREAD

**Issue by DarkWiiPlayer** [leafo/lapis#623]
This is probably one of the weirdest problems I have ever experienced with software.

I run lapis behind an openresty reverse proxy, so all outside requests ultimately reach lapis itself from localhost. Now, the weird thing is, every second request, I get `502 bad gateway` and this shows in the 

    2018/05/23 18:39:53 [notice] 3274#3274: signal 17 (SIGCHLD) received from 3275
    2018/05/23 18:39:53 [alert] 3274#3274: worker process 3275 exited on signal 11 (core dumped)
    2018/05/23 18:39:53 [notice] 3274#3274: start worker process 3296

Here's what I have found out:

0. Exactly every second request causes the worker process to segfault
0. This happens with completely new apps (freshly generated with `lapis --new`)
0. It only occurs in development configuration, probably because of the enabled code-cache
0. The error only manifests itself when accessing from localhost, both through a reverse proxy or directly with `lynx`
0. It happens with Lua and Moonscript
0. Re-building openresty with only some basic config flags doesn't work.
0. Adding worker processes doesn't fix the problem, but makes it a bit more random; every worker process drops dead by the second request it gets
0. The problem does *not* occur with a simple `content_by_lua` statement (example: `ngx.say "hello world"`) works.
0. Updating lapis doesn't fix it either
0. `apt-get update; apt-get upgrade` doesn't fix it either
0. Yes, I *have* tried turning it off and on again. Several times.

I'll provide aditional information if needed. This may very well be my fault for messing with something I shouldn't, but I can't think of anything I did that would lead to lapis breaking for no reason. I've had lapis running in production for a long time now, so I don't know when exactly it broke. It *might* have been with the last time I did `apt-get upgrade`, but I can't confirm that.

`openresty -V`:

    nginx version: openresty/1.13.6.1
    built by gcc 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9)
    built with OpenSSL 1.0.2g  1 Mar 2016
    TLS SNI support enabled
    configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt=-O2 --add-module=../ngx_devel_kit-0.3.0 --add-module=../echo-nginx-module-0.61 --add-module=../xss-nginx-module-0.05 --add-module=../ngx_coolkit-0.2rc3 --add-module=../set-misc-nginx-module-0.31 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.07 --add-module=../srcache-nginx-module-0.31 --add-module=../ngx_lua-0.10.11 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.18 --add-module=../redis2-nginx-module-0.14 --add-module=../redis-nginx-module-0.3.7 --add-module=../rds-json-nginx-module-0.15 --add-module=../rds-csv-nginx-module-0.08 --add-module=../ngx_stream_lua-0.0.3 --with-ld-opt=-Wl,-rpath,/usr/local/openresty/luajit/lib --with-pcre-jit --with-http_v2_module --with-http_ssl_module --with-stream --with-threads --with-stream_ssl_module --with-stream --with-stream_ssl_module

**Comment by leafo** [comment]
It's hard for me to tell what's going on with just the information you've provided, but we can try to narrow it down.

Can you try reinstalling all luarocks modules you have installed? You may have a C module that's depending on a .so file that no longer exists on your system after the upgrade.

**Comment by DarkWiiPlayer** [comment]
I was afraid you'd say something like that... :| (on it)

**Comment by DarkWiiPlayer** [comment]
Okay, from what I can tell, reinstalling all the rocks seems to have fixed it. Thanks for the help. What a weird error though...
