### ISSUE TITLE
Feature Request: Add Delete Method as Model Class Method

### ISSUE THREAD

**Issue by ryanford-frontend** [leafo/lapis#636]
Currently 2 queries are required to delete using the preferred instance method. 

```lua
local Model = require("lapis.db.model").Model
local Posts = Model:extend("posts")
local post = Posts:find(123) -- query 1
post:delete() -- query 2
```

It would be nicer to just use:

```lua
local Model = require("lapis.db.model").Model
local Posts = Model:extend("posts")
Posts:delete(123)
```

I'm aware you can do this with `db.delete` but it would be preferable to use the Model.

**Comment by leafo** [comment]
I'm very fearful of delete functions, small typos can lead to big disasters. Would `Posts:delete()` delete the whole table?

btw, an alternative is using load: `Posts:load({id = 123}):delete()`

**Comment by ryanford-frontend** [comment]
That would still be 2 queries wouldn't it?

**Comment by leafo** [comment]
@ryanford-frontend It is undocumented right now. I converts a table into a instance of a model class (sanitizing fields if necessary). It's how all query functions convert database results to model instances.

**Comment by ryanford-frontend** [comment]
This solves my issue. That's a better solution than what I proposed.
