### ISSUE TITLE
Standardize SQL commands to uppercase letters

### ISSUE THREAD

**Issue by edubart** [leafo/lapis#640]
Currently there are places that use uppercase letters like `SELECT` when composing a SQL query, and other places that use lowercase letters like `from`. It's better to have all SQL commands in uppercase because this is the usual standard in SQL world and also makes much easier to read SQL queries in debug mode because we can differentiate better columns and table names from SQL commands.

**Comment by leafo** [comment]
This should be resolved by now. Feel free to open a ticket if you spot any places that were missed
