### ISSUE TITLE
Should lapis validation support coercion?

### ISSUE THREAD

**Issue by italomaia** [leafo/lapis#644]
Input validation allows you to make sure the data you're getting is within the range of values that you expect, but what about its type?

Does it make sense to test if some input is an integer, but still get it as a string? I would like to suggest the built-in capability of being able to coerce param values that are valid. It could probably save some trouble to a lot of people along the way.

**Comment by leafo** [comment]
The default system for validation is fine for basic tests but leaves a lot to be desired when handling complex inputs. I've spent a lot of time trying to think about the best way to handle validation, and I ended up coming up with a new library. It's much more flexible so I recommend checking that out: https://github.com/leafo/tableshape It has the concept of transformations that will allow you coerce values from one type to another.

In the future, I'm considering replacing the lapis validation system with something powered by this
