### ISSUE TITLE
use lapis cjson empty array retun {} why not is []

### ISSUE THREAD

**Issue by tanwenliang** [leafo/lapis#648]
From the json data returned by the third-party API, there is an empty array of key values, but after the two steps of decode and encode, the value of the key becomes an empty object:

`local cjson = require('cjson')

local raw = {}
raw.name = 'answer'
raw.list = {}
local str = cjson.encode(raw)
print('after cjson encode:', str)
`

`local cjson = require('cjson')

local raw = {}
raw.name = 'answer'
raw.list = {}
cjson.encode_empty_table_as_object(false)  -- how to use this code in lapis 
local str = cjson.encode(raw)
print('after cjson encode:', str)`

**Comment by tanwenliang** [comment]
@leafo @kidd

**Comment by leafo** [comment]
This isn't specific to lapis, but a side effect of how lua doesn't have a separate array and has table type. So an empty table is ambiguous and cjson defaults to an empty hash table. Some cjson implementations include `cjson.empty_array` to represent an empty array when encoding. The version include with openresty has this, but the version on luarocks doesn't iirc.

**Comment by tanwenliang** [comment]
thks @leafo  How to solve cjson.empty_array in lapis？  how to set
return {json={},status=200}  like this data in reponse  
or return cjosn.encode({json={},status=200}   lapis  supports?
