### ISSUE TITLE
How to make lapis always return json instead of a page, I need to do restful api server 

### ISSUE THREAD

**Issue by tanwenliang** [leafo/lapis#651]
How to make lapis always return json instead of a page
Need to do restyapi server

now response  
some times server error ,lapis reponse html code ,how to set lapis  return json 
`<!DOCTYPE HTML>
<html lang="en">
    <head>
        <title>Lapis Page</title>
    </head>
    <body></body>
</html>`

**Comment by drmargarido** [comment]
In your endpoint function you can return something like:
```lua
function(self)
  return { json = self.params, status=200}
end
```

**Comment by drmargarido** [comment]
And for the error case, in you app file,  you can do:
```lua
app.handle_404 = function(self)
    return { json = self.params, status=200}
end
```

**Comment by leafo** [comment]
Just for some additional context, there is a default layout that will put HTML on the page (and also set the content type to `text/html`). If you need complete control over the output then you can pass `layout = false` as part of the return options. You can also overrie the content type with `content_type = "your content type". When `layout` is set to false then only the string that you write/return from your action will be sent to the browser.
