### ISSUE TITLE
Server files in their own folder

### ISSUE THREAD

**Issue by italomaia** [leafo/lapis#652]
Just tried out lapis-chan here and noticed a lot of server (openresty) files generated spread across my application files. Is there a way to keep all of those in a single folder by default, so that development is not affected?

**Comment by leafo** [comment]
I'm pretty sure you can edit nginx config and specify where these directories should exist. You'll have to look up each individual directive to see how you configure their locations. Alternatively you can use a `.gitignore` to ignore those directories:

```
client_body_temp
fastcgi_temp
proxy_temp
scgi_temp
uwsgi_temp
```
