### ISSUE TITLE
*_temp directories

### ISSUE THREAD

**Issue by karai17** [leafo/lapis#653]
When a lapis server is turned on, several directories and files are created:

* client_body_temp
* fastcgi_temp
* proxy_temp
* scgi_temp
* uwsgi_temp
* logs
* nginx.conf.compiled

`logs` and `nginx.conf.compiled` are pretty obvious, but the `*_temp` directories, are these directories actually used for anything? I've never seen files inside of any of them, not even for a split second. Are these directories created by nginx/openresty or lapis server? Is there a way to disable them since they seem to be largely useless?

**Comment by aiibe** [comment]
If you have a config.lua file, nginx.conf.compiled file is required to run. Other directories are used temporary for instance when making request to another server and read body response. Even if you removed them, they will be create automatically at next run.

**Comment by karai17** [comment]
Yeah, `nginx.conf.compiled` is obviously necessary but the other directories seem like they aren't, or shoudl be able to just use one single `temp` directory instead of spawning several that clutter up my work space. It' snot a huuuuge issue, just mostly wondering if there is a way to disable them without hurting anything.

**Comment by leafo** [comment]
nginx creates them, not lapis. You may be able to configure where nginx creates them, but I'm not sure if you can prevent them from being created. Check the nginx configuration documentation
