### ISSUE TITLE
/usr/local/share/lua/5.1/lapis/db/base.lua:122: attempt to call method &#039;gsub&#039

### ISSUE THREAD

**Issue by tanwenliang** [leafo/lapis#655]
```lua
    local where = " where service_id = ?"
    local sql = table.concat({
        "select ",
        field_alias.skyg_service_sid_field(),
        " from skyg_service.sid_",
        tid
    })

    ngx.say(sql)

    local res = db2:query(sql,sid)
    ngx.say(cjson.encode(res))
    ngx.exit(200)
```  

</style></head><body><div class="box"><h1>Error</h1><pre>/usr/local/share/lua/5.1/lapis/db/base.lua:122: attempt to call method &#039;gsub&#039; (a nil value)</pre><h2>Traceback</h2><pre>
stack traceback:
	/usr/local/share/lua/5.1/lapis/db/base.lua:122: in function &#039;interpolate_query&#039;
	.////lib/mdb.lua:271: in function &#039;query&#039;
	.///controllers/sid.lua:43: in function &#039;handler&#039;
	/usr/local/share/lua/5.1/lapis/application.lua:130: in function &#039;resolve&#039;
	/usr/local/share/lua/5.1/lapis/application.lua:167: in function &lt;/usr/local/share/lua/5.1/lapis/application.lua:165&gt;
	[C]: in function &#039;xpcall&#039;
	/usr/local/share/lua/5.1/lapis/application.lua:173: in function &#039;dispatch&#039;
	/usr/local/share/lua/5.1/lapis/nginx.lua:230: in function &#039;serve&#039;
	content_by_lua(nginx.conf.compiled:73):2: in function &lt;content_by_lua(nginx.conf.compiled:73):1&gt;</pre></div><div class="footer">lapis 1.7.0</div></body></html>

**Comment by tanwenliang** [comment]
over,

  local res = db2:query(sql,sid)  change to  local res = db2.query(sql,sid)

**Comment by leafo** [comment]
I'm assuming you figure it out based on your comment. The issue is that `db.query` is a function, and not a method, so you should use `.` to call it instead of `:`.
