### ISSUE TITLE
Using Request Variables in handle_error?

### ISSUE THREAD

**Issue by cycomachead** [leafo/lapis#657]
I have a `self.current_user` set in a `before_filter`. How can I get this in my `app:handle_error` method?

**Comment by leafo** [comment]
From here: http://leafo.net/lapis/reference/actions.html#error-handler

> You can access the original request object with `self.original_request`

So you can access the user with `self.original_request.current_user`

A new request object is created to prevent any things you may have written to the old one from messing up the output for the error page

**Comment by cycomachead** [comment]
Ah, whoops. It’s right there! 

Thanks for the quick reply!
