### ISSUE TITLE
Unable to have cqueues production without cqueues explicity defined for development also

### ISSUE THREAD

**Issue by ryanford-dev** [leafo/lapis#665]
```lua
-- config.lua
local config = require('lapis.config')

config('production', {
   port = 80,
   server = 'cqueues',
})
```
Running `lapis server production` will return
```
$ lapis server production
Error: file doesn't exist `nginx.conf'
 * Run with --trace to see traceback
 * Report issues to https://github.com/leafo/lapis/issues
```

Adding a matching config for development solves the issue.
```lua
-- config.lua
local config = require('lapis.config')

config('development', {
   server = 'cqueues',
   port = 8080,
})

config('production', {
   port = 80,
   server = 'cqueues',
})
```

**Comment by rayhanadev** [comment]
Hey did this ever get solved? I have this same issue.

**Comment by leafo** [comment]
@rayhanadev The issue originally described here does not happen. You're likely encountering something else. I would see to see what you config looks like and the command you're trying to run to diagnose what is happening. Keep in mind the default environment is `development`, and if you run `lapis server` with no environment specified then it will try to load the the default configuration which specifies nginx.
