### ISSUE TITLE
Model\create auto_id conflict

### ISSUE THREAD

**Issue by MiYogurt** [leafo/lapis#666]
```
raw_user = {
    -- id: 1 
    username: "xxx"
    email: "xxxxxt@gmail.com"
    password: "password"
    phone: "00000000000"
}
```

```
// by busted
  it "query users by query api", ->
    for i = 1, 32
        -- raw_user["id"] = i
        Model.create Users, raw_user
    status, body = request "/sdk/users/query", {
        headers: 
            'content-type': 'application/json'
        expect: "json"
        method: "POST"
    }

    assert.same 200, status
    assert.same 4, body["all"]
```
It's impossible to know id in a production environment

I got an error `ERROR: duplicate key value violates unique constraint "users_pkey"`

Is it concurrency that causes this problem? two thread use one last_auto_id ?

If i use raw sql it work

```
db.query [[
            INSERT INTO "users"("username", "email", "password", "phone") VALUES(?, ?, ?, ?) RETURNING "id", "username", "email", "password", "phone";
        ]], raw_user['username'], raw_user['email'], raw_user['password'], raw_user['phone']
```

**Comment by leafo** [comment]
If you're using postgres, then inserts from the `create` method have a `returning` clause. The object returned from `create` will have the `id` field in it. (or whatever the primary keys are set to, along with any other dynamically computed fields from `db.raw`)

Regarding duplicate IDs in production, I suggest having some kind of truncate `before` function to clean the database tables relevant to the tests being run. Hope that helps!

**Comment by MiYogurt** [comment]
```
Users\create copy raw_user
```

ye.  i forget the return data in table，to create multiline data， need copy object，thanks。
