### ISSUE TITLE
`OPENSSL_1_1_1' not found 

### ISSUE THREAD

**Issue by vadi2** [leafo/lapis#667]
Using Ubuntu 18.04 and Lua 5.1.5, lapis 1.7.0 and openresty 1.13.6.2-1, going to `localhost:8080` on the default example doesn't work:

```lua
$ lapis server
nginx: [alert] lua_code_cache is off; this will hurt performance in /home/vadi/Programs/smart-rubber-playground/nginx.conf.compiled:16
2019/04/10 11:38:29 [notice] 2709#2709: using the "epoll" event method
2019/04/10 11:38:29 [notice] 2709#2709: openresty/1.13.6.2
2019/04/10 11:38:29 [notice] 2709#2709: OS: Linux 4.15.0-34-generic
2019/04/10 11:38:29 [notice] 2709#2709: getrlimit(RLIMIT_NOFILE): 1024:4096
2019/04/10 11:38:29 [notice] 2709#2709: start worker processes
2019/04/10 11:38:29 [notice] 2709#2709: start worker process 2710
2019/04/10 11:38:36 [error] 2710#2710: *1 lua entry thread aborted: runtime error: error loading module '_openssl.hmac' from file '/usr/local/lib/lua/5.1/_openssl.so':
	/usr/local/openresty/openssl/lib/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by /usr/local/lib/lua/5.1/_openssl.so)
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf.compiled:22):2: in function <content_by_lua(nginx.conf.compiled:22):1>, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:8080"
```

I've tried the hello world example from openresty and that seems to be working fine.

**Comment by leafo** [comment]
this error appears to be coming from openresty when an hmac function is used. If you take the openresty example that works and try using the `hmac_sha1` function does it throw the same error?

https://github.com/openresty/lua-nginx-module#ngxhmac_sha1

**Comment by aiibe** [comment]
Did you install these packages ?
'''
sudo apt-get install libpcre3-dev \ libssl-dev perl make build-essential curl
'''

**Comment by zaiste** [comment]
I have the same error on Ubuntu `19.04` and OpenResty `1.15.8.1`. There is also `openresty-openssl` automatically installed in the version `1.1.0j`.

@leafo I've tried your suggestion with putting the code directly in OpenResty and the hashing function works without problem.

@aiibe I have those packages installed.

**Comment by zaiste** [comment]
After writing the previous comment, I've realized it's the OpenSSL version mismatch i.e. `1.1.0j` vs `1.1.1b` available in the system. It looks like it's needed to recompile `openresty`

**Comment by vadi2** [comment]
I get my openresty from the Ubuntu repository they provide so recompiling doesn't seem applicable. I'm stuck.

**Comment by aiibe** [comment]
I got the same issue with Ubuntu 18.04

**Comment by leafo** [comment]
I have a mini guide here about building openresty with openssl 1.0 that you can try: https://leafo.net/guides/building-openresty-with-openssl-1-0.html

**Comment by vadi2** [comment]
Nice thanks. @Edru2 also mentioned this worked for them:

> I removed openresty and installed openresty-openssl111 before reinstalling openrestry

**Comment by FourierTransformer** [comment]
Another solution to this is to use [ryanford-dev's solution](https://github.com/leafo/lapis/issues/632#issuecomment-436514178) of installing openresty-openssl-dev and then installing luaossl (or lapis) pointing at openresty's openssl.
