### ISSUE TITLE
fetch relation preload documentation unclear

### ISSUE THREAD

**Issue by giann** [leafo/lapis#668]
Here's the paragraph

> fetch relations can also provide a preloader to allow for the data to be loaded over an array of objects. **The preloader function recieves as arguments: the array table of objects to preload, the current mode, the name of the relation.**

- After trying it out: the third argument seems to be the model class and the fourth the name of the relation
- What's the _current mode_?

**Comment by leafo** [comment]
*current mode* should be *current model*

**Comment by leafo** [comment]
I updated the docs a bit, tell me if that helps at all

**Comment by giann** [comment]
It’s better yes 👍 Maybe add the parameters in the snippets?
