### ISSUE TITLE
"lapis new" fails with error: attempt to index local '_with_0' (a nil value)

### ISSUE THREAD

**Issue by marcdraco** [leafo/lapis#670]
Feel a bit of a dolt TBH. I got everything working, even the Crypto functions and so on on my freshly minted Alpline Linux (so a lot isn't install and it's Musl-based so there's that confusion). Moonscript installed too so I was about ready for liftoff whe:

`
$lapis new

Error: attempt to index local '_with_0' (a nil value)
 * Run with --trace to see traceback
 * Report issues to https://github.com/leafo/lapis/issues
museum:~/webrathea$ lapis new --trace
/usr/bin/lua5.1: /usr/local/share/lua/5.1/lapis/cmd/path.lua:33: attempt to index local '_with_0' (a nil value)
stack traceback:
	/usr/local/share/lua/5.1/lapis/cmd/path.lua:33: in function 'fn'
	/usr/local/share/lua/5.1/lapis/cmd/path.lua:116: in function 'write_file'
	/usr/local/share/lua/5.1/lapis/cmd/actions.lua:32: in function 'write_file_safe'
	/usr/local/share/lua/5.1/lapis/cmd/nginx/actions.lua:19: in function 'new'
	/usr/local/share/lua/5.1/lapis/cmd/actions.lua:136: in function </usr/local/share/lua/5.1/lapis/cmd/actions.lua:129>
	(tail call): ?
	(tail call): ?
	(tail call): ?
	...local/lib/luarocks/rocks-5.1/lapis/1.7.0-1/bin/lapis:4: in main chunk
	[C]: ?
`

**Comment by leafo** [comment]
error is most likely because you don't have write permissions in the directory you ran `lapis new` in. I updated the error handling to show a proper error message if the file can't be opened for writing

**Comment by marcdraco** [comment]
Thank you. Apologies for the long delay, I didn't receive the notification and only just noticed it elsewhere.
