### ISSUE TITLE
How to serve static files with lua-http?

### ISSUE THREAD

**Issue by frenzox** [leafo/lapis#673]
I'm wondering if there's a good way to serve static files using lua-http/cqueues server. I can read files into a buffer and write them, but for larger files it becomes quite slow.

**Comment by aylmerbritto** [comment]
Hey @frenzox 
Did you find out a way to do it ? Can you please help me with it ?? 
Thanks :)

**Comment by rise-cons** [comment]
I'm actually using Lapis with Lua 5.4 and http / cqueues using Nginx as a rexerse proxy and for sarving the static files
