### ISSUE TITLE
_G write guard

### ISSUE THREAD

**Issue by webandbusiness** [leafo/lapis#676]
Hello, i am new in LAPIS+openresty 1.15
i am running a test application from openresty installation (not command line)
I have this issue since...., i tracked but no find any global variable declaration
Pls help!!

```
2019/08/19 08:25:28 [warn] 980#0: *80 [lua] _G write guard:12: writing a global lua variable ('socket') which may lead to race conditions between concurrent requests, so prefer the use of 'local' variables
stack traceback:
	[C]: at 0x7fca6bc70240
	[C]: in function 'require'
	/usr/local/share/lua/5.1/socket.lua:12: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.1/socket/url.lua:13: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.1/lapis/util.lua:1: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.1/lapis/cmd/util.lua:6: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.1/lapis/config.lua:120: in function 'get_env'
	/usr/local/share/lua/5.1/lapis/config.lua:127: in function 'get'
	/usr/local/share/lua/5.1/lapis/logging.lua:4: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.1/lapis/application.lua:1: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.1/lapis/init.lua:1: in main chunk
	[C]: in function 'require'
	/home/scrrim/app.lua:2: in main chunk, client: 129.0.80.212, server: www.mydomain.com, 
2019/08/19 08:25:28 [warn] 980#0: *80 [lua] _G write guard:12: writing a global lua variable ('lpeg') which may lead to race conditions between concurrent requests, so prefer the use of 'local' variables
stack traceback:
	[C]: at 0x7fca6b5f6420
	[C]: in function 'require'
	/usr/local/share/lua/5.1/lapis/util.lua:44: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.1/lapis/cmd/util.lua:6: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.1/lapis/config.lua:120: in function 'get_env'
	/usr/local/share/lua/5.1/lapis/config.lua:127: in function 'get'
	/usr/local/share/lua/5.1/lapis/logging.lua:4: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.1/lapis/application.lua:1: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.1/lapis/init.lua:1: in main chunk
	[C]: in function 'require'
	/home/scrrim/app.lua:2: in main chunk, client: 129.0.80.212, server: www.mydomain.com
```

**Comment by turbo** [comment]
I second this, it's pretty annoying. Now, this isn't an error or really Lapis' fault, but we should get rid of this in all Lua libs. Looks like the first warning comes from luasocket, not Lapis.

**Comment by ryanford-frontend** [comment]
If you just want to silence the warning, you can require those rocks in an `init_by_lua_block` block in OpenResty. Maybe someday Lapis will ship with forked versions of it's dependencies that don't pollute the global namespace. I'm fairly certain the offenders *won't* fix it in the libraries as they're older/popular and it would potentially break tons of projects.

**Comment by leafo** [comment]
you can get rid of the lpeg warning by upgrading to the latest vesrion

regarding LuaSocket, it probably doesn't have to be a dependency that's loaded during nginx.

There are other things that we use that are more tricky to clean up though.

**Comment by cycomachead** [comment]
Anyone know if it is possible to disable this? I find the logs distracting from what I'm actually looking for. (And though this seems like a good idea, `luacheck` covers my needs.)

Sorry, I know this is not a Lapis-specific question, but I looked around and the only other results are about disabling warnings in tests. I saw a mention of `rawest`, but I can't tell if it could have any adverse effects?

**Comment by turbo** [comment]
> I find the logs distracting from what I'm actually looking for.

They should only occur once unless code cache is disabled. But even in tests, there is no reason to disable code cache (I'm using busted with resty to run tests). If you're running in nginx, ryan's advice is the easiest way to fix this (added benefit is that errors in required modules are found on server startup).

**Comment by TofuLay** [comment]
I want to know where is the problem.
Whether it will pollute other libraries ?
And Whether affect the use of other libraries？
who can help me，I am new to this framework！
Thanks!!!

**Comment by sharpobject** [comment]
The lpeg warning is still present in the latest version.

**Comment by leafo** [comment]
I'm going to close this issue since there not much we can do, see this response from ryanford-dev:

> If you just want to silence the warning, you can require those rocks in an `init_by_lua_block` block in OpenResty (the nginx.conf). Maybe someday Lapis will ship with forked versions of it's dependencies that don't pollute the global namespace. I'm fairly certain the offenders _won't_ fix it in the libraries as they're older/popular and it would potentially break tons of projects.
