### ISSUE TITLE
Not fount example with http.server and without openresty

### ISSUE THREAD

**Issue by first-leon** [leafo/lapis#678]
Hello!
I not found example in source code and internet with run lapis on http.server.
But it work!?
Where i find example?

**Comment by mosolovsa** [comment]
There's a [doc section](https://github.com/leafo/lapis/blob/master/docs/server_backends.md), describing the way how to configure lapis to run on http.server Lua library.
However, I do not know if this info is still relevant.

I would appreciate, if someone who knows that, comment on that.
