### ISSUE TITLE
cache.lua:14: attempt to concatenate local 'v' (a boolean value)

### ISSUE THREAD

**Issue by alexz006** [leafo/lapis#683]
```lua
app:match("/microcached", cached({
  exptime = 1,
  function(self)
    return "hello world!"
  end
}))
```
```GET /microcached?foo=bar``` - it works

```GET /microcached?foo``` - this does not work
```
Error

...cal/openresty/luajit/share/lua/5.1/lapis/nginx/cache.lua:14: attempt to concatenate local 'v' (a boolean value)

Traceback

stack traceback:
	...cal/openresty/luajit/share/lua/5.1/lapis/nginx/cache.lua:14: in function '_cache_key'
	...cal/openresty/luajit/share/lua/5.1/lapis/nginx/cache.lua:52: in function 'handler'
	...cal/openresty/luajit/share/lua/5.1/lapis/application.lua:130: in function 'resolve'
	...cal/openresty/luajit/share/lua/5.1/lapis/application.lua:167: in function <...cal/openresty/luajit/share/lua/5.1/lapis/application.lua:165>
	[C]: in function 'xpcall'
	...cal/openresty/luajit/share/lua/5.1/lapis/application.lua:173: in function 'dispatch'
	/usr/local/openresty/luajit/share/lua/5.1/lapis/nginx.lua:230: in function 'serve'
	content_by_lua(nginx.conf.compiled:252):2: in main chunk
```

**Comment by CaptainZidgel** [comment]
1) I cannot solve your issue, unfortunately, it seems to be Lapis. I am writing this to contribute to the solution of the Lapis issue.
2) I do not understand anything about the internals of Lapis so I cannot tinker or build it.
3) Leafo most likely knows the problem+solution here and hasn't posted on the issue but if this is the offending code:
```lua
local cache_key
cache_key = function(path, params, r)
  do
    local _accum_0 = { } 
    local _len_0 = 1
    for k, v in pairs(params) do
      _accum_0[_len_0] = k .. ":" .. v --line 14
      _len_0 = _len_0 + 1
    end
    params = _accum_0
  end
  sort(params)
  params = concat(params, "-")
  return path .. "#" .. params
end
```
The problem would be that when params are passed, if a param only has a key (like `GET /microcached?foo`) it is stored as `foo = true`. I don't know what _accum_0 does so I don't know what exact format the result needs to be but this looks like it could be solved with a simple `tostring` call, or a ternary `v = type(v) == "boolean" and tostring(v) or v` to preserve num values (although I don't think this code is set up to receive nums as nums? If it were, then you would need a tonumber call...)
