### ISSUE TITLE
route pattern matches "-" incorrectly

### ISSUE THREAD

**Issue by Fish013** [leafo/lapis#696]
when defining a route like `app:post("/build/:build_identifier[a-z]/info", function(self) ...`
build_identifier "-" will be matched.
I did not expect that, since `string.find("-", "[a-z]")` does not match.

Currently: `/build/-/info` is a valid path for the route `/build/:build_identifier[a-z]/info`
Expected: `/build/-/info` does not match for the route `/build/:build_identifier[a-z]/info`

**Comment by leafo** [comment]
Thanks, good find
