### ISSUE TITLE
Installing issue in Ubuntu 18.

### ISSUE THREAD

**Issue by jscsharp** [leafo/lapis#698]
I am trying to install Lapis on Ubuntu 18.0
I have Lua 5.4.0 installed.

but I am getting error for luabitop( from pgmoon) here is the error:

 sudo luarocks install lapis

-----------------------------------
Installing https://luarocks.org/lapis-1.8.1-1.src.rock
Missing dependencies for lapis 1.8.1-1:
   pgmoon (not installed)

lapis 1.8.1-1 depends on lua (5.4-1 provided by VM)
lapis 1.8.1-1 depends on ansicolors (1.0.2-3 installed)
lapis 1.8.1-1 depends on date (1.0-1 installed)
lapis 1.8.1-1 depends on etlua (1.3.0-1 installed)
lapis 1.8.1-1 depends on loadkit (1.1.0-1 installed)
lapis 1.8.1-1 depends on lpeg (1.0.2-1 installed)
lapis 1.8.1-1 depends on lua-cjson (2.1.0.6-1 installed)
lapis 1.8.1-1 depends on luaossl (20200709-0 installed)
lapis 1.8.1-1 depends on luafilesystem (1.8.0-1 installed)
lapis 1.8.1-1 depends on luasocket (3.0rc1-2 installed)
lapis 1.8.1-1 depends on mimetypes (1.0.0-2 installed)
lapis 1.8.1-1 depends on pgmoon (not installed)
Installing https://luarocks.org/pgmoon-1.11.0-1.src.rock
Missing dependencies for pgmoon 1.11.0-1:
   luabitop (not installed)

pgmoon 1.11.0-1 depends on lua >= 5.1 (5.4-1 provided by VM)
pgmoon 1.11.0-1 depends on luabitop (not installed)
Installing https://luarocks.org/luabitop-1.0.1-1.src.rock

luabitop 1.0.1-1 depends on lua >= 5.1 (5.4-1 provided by VM)
Do not use 'module' as a build type. Use 'builtin' instead.
gcc -O2 -fPIC -I/usr/local/include -c bit.c -o bit.o
bit.c: In function ‘barg’:
bit.c:79:2: error: #error "Unknown number type, check LUA_NUMBER_* in luaconf.h"
 #error "Unknown number type, check LUA_NUMBER_* in luaconf.h"
  ^~~~~
bit.c:82:5: warning: implicit declaration of function ‘luaL_typerror’; did you mean ‘luaL_typeerror’? [-Wimplicit-function-declaration]
     luaL_typerror(L, idx, "number");
     ^~~~~~~~~~~~~
     luaL_typeerror
bit.c: In function ‘luaopen_bit’:
bit.c:175:3: warning: implicit declaration of function ‘luaL_register’; did you mean ‘lua_register’? [-Wimplicit-function-declaration]
   luaL_register(L, "bit", bit_funcs);
   ^~~~~~~~~~~~~
   lua_register

Error: Failed installing dependency: https://luarocks.org/pgmoon-1.11.0-1.src.rock - Failed installing dependency: https://luarocks.org/luabitop-1.0.1-1.src.rock - Build error: Failed compiling object bit.o
---------------------------------------------------------------------------------

I am new to Lua and Lapis projects.
Does Lua 5.4.0  needs the "luabitop"  package?
Thanks

**Comment by CriztianiX** [comment]
Lapis only runs over lua5.1 compatible version, like luajit.

**Comment by jscsharp** [comment]
Thanks, I will try it.
