### ISSUE TITLE
/usr/local/share/lua/5.1/lapis/html.lua:303: attempt to call method '_inherit_helpers' (a nil value)

### ISSUE THREAD

**Issue by Unlimiter** [leafo/lapis#699]
```moonscript
-- app.moon
export require, Widget
require = require'require'.require
lapis = require 'lapis'

import Widget from require 'lapis.html'

class extends lapis.Application
  layout: 'layout' --> Error
  '/': =>
    render: 'index'
```

```moonscript
-- views/layout.moon
class Layout extends Widget
  content: =>
    html_5 ->
      head -> title @title or 'TinyMoon'
      body ->
        widget 'navbar' --> This is THE line making the error
        @content_for 'inner'
```

```moonscript
-- views/navbar.moon
class NavBar extends Widget
  content: =>
    nav id: 'navbar', ->
      a href: '/', 'Home'
      span '&bull;'
      a href: '/help', 'Help'
```

In #700 I passed ~~the actual widget~~ a function rather than the widget's name.

**Comment by leafo** [comment]
If you're showing the entire files, then you never brought Widget into scope in the views. You need to require it. You may want to look up how require and local variables work in lua since it seems both of your issues are related to that

**Comment by leafo** [comment]
```
export require, Widget
require = require'require'.require
lapis = require 'lapis'

import Widget from require 'lapis.html'
```

I'm not really sure what exactly is going on here but I generally recommend against global variables.

The error you're seeing is because the view widget isn't inheriting from the widget subclass. It looks like you're trying to depend on a global value of `Widget` in the code you shared.

**Comment by Unlimiter** [comment]
@leafo Importing `Widget` in each file didn't fix it.

**Comment by leafo** [comment]
The error message `attempt to call method '_inherit_helpers'` effectively means you're trying to render something that isn't a widget class (whether that's the layout, a view, or a sub widget)

Upon closer investigation I see that you pointed the line `widget 'navbar'`

The string `"navbar"` is not a widget class. You need to pass either a widget subclass or an instance of a widget. If you want to render something by module name then you can use the `render` function.

**Comment by Unlimiter** [comment]
`render 'views.navbar` did the trick.
