### ISSUE TITLE
Warnings for a new installation - "writing a global Lua variable ('lpeg') which may lead to race conditions between concurrent requests, so prefer the use of 'local' variables"

### ISSUE THREAD

**Issue by nfedyashev** [leafo/lapis#708]
Hello! Thanks for the wonderful lua web framework! I'm still learning it but it already looks very impressive.

I'm wondering whether these warnings for a clean new lapis app could be ignored or is it safe to use it in production.
vanilla new `lapis new` app, latest Ubuntu(20.04), latest openresty(1.17.8.2).
I can reproduce these warnings on 2 setups(at home - Debian, and with this log below on Ubuntu 20.04 VPS).

<details open>
<summary>lapis log</summary>
<br>
<pre>
 LAPIS_OPENRESTY=/opt/resty/nginx/sbin/nginx lapis server
nginx: [alert] lua_code_cache is off; this will hurt performance in /home/deploy/fooapp/nginx.conf.compiled:16
2020/10/11 17:51:00 [notice] 71689#0: using the "epoll" event method
2020/10/11 17:51:00 [notice] 71689#0: openresty/1.17.8.2
2020/10/11 17:51:00 [notice] 71689#0: built by gcc 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04) 
2020/10/11 17:51:00 [notice] 71689#0: OS: Linux 5.4.0-45-generic
2020/10/11 17:51:00 [notice] 71689#0: getrlimit(RLIMIT_NOFILE): 1024:1048576
2020/10/11 17:51:00 [notice] 71689#0: start worker processes
2020/10/11 17:51:00 [notice] 71689#0: start worker process 71690
2020/10/11 17:51:10 [warn] 71690#0: *1 [lua] _G write guard:12: writing a global Lua variable ('lpeg') which may lead to race conditions between concurrent requests, so prefer the use of 'local' variables
stack traceback:
	[C]: at 0x7f1ff7719cc0
	[C]: in function 'require'
	/usr/local/share/lua/5.1/lapis/router.lua:4: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.1/lapis/application.lua:4: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.1/lapis/init.lua:1: in main chunk
	[C]: in function 'require'
	content_by_lua(nginx.conf.compiled:22):2: in main chunk, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:8080"
2020/10/11 17:51:10 [warn] 71690#0: *1 [lua] _G write guard:12: writing a global Lua variable ('socket') which may lead to race conditions between concurrent requests, so prefer the use of 'local' variables
stack traceback:
	[C]: at 0x7f1ff77063e0
	[C]: in function 'require'
	/usr/local/share/lua/5.1/socket.lua:12: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.1/socket/url.lua:13: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.1/lapis/util.lua:1: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.1/lapis/router.lua:10: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.1/lapis/application.lua:4: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.1/lapis/init.lua:1: in main chunk
	[C]: in function 'require'
	content_by_lua(nginx.conf.compiled:22):2: in main chunk, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:8080"
2020/10/11 17:51:10 [notice] 71690#0: *1 [lua] [C]:-1: [200] GET / - {  }, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:8080"
2020/10/11 17:51:23 [warn] 71690#0: *2 [lua] _G write guard:12: writing a global Lua variable ('lpeg') which may lead to race conditions between concurrent requests, so prefer the use of 'local' variables
stack traceback:
	[C]: at 0x7f1ff7739cc0
	[C]: in function 'require'
	/usr/local/share/lua/5.1/lapis/router.lua:4: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.1/lapis/application.lua:4: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.1/lapis/init.lua:1: in main chunk
	[C]: in function 'require'
	content_by_lua(nginx.conf.compiled:22):2: in main chunk, client: 109.207.193.225, server: , request: "GET / HTTP/1.1", host: "1.2.3.4:8080"
2020/10/11 17:51:23 [warn] 71690#0: *2 [lua] _G write guard:12: writing a global Lua variable ('socket') which may lead to race conditions between concurrent requests, so prefer the use of 'local' variables
stack traceback:
	[C]: at 0x7f1ff77263e0
	[C]: in function 'require'
	/usr/local/share/lua/5.1/socket.lua:12: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.1/socket/url.lua:13: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.1/lapis/util.lua:1: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.1/lapis/router.lua:10: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.1/lapis/application.lua:4: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.1/lapis/init.lua:1: in main chunk
	[C]: in function 'require'
	content_by_lua(nginx.conf.compiled:22):2: in main chunk, client: 109.207.193.225, server: , request: "GET / HTTP/1.1", host: "1.2.3.4:8080"
2020/10/11 17:51:23 [notice] 71690#0: *2 [lua] [C]:-1: [200] GET / - {  }, client: 109.207.193.225, server: , request: "GET / HTTP/1.1", host: "1.2.3.4:8080"
</details>

Everything seems to be working but because of these warnings log file is very noisy and it's kind of hard to test for race condition warnings that it shows.
Should I just ignore it?

**Comment by karai17** [comment]
This is due to an update with openresty that detects globals. There are a number of major lua modules that end up polluting the global namespace so the only real way to clear these warnings is to load the modules in an init block in your nginx config:

```nginx
http {
	...

	init_worker_by_lua_block {
		local uuid = require "resty.jit-uuid"
		uuid.seed()
	}

	init_by_lua_block {
		require "lfs"
		require "lpeg"
		require "ltn12"
		require "markdown"
		require "mime"
		require "socket"
	}

	...
}
```

**Comment by leafo** [comment]
Duplicate issue: #676
