### ISSUE TITLE
mimetypes repository is gone

### ISSUE THREAD

**Issue by frenzox** [leafo/lapis#712]
The [repository for mimetypes](https://bitbucket.org/leafstorm/lua-mimetypes/), which is a lapis dependency, is gone from bitbucket.
Any plans to replace it?

**Comment by leafo** [comment]
I don't think this dependency is necessary, I'd rather just provide the implementation directly in lapis

**Comment by leafo** [comment]
I've removed the dependency and pushed an updated rockspec for 1.8.2 that no longer includes it. I may need to go back to older ones if people are still using those vesrions

**Comment by frenzox** [comment]
Thank you @leafo
