### ISSUE TITLE
How to delete the html code inserted by default?

### ISSUE THREAD

**Issue by ricardoG08** [leafo/lapis#721]
I am using the template system with lua but lapis adds html code by default, do you know how I can delete that html code?, for example:

```
<!DOCTYPE HTML><html lang="en"><head><title>Lapis Page</title></head><body><!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="utf-8">
	<title>nabu</title>
</head>
<body>
<h1>nabu</h1>
</body>
</html></body></html>
```

**Comment by leafo** [comment]
You can set `layout = false` on the render options to disable it for that request, or you can set `layout = false` on on app instance to disable it by default for all requests

**Comment by ricardoG08** [comment]
only with this code for example?

```
local lapis = require("lapis")
local app = lapis.Application()
app:enable("etlua")
local layout = false
```

**Comment by leafo** [comment]
> only with this code for example?
> 
> ```
> local lapis = require("lapis")
> local app = lapis.Application()
> app:enable("etlua")
> local layout = false
> ```

In this example you create a local variable named layout and set it to false, this will have no effect on anything related to lapis.
 
You can change the layout setting on the app in your example code like so:

```lua
app.layout = false
```

**Comment by ricardoG08** [comment]
thanks leafo it worked, I'm still new to lua, greetings and hugs

**Comment by ricardoG08** [comment]
@leafo what is the difference of `types.numeric` and `types.integer`?

**Comment by ricardoG08** [comment]
and in the validation functions you can tell me an example of `type: String` I can't understand how it works: 'c

**Comment by ricardoG08** [comment]
@leafo please set into documentation that types.numeric is a TINYINT
