### ISSUE TITLE
remove session variables in templates

### ISSUE THREAD

**Issue by ricardoG08** [leafo/lapis#728]
it's possible?

**Comment by leafo** [comment]
Cookies and sessions are written after your action finishes but before the view and layout are rendered, so it's not possible to persist any changes to `self.session` during rendering unless you manually interact with nginx to set the cookies yourself.

That said, I think generally you should try to have separation of concerns, rendering a view should ideally not have any side effects

**Comment by ricardoG08** [comment]
thank's @leafo , ideally, save the data from a session variable to an ordinary variable within an action, remove the session variable, and display the data from the ordinary variable within a template
