### ISSUE TITLE
How to make the auto-added iframe and div elements not get added?

### ISSUE THREAD

**Issue by Unlimiter** [leafo/lapis#729]

**Comment by leafo** [comment]
iframe? Not sure what you're talking about, but maybe your want to disable the layout? https://github.com/leafo/lapis/issues/288

**Comment by Unlimiter** [comment]
> iframe? Not sure what you're talking about, but maybe your want to disable the layout? #288

I'm using a custom layout. But it doesn't have this:
```html
<iframe frameborder="0" scrolling="no" style="background-color: transparent; border: 0px; display: none;"></iframe>
<div id="GOOGLE_INPUT_CHEXT_FLAG" style="display: none;" input="" input_stat="{&quot;tlang&quot;:true,&quot;tsbc&quot;:true,&quot;pun&quot;:true,&quot;mk&quot;:true,&quot;ss&quot;:true}"></div>
```

**Comment by leafo** [comment]
Looks like you have a browser extension adding markup to every page you visit.
