### ISSUE TITLE
Add support for Blob types for Postgres.

### ISSUE THREAD

**Issue by eko234** [leafo/lapis#730]
I'm trying to store a blob using Postgres but as i see there is no blob or bytea type, is it posible for you to implement that feature?, or how would you suggest to go about storing binary data?

**Comment by leafo** [comment]
Any types that don't have specific handlers are treated as Lua strings, which is exactly what you want for your blob type.

**Comment by eko234** [comment]
I see, thanks again.

**Comment by eko234** [comment]
I realized that my question is really about migrations, how do i write a migration to create a field that stores a blob?

**Comment by eko234** [comment]
I tried altering the postgresql field and set it to bytea and then tried inserting a record with a blob in the form of a string but it didn't worked either, I think it has something to do with escaping in the blob/string.

**Comment by eko234** [comment]
it's because of the null bytes represented in the string that postgres throws errors... still don'w know how to work around it.
