### ISSUE TITLE
Can't set a row field to null

### ISSUE THREAD

**Issue by eko234** [leafo/lapis#735]
I can't find a way to set a field back to null using the update method from a model entity, deleting the row and creating it again feels like a hack, is there a better way to do it?

**Comment by CriztianiX** [comment]
You can use db.NULL

db = require("lapis.db")
data = { field: db.NULL, ...... }

**Comment by eko234** [comment]
Thanks Criztianix, is there a way to put this in the official documentation, I think it'd be good to have an explicit example there.

**Comment by CriztianiX** [comment]
It is already documented
https://leafo.net/lapis/reference/database.html

db.update "the_table", { name: db.NULL }

**Comment by eko234** [comment]
Oh sorry, i was looking it up un the Models section, My Bad, thankyou again.
