### ISSUE TITLE
table relation with primary keys and foreign keys

### ISSUE THREAD

**Issue by ghost** [leafo/lapis#736]
Although most of the information provided in the lapis documentation is to operate on a single table, how can I make filters or projections by relaunching tables, for example with the following statement? 

`SELECT u.id,u.activated,v.expire AS token_expire FROM users AS u INNER JOIN verifications AS v ON u.id = v.id;`

a quick way is to use` query (query, params ...) ` but is there another method?

**Comment by ricardoG08** [comment]
this is my temporal solution

```
function userModel:findUser(username,email)
	local str_query = "SELECT u.id,u.activated,v.expire AS token_expiration FROM users AS u "..
					  "INNER JOIN verifications AS v ON u.id = v.id "..
					  "WHERE u.username = ? OR u.email = ? LIMIT 2"

	local list_users = self.db.query(str_query,username,email)

	return list_users
end
```

**Comment by leafo** [comment]
For the time being, lapis will not support using join syntax for preloading relations.
