### ISSUE TITLE
lpeg undefined symbol

### ISSUE THREAD

**Issue by bodonkerhoderos** [leafo/lapis#740]
hey i'm having trouble getting lapis to run the default project .

i have installed openresty and luarocks from AUR and then followed the lapis getting started page but opening it in the browser yields:
```
2021/07/05 23:36:44 [error] 232618#0: *1 lua entry thread aborted: runtime error: error loading module 'lpeg' from file '/usr/lib/lua/5.4/lpeg.so':
	/usr/lib/lua/5.4/lpeg.so: undefined symbol: lua_getiuservalue
stack traceback:
coroutine 0:
	[C]: ?
	[C]: in function 'require'
	/usr/share/lua/5.4/lapis/router.lua:4: in main chunk
	[C]: in function 'require'
	/usr/share/lua/5.4/lapis/application.lua:4: in main chunk
	[C]: in function 'require'
	/usr/share/lua/5.4/lapis/init.lua:1: in main chunk
	[C]: in function 'require'
	content_by_lua(nginx.conf.compiled:22):2: in main chunk, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:8080"
```
(irrelevant but notable that i did have to roll back the lua-cjson version as described in #739)

i guess first question is is there something i'm doing wrong? the error leads me to think that (this version of) lpeg is incompatible with luajit. the rockspec file for lpeg indicates it is compatible with lua 5.1

currently i have lpeg version 1.0.2-1 installed. but i tried walking down the line and couldn't get other versions to work as they either threw the same error or other symbols were undefined.

**Comment by leafo** [comment]
This can happen if you're installed a native module using LuaRocks configured for a later version of Lua (5.4, 5.3, etc.) that you're trying to load into openresty with luajit which is compatible with Lua 5.1 shared libraries only.

**Comment by bodonkerhoderos** [comment]
ah perfect thank you! i knew there was something basic i was missing :)

should i draft up a paragraph with this info for the docs in the getting started section?

**Comment by JlnWntr** [comment]
This gives me 

```
Error: Could not find Lua 5.1 in PATH.
Please set your Lua interpreter with:

   luarocks --lua-version=5.1 --local config variables.LUA </path/lua>
```

But `5.1` is too damn outdated for me. That's why I won't be using _Lapis_ anyway.
