### ISSUE TITLE
Widgets and Layouts for Lua?

### ISSUE THREAD

**Issue by eko234** [leafo/lapis#741]
I'm building and app using lua and lapis, and I would like to use widget based views, is there a way to use widgets in plain lua?, if it's not supported yet, could you give me some hint on how to go about it?, maybe there is some way using metatables.

**Comment by eko234** [comment]
Or is there maybe a way to write lua code buy have my views in moonscript?

**Comment by ryanford** [comment]
It's not great but checkout #633 . Basically you can create wrapper factory functions that can create the precompiled moonscript classes.
