### ISSUE TITLE
Missing deps

### ISSUE THREAD

**Issue by the-man-with-a-golden-mind** [leafo/lapis#757]
On Mac (M1 proc) when I am trying to make an migration I am getting an error:
Error: module 'bit' not found:
	no field package.preload['bit']
	no file '/Users/michalmajchrzak/.luarocks/share/lua/5.1/bit.lua'
	no file '/Users/michalmajchrzak/.luarocks/share/lua/5.1/bit/init.lua'
	no file './bit.lua'
	no file '/opt/homebrew/share/lua/5.1/bit.lua'
	no file '/opt/homebrew/share/lua/5.1/bit/init.lua'
	no file '/opt/homebrew/lib/lua/5.1/bit.lua'
	no file '/opt/homebrew/lib/lua/5.1/bit/init.lua'
	no file '/Users/michalmajchrzak/.luarocks/lib/lua/5.1/bit.so'
	no file './bit.so'
	no file '/opt/homebrew/lib/lua/5.1/bit.so'
	no file '/opt/homebrew/lib/lua/5.1/loadall.so'

it looks that Lapis doesn't have "luabitop" as a dependency.

**Comment by leafo** [comment]
This dependency comes from pgmoon, check here: https://github.com/leafo/pgmoon#dependencies

**Comment by leafo** [comment]
Because pgmoon is designed to run in many different kind of environments, it does not install any dependencies aside from lpeg by default, you are responsible for installing them depending on the environment you wish to run it in.
