### ISSUE TITLE
Lua 5.1 Support

### ISSUE THREAD

**Issue by r0b0t-0** [leafo/lapis#789]
Hi. I only have Lua 5.1.5 on my Mac as I am primarily working on a DEFOLD project. I have ensured that my LUA_PATH  and LUA_CPATH points to 5.1.5. "which Lua" returns my 5.1.5 binary and "lua" in the terminal gives me the 5.1.5 prompt. Luarocks force installs Lua 5.4.7, which I delete thereafter. The problem is that lapis seems to require 5.4 and the error I get when running lapis serve or lapis new is that a files in /opt/homebrew/opt/lua/bin/lua5.4: cannot execute: No such file or directory. I really do not want 5.4.7 because it takes over my terminal.luarocks-51 is deprecated and I cannot find a luarocks that would give me a working lapis. Any ideas on how to get a lapis that works with 5.1

**Comment by leafo** [comment]
You can instruct LuaRocks to use a specific version of Lua with the `--lua-version 5.1` flag. Make sure you use that flag when installing Lapis and any related dependencies.

**Comment by r0b0t-0** [comment]
Thanks so much for a very quick reply! I will give that a try today.
