### ISSUE TITLE
csrf validation may cause lua error on missing csrf token

### ISSUE THREAD

**Issue by martinfelis** [leafo/lapis#88]
In https://github.com/leafo/lapis/blob/master/lapis/csrf.moon#L18 the csrf.validate_token function performs a regex match. If the csrf token however does not contain a '.' the pattern does not match and a nil value is passed to ngx.decode_base64(sig) which causes a Lua error.

I don't know whether that is an actual bug as a valid csrf token will always contain a '.', though. I ran into this by testing the csrf facilities and it took my some time to figure out where the error came from.

**Comment by qaisjp** [comment]
fixed in 09b2b2b3c92abcbcc52d9f12c2bb48ff37847dc2

probably

**Comment by leafo** [comment]
Yup, should be fixed now
